import Head from "next/head";
import React from "react";
import { Client } from "@codetest/editor-client";
import Link from "next/link";
import styled from "@emotion/styled";
import { ArchiveIcon } from "@radix-ui/react-icons";

export default function QAFilesPage({ files }) {
  return (
    <>
      <Head>
        <title>@codetest/reports</title>
      </Head>
      <main
        style={{
          fontFamily: "monospace",
          margin: "auto",
          marginTop: 120,
          width: 400,
        }}
      >
        <h1>
          <code>@codetest/reports</code>
        </h1>
        <p>
          reports coverage generated by <code>@codetest/reports</code> (locally)
          will be listed here
        </p>
        <div
          style={{
            display: "flex",
            flexDirection: "column",
            gap: 8,
          }}
        >
          {files.map((file) => (
            <Link
              href={{
                pathname: `/tests/reports/[key]`,
                query: {
                  key: file,
                },
              }}
            >
              <Row>
                <a href={file}>
                  <ArchiveIcon />
                  <div style={{ width: 8 }} />
                  reports/{file}
                </a>
              </Row>
            </Link>
          ))}
        </div>
      </main>
    </>
  );
}

const Row = styled.div`
  cursor: pointer;
  padding: 16px;
  background: rgba(0, 0, 0, 0.1);
  border-radius: 4;
  border: 1px solid rgba(255, 255, 255, 0.1);

  a {
    display: flex;
    align-items: center;
  }

  &:hover {
    background: rgba(0, 0, 0, 0.2);
  }
`;

export async function getServerSideProps(context: any) {
  const client = Client({
    baseURL: "http://localhost:6627",
  });

  try {
    const { data } = await client.reports();

    return {
      props: {
        files: data.files,
      },
    };
  } catch (e) {
    return {
      redirect: {
        destination: "/tests/reports/how-to-setup",
        permanent: false,
      },
    };
  }
}
