BEGIN;
SELECT plan(25);
SELECT is(public.platform_billing_owner()->>'owner','grida','production default remains Grida');
SELECT ok(NOT has_function_privilege('service_role','grida_platform.transfer_billing_ownership(bigint,text)','EXECUTE'),'broad service key cannot transfer owner');
SELECT ok(NOT has_function_privilege('authenticated','public.platform_billing_owner()','EXECUTE'),'customer cannot inspect private fence');
SELECT ok(NOT has_function_privilege('anon','public.platform_billing_owner()','EXECUTE'),'anonymous cannot inspect private fence');
SELECT is((SELECT count(*)::integer FROM pg_trigger t JOIN pg_class c ON c.oid=t.tgrelid JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='grida_billing' AND t.tgname='platform_billing_write_fence'),6,'all six current financial relations are fenced');
SELECT set_config('test.owner',(SELECT id::text FROM auth.users WHERE email='insider@grida.co'),true);
INSERT INTO public.organization(name,display_name,owner_id) VALUES('m3-fence-before','Before',current_setting('test.owner')::uuid);
SELECT set_config('test.org',(SELECT id::text FROM public.organization WHERE name='m3-fence-before'),true);
SELECT ok(EXISTS(SELECT 1 FROM grida_billing.account WHERE organization_id=current_setting('test.org')::bigint),'default onboarding retains source billing');
SET LOCAL ROLE service_role;
SELECT is(public.platform_billing_owner()->>'epoch','1','service can observe authoritative source mode');
SELECT lives_ok('UPDATE grida_billing.account SET customer_entitled=customer_entitled','source writer remains valid before transfer');
SELECT throws_ok($$SELECT grida_platform.transfer_billing_ownership(1,repeat('a',64))$$,'42501',NULL,'service cannot invoke transfer');
RESET ROLE;
DO $$ BEGIN PERFORM grida_platform.begin_billing_maintenance(1,repeat('a',64)); END $$;
SELECT is(grida_platform.transfer_billing_ownership(1,repeat('a',64))->>'owner','infra','operator transfers locally with retained manifest');
SELECT is(grida_platform.transfer_billing_ownership(1,repeat('a',64))->>'epoch','2','identical handoff retry retains epoch');
SELECT throws_ok($$SELECT grida_platform.transfer_billing_ownership(1,repeat('b',64))$$,'23505',NULL,'different manifest cannot reuse transfer');
SET LOCAL ROLE service_role;
SELECT throws_ok('UPDATE grida_billing.account SET customer_entitled=true','42501',NULL,'service account writes denied after transfer');
SELECT throws_ok('DELETE FROM grida_billing.subscription','42501',NULL,'service subscription writes denied after transfer');
SELECT throws_ok('DELETE FROM grida_billing.product_catalogue','42501',NULL,'catalog writes denied after transfer');
SELECT throws_ok('DELETE FROM grida_billing.stripe_event','42501',NULL,'Stripe projection writes denied after transfer');
SELECT throws_ok('DELETE FROM grida_billing.metronome_event','42501',NULL,'Metronome projection writes denied after transfer');
SELECT throws_ok('DELETE FROM grida_billing.audit','42501',NULL,'audit deletion denied after transfer');
SELECT throws_ok('TRUNCATE grida_billing.audit','42501',NULL,'TRUNCATE cannot bypass fence');
SELECT throws_ok($$SELECT public.fn_billing_set_balance_cache(current_setting('test.org')::bigint,100,true)$$,'42501',NULL,'definer writer cannot bypass fence');
RESET ROLE;
SELECT throws_ok($$UPDATE public.organization SET is_enterprise=NOT is_enterprise WHERE id=current_setting('test.org')::bigint$$,'42501',NULL,'product metadata cannot replace commercial policy');
INSERT INTO public.organization(name,display_name,owner_id) VALUES('m3-fence-after','After',current_setting('test.owner')::uuid);
SELECT ok(NOT EXISTS(SELECT 1 FROM grida_billing.account a JOIN public.organization o ON o.id=a.organization_id WHERE o.name='m3-fence-after'),'new org no longer creates financial source state');
DELETE FROM public.organization WHERE id=current_setting('test.org')::bigint;
SELECT ok(EXISTS(SELECT 1 FROM grida_billing.account WHERE organization_id=current_setting('test.org')::bigint),'canonical deletion retains archived financial identity');
SELECT is((SELECT state FROM grida_platform.account_states WHERE organization_id=current_setting('test.org')::bigint),'deleted','canonical deletion still creates tombstone');
SELECT ok(EXISTS(SELECT 1 FROM grida_platform.product_producers WHERE producer='grida-ai' AND product='grida-ai'),'fixed product producer registered without provider calls');
SELECT * FROM finish();
ROLLBACK;
