BEGIN;
SELECT plan(95);
CREATE TEMP TABLE platform_signatures(signature text PRIMARY KEY, user_callable boolean);
INSERT INTO platform_signatures VALUES
 ('public.platform_source_work_begin(uuid, text, jsonb, uuid)',false),('public.platform_source_work_capture(uuid, jsonb)',false),('public.platform_source_work_finish(uuid)',false),('public.platform_source_webhook_capture(text, text, bytea, jsonb)',false),('public.platform_source_webhook_ack(text, text, text)',false),
 ('public.platform_billing_owner()',false),('public.platform_account_context(text)',true),('public.platform_organizations_page(text)',true),
 ('public.platform_gg_account_snapshots(jsonb, text)',false),('public.platform_lifecycle_page(integer)',false),('public.platform_lifecycle_ack(uuid[])',false),
 ('public.platform_product_execution_claim(text, text, jsonb)',false),('public.platform_product_execution_dispatch(text, text)',false),
 ('public.platform_product_execution_receipt(text, text, jsonb)',false),('public.platform_product_usage_page(integer)',false),('public.platform_product_usage_ack(uuid[])',false);
SELECT is((SELECT array_agg(format('public.%s(%s)',p.proname,oidvectortypes(p.proargtypes)) ORDER BY p.proname) FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname LIKE 'platform_%'),(SELECT array_agg(signature ORDER BY signature) FROM platform_signatures),'complete public RPC family and overload inventory');
SELECT ok(NOT has_function_privilege('anon',to_regprocedure(signature),'EXECUTE'),'anon denied '||signature) FROM platform_signatures ORDER BY signature;
SELECT is(has_function_privilege('authenticated',to_regprocedure(signature),'EXECUTE'),user_callable,'authenticated contract '||signature) FROM platform_signatures ORDER BY signature;
SELECT is(has_function_privilege('service_role',to_regprocedure(signature),'EXECUTE'),NOT user_callable,'service contract '||signature) FROM platform_signatures ORDER BY signature;
SELECT ok(NOT EXISTS(SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace CROSS JOIN LATERAL aclexplode(COALESCE(p.proacl,acldefault('f',p.proowner))) a WHERE (n.nspname='grida_platform' OR n.nspname='public' AND p.proname LIKE 'platform_%') AND a.grantee=0 AND a.privilege_type='EXECUTE'),'no new function PUBLIC execute');
SELECT is((SELECT count(*)::integer FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='grida_platform' AND c.relkind='r' AND c.relrowsecurity AND c.relforcerowsecurity),12,'all private tables force RLS');
SELECT ok(NOT EXISTS(SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace CROSS JOIN (VALUES('anon'),('authenticated'),('service_role')) role(name) WHERE n.nspname='grida_platform' AND c.relkind='r' AND has_table_privilege(role.name,c.oid,'SELECT,INSERT,UPDATE,DELETE')),'no client or service direct read/write on any private table');
DO $$ BEGIN
  PERFORM set_config('test.owner',(SELECT id::text FROM auth.users WHERE email='insider@grida.co'),true);
  PERFORM set_config('test.other',(SELECT id::text FROM auth.users WHERE email='alice@acme.com'),true);
  PERFORM set_config('test.random',(SELECT id::text FROM auth.users WHERE email='random@example.com'),true);
  PERFORM set_config('test.org',(SELECT id::text FROM public.organization WHERE name='local'),true);
END $$;
SET LOCAL ROLE authenticated;
SELECT set_config('request.jwt.claim.sub',current_setting('test.owner'),true);
SELECT is(public.platform_account_context(current_setting('test.org'))->>'role','owner','bearer owner can read own context');
SELECT is(public.platform_account_context(current_setting('test.org'))->>'policy_version','organization-access-1','explicit policy revision');
SELECT ok(NOT (public.platform_account_context(current_setting('test.org')) ? 'projects'),'context contains no shared project authority');
SELECT ok(jsonb_array_length(public.platform_organizations_page()->'data')>0,'member organization list is readable');
SELECT set_config('request.jwt.claim.sub',current_setting('test.other'),true);
SELECT throws_ok($$SELECT public.platform_account_context(current_setting('test.org'))$$,'42501',NULL,'other tenant denied');
SELECT set_config('request.jwt.claim.sub',current_setting('test.random'),true);
SELECT throws_ok($$SELECT public.platform_account_context(current_setting('test.org'))$$,'42501',NULL,'no membership denied');
SELECT is(jsonb_array_length(public.platform_organizations_page()->'data'),0,'no membership lists nothing');
SELECT set_config('request.jwt.claim.sub',current_setting('test.owner'),true);
SELECT set_config('request.jwt.claims',jsonb_build_object('sub',current_setting('test.owner'),'client_id','unregistered')::text,true);
SELECT throws_ok($$SELECT public.platform_account_context(current_setting('test.org'))$$,'42501',NULL,'unregistered OAuth client denied');
SELECT set_config('request.jwt.claims',jsonb_build_object('sub',current_setting('test.owner'))::text,true);
SELECT throws_ok($$SELECT public.platform_account_context('01')$$,'22023',NULL,'noncanonical id denied');
SELECT throws_ok($$SELECT public.platform_lifecycle_page(100)$$,'42501',NULL,'user cannot read lifecycle feed');
SELECT throws_ok($$SELECT public.platform_gg_account_snapshots('[{"id":"1"}]','aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa')$$,'42501',NULL,'user cannot impersonate source observer');
SELECT throws_ok($$SELECT public.platform_product_execution_claim('producer','e','{}')$$,'42501',NULL,'user cannot create producer custody');
SELECT throws_ok($$SELECT * FROM grida_platform.account_states$$,'42501',NULL,'private source state denied');
SELECT throws_ok($$DELETE FROM grida_platform.usage_outbox$$,'42501',NULL,'private receipt deletion denied');
SET LOCAL ROLE anon;
SELECT throws_ok($$SELECT public.platform_account_context('1')$$,'42501',NULL,'anonymous user RPC denied');
RESET ROLE;
INSERT INTO public.organization(name,display_name,owner_id) VALUES('platform-custody-test','Custody',current_setting('test.owner')::uuid);
SELECT set_config('test.created_org',(SELECT id::text FROM public.organization WHERE name='platform-custody-test'),true);
SELECT ok(EXISTS(SELECT 1 FROM grida_billing.account WHERE organization_id=current_setting('test.created_org')::bigint),'old source billing still provisions by default');
SELECT set_config('test.version',(SELECT version::text FROM grida_platform.account_states WHERE organization_id=current_setting('test.created_org')::bigint),true);
UPDATE public.organization SET display_name='Changed directly' WHERE id=current_setting('test.created_org')::bigint;
SELECT is((SELECT version FROM grida_platform.account_states WHERE organization_id=current_setting('test.created_org')::bigint),current_setting('test.version')::bigint+1,'direct SQL rename advances org version');
INSERT INTO public.organization_member(organization_id,user_id) VALUES(current_setting('test.created_org')::bigint,current_setting('test.random')::uuid);
SELECT is((SELECT version FROM grida_platform.account_states WHERE organization_id=current_setting('test.created_org')::bigint),current_setting('test.version')::bigint+2,'direct SQL membership advances org version');
INSERT INTO grida_platform.product_producers(producer,product) VALUES('local.grida.test','grida.text');
SELECT set_config('test.claim',jsonb_build_object('organization_id',current_setting('test.created_org'),'product','grida.text','operation','text','model','fixture','unit','cost_mills','policy_version','fixture-1','request_digest',repeat('a',64),'admission_observed_at',clock_timestamp()::text,'admission_expires_at',(clock_timestamp()+interval '50 seconds')::text)::text,true);
SELECT set_config('test.receipt',((current_setting('test.claim')::jsonb-ARRAY['request_digest','admission_observed_at','admission_expires_at'])||jsonb_build_object('outcome','succeeded','quantity','0.000000000000000001','occurred_at',clock_timestamp()::text,'evidence_digest',repeat('b',64)))::text,true);
SET LOCAL ROLE service_role;
SELECT is(public.platform_gg_account_snapshots(jsonb_build_array(jsonb_build_object('id',current_setting('test.created_org'))),'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa')->'organizations'->0->>'name','platform-custody-test','service snapshot returns current source');
SELECT is(public.platform_gg_account_snapshots('[{"id":"9223372036854775807"}]','aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa')->'organizations'->0->>'source_version','0','unknown organization is denied with zero frontier');
SELECT throws_ok($$SELECT public.platform_gg_account_snapshots('[{"id":"1","project_id":"2"}]','aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa')$$,'22023',NULL,'project authority rejected by SQL');
SELECT throws_ok($$SELECT public.platform_gg_account_snapshots('[{"id":"1"},{"id":"1"}]','aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa')$$,'22023',NULL,'duplicate snapshot references rejected');
SELECT ok(jsonb_array_length(public.platform_lifecycle_page(100)->'events')>0,'service receives durable lifecycle page');
SELECT is(public.platform_product_execution_claim('local.grida.test','execution-1',current_setting('test.claim')::jsonb)->>'created','true','claim commits before provider dispatch');
SELECT is(public.platform_product_execution_claim('local.grida.test','execution-1',current_setting('test.claim')::jsonb)->>'created','false','duplicate claim never creates another execution');
SELECT throws_ok($$SELECT public.platform_product_execution_claim('local.grida.test','execution-1',current_setting('test.claim')::jsonb||'{"unit":"usd_micros"}')$$,'22023',NULL,'GG money unit cannot enter Grida producer claims');
SELECT throws_ok($$SELECT public.platform_product_execution_claim('local.grida.test','execution-1',current_setting('test.claim')::jsonb||'{"model":"different"}')$$,'23505',NULL,'execution identity cannot be rebound');
SELECT is(public.platform_product_execution_dispatch('local.grida.test','execution-1')->>'dispatch','true','first dispatch is admitted once');
SELECT is(public.platform_product_execution_dispatch('local.grida.test','execution-1')->>'dispatch','false','unknown external outcome cannot be automatically dispatched again');
RESET ROLE;
DELETE FROM public.organization WHERE id=current_setting('test.created_org')::bigint;
SELECT is((SELECT state FROM grida_platform.account_states WHERE organization_id=current_setting('test.created_org')::bigint),'deleted','direct SQL delete retains permanent source tombstone');
SELECT ok(EXISTS(SELECT 1 FROM grida_platform.lifecycle_outbox WHERE organization_id=current_setting('test.created_org')::bigint AND payload->>'state'='deleted'),'deletion transaction retains lifecycle event');
SELECT throws_ok(format('INSERT INTO public.organization(id,name,owner_id) OVERRIDING SYSTEM VALUE VALUES(%s,%L,%L)',current_setting('test.created_org'),'platform-custody-test',current_setting('test.owner')),'23514',NULL,'deleted canonical ID cannot be reused');
SET LOCAL ROLE service_role;
SELECT is(public.platform_product_execution_receipt('local.grida.test','execution-1',current_setting('test.receipt')::jsonb)->>'accepted','true','completion evidence persists after organization deletion');
SELECT is(public.platform_product_execution_receipt('local.grida.test','execution-1',current_setting('test.receipt')::jsonb)->>'duplicate','true','exact receipt retry is harmless');
SELECT throws_ok($$SELECT public.platform_product_execution_receipt('local.grida.test','execution-1',current_setting('test.receipt')::jsonb||'{"quantity":"2"}')$$,'23505',NULL,'conflicting receipt rejected');
SELECT throws_ok($$SELECT public.platform_product_execution_claim('local.grida.test','execution-2',current_setting('test.claim')::jsonb)$$,'42501',NULL,'new execution on deleted organization denied');
SELECT is(public.platform_product_usage_page(100)->'events'->0->'receipt'->>'quantity','0.000000000000000001','native quantity retains 18 exact fractional places');
SELECT is(public.platform_product_usage_ack(ARRAY[(public.platform_product_usage_page(100)->'events'->0->>'event_id')::uuid])->>'acknowledged','true','usage acknowledged by permanent event ID');
SELECT is(jsonb_array_length(public.platform_product_usage_page(100)->'events'),0,'acknowledged usage is no longer delivered');
RESET ROLE;
SELECT is((SELECT count(*)::integer FROM grida_platform.usage_outbox WHERE producer='local.grida.test'),1,'ack retains permanent receipt rather than deleting evidence');
SET LOCAL ROLE service_role;
SELECT is(public.platform_lifecycle_ack(ARRAY[(public.platform_lifecycle_page(100)->'events'->0->>'event_id')::uuid])->>'acknowledged','true','lifecycle ACK is explicit after receipt');
RESET ROLE;
SELECT throws_ok('TRUNCATE public.organization CASCADE','23514',NULL,'truncate cannot bypass organization tombstones');
SELECT throws_ok('TRUNCATE public.organization_member CASCADE','23514',NULL,'truncate cannot bypass membership lifecycle');
SELECT * FROM finish();
ROLLBACK;
