packages:
  - "legacy/www"
  - "desktop"
  - "editor"
  - "apps/backgrounds"
  - "apps/docs"
  - "apps/blog"
  - "apps/viewer"
  - "packages/*"
  - "packages/lib/*"
  - "ui/editor-ui/packages/*"
  - "ui/*"
  # - "legacy/web"
  # - "legacy/editor"
  # - "legacy/editor-packages/*"
  # - "apps/*"
  # - "apps/posts"
  # - "packages/.legacy/*"
  # - "externals/code/packages/*"
  # - "externals/code/code"
  # - "externals/boring/packages/*"
