const docs = [
  {
    type: "category",
    label: "Getting Started",
    collapsed: false,
    items: [
      {
        type: "autogenerated",
        dirName: "getting-started",
      },
    ],
  },
  {
    type: "category",
    label: "Concepts",
    collapsed: false,
    items: [
      {
        type: "autogenerated",
        dirName: "concepts",
      },
    ],
  },
  {
    type: "category",
    label: "Assistant",
    items: [
      {
        type: "autogenerated",
        dirName: "assistant",
      },
    ],
  },
  {
    type: "category",
    label: "Reference",
    items: [
      {
        type: "category",
        label: "Design to code Reference",
        items: [
          {
            type: "autogenerated",
            dirName: "@designto-code",
          },
        ],
      },
      {
        type: "category",
        label: "Flags Reference",
        items: [
          {
            type: "autogenerated",
            dirName: "@designto-code/flags",
          },
        ],
      },
      {
        type: "category",
        label: "Conventions",
        items: [
          {
            type: "autogenerated",
            dirName: "conventions",
          },
        ],
      },
    ],
  },
  {
    type: "category",
    label: "Together",
    items: [
      {
        type: "autogenerated",
        dirName: "together",
      },
    ],
  },
];

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: docs,
};

module.exports = sidebars;
