export type EncodedMediaFile = Readonly<{
  base64: string;
  media_type: string;
}>;

/** Decode generated bytes into the same local `File` boundary as Open. */
export function generatedMediaFile(
  encoded: EncodedMediaFile,
  filename: string
): File {
  const binary = atob(encoded.base64.replace(/[\t\n\f\r ]/g, ""));
  const bytes = new Uint8Array(binary.length);
  for (let index = 0; index < binary.length; index++) {
    bytes[index] = binary.charCodeAt(index);
  }
  return new File([bytes], filename, { type: encoded.media_type });
}
