/**
 * GRIDA-SEC-004 — agent filesystem scope policy.
 *
 * The protected (no-clobber) set: config and state the agent's fs-edit tools
 * must never overwrite, even inside a writable root. This is the fs-tool half
 * of the model; the shell half is covered structurally by the OS sandbox's
 * mandatory-deny set (git hooks, shell rc, `.mcp.json`) for any spawned child.
 *
 * It answers "don't corrupt this", a sibling to "don't leak this" (the
 * sensitive-read set). Like the sensitive set it is a managed list — the one
 * place a hand-maintained list is correct, because it enumerates what to
 * REFUSE and so fails safe: a gap costs an unprotected clobber the agent could
 * already do via the shell, never a silent breach. Matched by path segment /
 * basename (not a glob engine) so a `.git` anywhere in the tree is covered.
 */

/** Directories whose entire subtree is off-limits to fs-tool writes. */
const PROTECTED_DIRS: ReadonlySet<string> = new Set([".git", ".hg", ".svn"]);

/** Exact filenames (basename match) the fs-edit tools must not write. */
const PROTECTED_FILES: ReadonlySet<string> = new Set([
  // VCS config
  ".gitconfig",
  ".gitmodules",
  ".gitattributes",
  // shell rc / env
  ".bashrc",
  ".bash_profile",
  ".zshrc",
  ".zprofile",
  ".zshenv",
  ".profile",
  ".envrc",
  // package-manager config
  ".npmrc",
  ".yarnrc",
  ".yarnrc.yml",
  ".pnpmfile.cjs",
  // lockfiles — regenerated by the package manager, not hand-edited
  "package-lock.json",
  "pnpm-lock.yaml",
  "yarn.lock",
  "bun.lockb",
  // agent / tool config that could redirect future runs
  ".mcp.json",
  ".claude.json",
]);

/**
 * Whether `path` (an AgentFs logical "/"-rooted path or a workspace-relative
 * path) is a protected no-clobber target. Splits into segments and checks: any
 * segment a protected dir, or the basename a protected file.
 */
export function isProtectedWrite(path: string): boolean {
  const segments = path.split(/[/\\]/).filter((s) => s.length > 0);
  if (segments.length === 0) return false;
  if (segments.some((s) => PROTECTED_DIRS.has(s))) return true;
  const basename = segments[segments.length - 1];
  return PROTECTED_FILES.has(basename);
}
