/* eslint-disable */
export const cursors = {
  "alias": { src: "/assets/css-cursors-macos/alias.png", label: "Alias" },
  "cell": { src: "/assets/css-cursors-macos/cell.png", label: "Cell" },
  "col-resize": { src: "/assets/css-cursors-macos/col-resize.png", label: "Column Resize" },
  "copy": { src: "/assets/css-cursors-macos/copy.png", label: "Copy" },
  "crosshair": { src: "/assets/css-cursors-macos/crosshair.png", label: "Crosshair" },
  "default": { src: "/assets/css-cursors-macos/default.png", label: "Default" },
  "e-resize": { src: "/assets/css-cursors-macos/e-resize.png", label: "East Resize" },
  "ew-resize": { src: "/assets/css-cursors-macos/ew-resize.png", label: "East-West Resize" },
  "grab": { src: "/assets/css-cursors-macos/grab.png", label: "Grab" },
  "grabbing": { src: "/assets/css-cursors-macos/grabbing.png", label: "Grabbing" },
  "help": { src: "/assets/css-cursors-macos/help.png", label: "Help" },
  "move": { src: "/assets/css-cursors-macos/move.png", label: "Move" },
  "n-resize": { src: "/assets/css-cursors-macos/n-resize.png", label: "North Resize" },
  "ne-resize": { src: "/assets/css-cursors-macos/ne-resize.png", label: "North-East Resize" },
  "nesw-resize": { src: "/assets/css-cursors-macos/nesw-resize.png", label: "North-East/South-West Resize" },
  "not-allowed": { src: "/assets/css-cursors-macos/not-allowed.png", label: "Not Allowed" },
  "ns-resize": { src: "/assets/css-cursors-macos/ns-resize.png", label: "North-South Resize" },
  "nw-resize": { src: "/assets/css-cursors-macos/nw-resize.png", label: "North-West Resize" },
  "nwse-resize": { src: "/assets/css-cursors-macos/nwse-resize.png", label: "North-West/South-East Resize" },
  "pointer": { src: "/assets/css-cursors-macos/pointer.png", label: "Pointer" },
  "progress": { src: "/assets/css-cursors-macos/progress.png", label: "Progress" },
  "row-resize": { src: "/assets/css-cursors-macos/row-resize.png", label: "Row Resize" },
  "s-resize": { src: "/assets/css-cursors-macos/s-resize.png", label: "South Resize" },
  "se-resize": { src: "/assets/css-cursors-macos/se-resize.png", label: "South-East Resize" },
  "sw-resize": { src: "/assets/css-cursors-macos/sw-resize.png", label: "South-West Resize" },
  "text": { src: "/assets/css-cursors-macos/text.png", label: "Text" },
  "vertical-text": { src: "/assets/css-cursors-macos/vertical-text.png", label: "Vertical Text" },
  "w-resize": { src: "/assets/css-cursors-macos/w-resize.png", label: "West Resize" },
  "zoom-in": { src: "/assets/css-cursors-macos/zoom-in.png", label: "Zoom In" },
  "zoom-out": { src: "/assets/css-cursors-macos/zoom-out.png", label: "Zoom Out" },
};