import { grida } from "@/grida";

// eslint-disable-next-line import/no-anonymous-default-export
export default {
  root_id: "playground",
  nodes: {
    playground: {
      id: "playground",
      name: "playground",
      type: "container",
      active: true,
      locked: false,
      expanded: true,
      opacity: 1,
      zIndex: 0,
      rotation: 0,
      position: "relative",
      width: 960,
      height: 540,
      fill: { type: "solid", color: { r: 0, g: 0, b: 0, a: 1 } },
      cornerRadius: 0,
      padding: 0,
      boxShadow: {
        color: { r: 0, g: 0, b: 0, a: 0.1 },
        offset: [0, 0],
        blur: 10,
        spread: 0,
      },
      style: {},
      children: ["card_1_bg", "card_2_bg", "card_3_bg"],
      layout: "flow",
      direction: "horizontal",
      mainAxisAlignment: "start",
      crossAxisAlignment: "start",
      mainAxisGap: 0,
      crossAxisGap: 0,
    },
    card_1_bg: {
      id: "card_1_bg",
      name: "card_1_bg",
      type: "image",
      active: true,
      locked: false,
      opacity: 1,
      zIndex: -1,
      rotation: 0,
      width: 300,
      height: 510,
      position: "absolute",
      top: 15,
      left: 15,
      fit: "cover",
      cornerRadius: 0,
      fill: { type: "solid", color: { r: 255, g: 255, b: 255, a: 0.1 } },
      style: {},
    },
    card_2_bg: {
      id: "card_2_bg",
      name: "card_2_bg",
      type: "image",
      active: true,
      locked: false,
      opacity: 1,
      zIndex: -1,
      rotation: 0,
      width: 300,
      height: 510,
      position: "absolute",
      top: 15,
      left: 330,
      fit: "cover",
      cornerRadius: 0,
      fill: { type: "solid", color: { r: 255, g: 255, b: 255, a: 0.1 } },
      style: {},
    },
    card_3_bg: {
      id: "card_3_bg",
      name: "card_3_bg",
      type: "image",
      active: true,
      locked: false,
      opacity: 1,
      zIndex: -1,
      rotation: 0,
      width: 300,
      height: 510,
      position: "absolute",
      top: 15,
      left: 645,
      fit: "cover",
      cornerRadius: 0,
      fill: { type: "solid", color: { r: 255, g: 255, b: 255, a: 0.1 } },
      style: {},
    },
  },
} satisfies grida.program.document.IDocumentDefinition;
