import { grida } from "@/grida";

// eslint-disable-next-line import/no-anonymous-default-export
export default {
  root_id: "playground",
  nodes: {
    playground: {
      id: "playground",
      name: "playground",
      type: "container",
      active: true,
      locked: false,
      expanded: true,
      opacity: 1,
      zIndex: 0,
      style: {
        position: "relative",
        width: 960,
        height: 540,
        backgroundColor: "white",
        boxShadow: "0 0 10px rgba(0,0,0,0.1)",
      },
      children: ["sticker", "h1", "p"],
    },
    sticker: {
      id: "sticker",
      name: "sticker",
      type: "container",
      active: true,
      locked: false,
      expanded: true,
      opacity: 1,
      zIndex: 0,
      style: {
        position: "absolute",
        top: 100,
        left: 100,
        width: 100,
        height: 100,
        backgroundColor: "#000",
      },
    },
    h1: {
      id: "h1",
      name: "h1",
      type: "text",
      active: true,
      locked: false,
      text: "데이터로 트렌드를 읽고, 소통으로 브랜드를 키우다",
      opacity: 1,
      zIndex: 0,
      style: {
        fontSize: 32,
        fontWeight: 500,
        position: "absolute",
        top: 50,
        left: 50,
      },
    },
    p: {
      id: "p",
      name: "p",
      type: "text",
      active: true,
      locked: false,
      text: "안녕하세요, 홍길동입니다. 저는 데이터를 통해 트렌드를 분석하고, 소통을 통해 브랜드의 가치를 높이는 마케터입니다. 빠르게 변하는 시장 환경 속에서 정확한 인사이트를 제공하며, 브랜드의 성장을 돕는 것을 목표로 하고 있습니다. 창의적 사고와 데이터 기반 전략을 결합해 차별화된 브랜드 경험을 만들어가는 데 집중합니다.",
      opacity: 1,
      zIndex: 0,
      style: {
        fontSize: 16,
        fontWeight: 400,
        position: "absolute",
        top: 200,
        left: 50,
      },
    },
  },
} satisfies grida.program.document.IDocumentDefinition;
