//! Fast hasher for u64-keyed HashMaps in the rendering hot path.
//!
//! The default `HashMap` uses SipHash-1-3, which provides DoS resistance
//! at ~25ns per hash. For trusted-input rendering caches keyed by `NodeId`
//! (u64), we can use a much faster multiplicative hash (~3ns) since there
//! is no untrusted input to defend against.
//!
//! This is the same approach as `rustc-hash` (FxHash): multiply by a large
//! odd constant to scatter bits, then use the result directly as the hash.

use std::collections::HashMap;
use std::hash::{BuildHasher, Hasher};

/// A fast hasher for integer keys.
///
/// Uses a single multiply to distribute bits. Suitable for u64 keys
/// (NodeId) and (u64, u64) tuple keys used in the picture/geometry/
/// compositor caches.
#[derive(Default)]
pub struct NodeIdHasher {
    hash: u64,
}

impl Hasher for NodeIdHasher {
    #[inline]
    fn write(&mut self, bytes: &[u8]) {
        // For arbitrary byte sequences, use a simple FNV-like combine.
        for &b in bytes {
            self.hash = self.hash.wrapping_mul(0x100000001b3).wrapping_add(b as u64);
        }
    }

    #[inline]
    fn write_u64(&mut self, i: u64) {
        // FxHash: XOR-fold then multiply by a large odd constant.
        // This is the primary fast path for NodeId (u64) keys.
        self.hash ^= i;
        self.hash = self.hash.wrapping_mul(0x517cc1b727220a95);
    }

    #[inline]
    fn finish(&self) -> u64 {
        self.hash
    }
}

/// BuildHasher that produces `NodeIdHasher` instances.
#[derive(Clone, Default)]
pub struct NodeIdBuildHasher;

impl BuildHasher for NodeIdBuildHasher {
    type Hasher = NodeIdHasher;

    #[inline]
    fn build_hasher(&self) -> NodeIdHasher {
        NodeIdHasher::default()
    }
}

/// A HashMap using the fast NodeId hasher.
///
/// Use this for caches keyed by `NodeId` (u64) or `(NodeId, u64)` tuples
/// where keys come from trusted internal sources (no DoS risk).
pub type NodeIdHashMap<K, V> = HashMap<K, V, NodeIdBuildHasher>;

/// Create a new empty NodeIdHashMap.
#[inline]
pub fn new_node_id_map<K, V>() -> NodeIdHashMap<K, V> {
    HashMap::with_hasher(NodeIdBuildHasher)
}

/// Create a new NodeIdHashMap with the specified capacity.
#[inline]
pub fn new_node_id_map_with_capacity<K, V>(capacity: usize) -> NodeIdHashMap<K, V> {
    HashMap::with_capacity_and_hasher(capacity, NodeIdBuildHasher)
}

// ---------------------------------------------------------------------------
// DenseNodeMap — Vec-indexed storage for sequential NodeId keys
// ---------------------------------------------------------------------------

use crate::node::id::NodeId;

/// A dense, Vec-backed map keyed by `NodeId` (sequential u64 starting at 0).
///
/// Replaces `HashMap<NodeId, V>` in hot paths where NodeIds are generated by
/// a counter. Provides O(1) access with zero hashing and excellent cache
/// locality — critical for WASM where HashMap overhead is 10–30× native.
#[derive(Debug, Clone)]
pub struct DenseNodeMap<V> {
    slots: Vec<Option<V>>,
    len: usize,
}

impl<V> DenseNodeMap<V> {
    #[inline]
    pub fn new() -> Self {
        Self {
            slots: Vec::new(),
            len: 0,
        }
    }

    #[inline]
    pub fn with_capacity(capacity: usize) -> Self {
        let mut slots = Vec::with_capacity(capacity);
        slots.resize_with(capacity, || None);
        Self { slots, len: 0 }
    }

    #[inline]
    pub fn insert(&mut self, id: NodeId, value: V) -> Option<V> {
        let idx = id as usize;
        if idx >= self.slots.len() {
            self.slots.resize_with(idx + 1, || None);
        }
        let old = self.slots[idx].take();
        self.slots[idx] = Some(value);
        if old.is_none() {
            self.len += 1;
        }
        old
    }

    #[inline]
    pub fn get(&self, id: &NodeId) -> Option<&V> {
        self.slots.get(*id as usize).and_then(|s| s.as_ref())
    }

    #[inline]
    pub fn get_mut(&mut self, id: &NodeId) -> Option<&mut V> {
        self.slots.get_mut(*id as usize).and_then(|s| s.as_mut())
    }

    #[inline]
    pub fn remove(&mut self, id: &NodeId) -> Option<V> {
        let idx = *id as usize;
        if idx < self.slots.len() {
            let old = self.slots[idx].take();
            if old.is_some() {
                self.len -= 1;
            }
            old
        } else {
            None
        }
    }

    #[inline]
    pub fn contains_key(&self, id: &NodeId) -> bool {
        self.get(id).is_some()
    }

    #[inline]
    pub fn len(&self) -> usize {
        self.len
    }

    #[inline]
    pub fn is_empty(&self) -> bool {
        self.len == 0
    }

    pub fn clear(&mut self) {
        for slot in self.slots.iter_mut() {
            *slot = None;
        }
        self.len = 0;
    }

    /// Pre-allocate storage so that IDs up to `capacity - 1` can be inserted
    /// without reallocation.
    pub fn reserve(&mut self, capacity: usize) {
        if capacity > self.slots.len() {
            self.slots.resize_with(capacity, || None);
        }
    }

    /// Iterate over occupied entries as `(NodeId, &V)`.
    pub fn iter(&self) -> DenseNodeMapIter<'_, V> {
        DenseNodeMapIter {
            inner: self.slots.iter().enumerate(),
        }
    }

    /// Iterate over occupied entries as `(NodeId, &mut V)`.
    pub fn iter_mut(&mut self) -> DenseNodeMapIterMut<'_, V> {
        DenseNodeMapIterMut {
            inner: self.slots.iter_mut().enumerate(),
        }
    }

    /// Retain only entries satisfying a predicate.
    pub fn retain<F: FnMut(NodeId, &mut V) -> bool>(&mut self, mut f: F) {
        for (idx, slot) in self.slots.iter_mut().enumerate() {
            if let Some(ref mut v) = slot {
                if !f(idx as NodeId, v) {
                    *slot = None;
                    self.len -= 1;
                }
            }
        }
    }

    /// Get the allocated capacity (max NodeId + 1 that fits without realloc).
    #[inline]
    pub fn capacity(&self) -> usize {
        self.slots.len()
    }
}

impl<V> Default for DenseNodeMap<V> {
    fn default() -> Self {
        Self::new()
    }
}

/// Iterator over `(NodeId, &V)` pairs in a `DenseNodeMap`.
pub struct DenseNodeMapIter<'a, V> {
    inner: std::iter::Enumerate<std::slice::Iter<'a, Option<V>>>,
}

impl<'a, V> Iterator for DenseNodeMapIter<'a, V> {
    type Item = (NodeId, &'a V);

    #[inline]
    fn next(&mut self) -> Option<Self::Item> {
        loop {
            match self.inner.next() {
                Some((idx, Some(v))) => return Some((idx as NodeId, v)),
                Some((_, None)) => continue,
                None => return None,
            }
        }
    }
}

/// Iterator over `(NodeId, &mut V)` pairs in a `DenseNodeMap`.
pub struct DenseNodeMapIterMut<'a, V> {
    inner: std::iter::Enumerate<std::slice::IterMut<'a, Option<V>>>,
}

impl<'a, V> Iterator for DenseNodeMapIterMut<'a, V> {
    type Item = (NodeId, &'a mut V);

    #[inline]
    fn next(&mut self) -> Option<Self::Item> {
        loop {
            match self.inner.next() {
                Some((idx, Some(v))) => return Some((idx as NodeId, v)),
                Some((_, None)) => continue,
                None => return None,
            }
        }
    }
}

impl<'a, V> IntoIterator for &'a DenseNodeMap<V> {
    type Item = (NodeId, &'a V);
    type IntoIter = DenseNodeMapIter<'a, V>;

    fn into_iter(self) -> Self::IntoIter {
        self.iter()
    }
}

impl<V> FromIterator<(NodeId, V)> for DenseNodeMap<V> {
    fn from_iter<T: IntoIterator<Item = (NodeId, V)>>(iter: T) -> Self {
        let iter = iter.into_iter();
        let (lower, _) = iter.size_hint();
        let mut map = Self::with_capacity(lower);
        for (id, v) in iter {
            map.insert(id, v);
        }
        map
    }
}
