[package]
name = "grida-canvas-fonts"
version = "0.1.0"
edition = "2021"

[dependencies]
ttf-parser = "0.25"

[dependencies.serde]
version = "1.0"
features = ["derive"]
optional = true

[dev-dependencies]
serde_json = "1.0"

[features]
default = []
serde = ["dep:serde"]
