import assert from "node:assert/strict";
import { execFile } from "node:child_process";
import { createHash } from "node:crypto";
import { mkdtemp, readFile, readdir, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { parseArgs, promisify } from "node:util";

const exec = promisify(execFile);
const root = fileURLToPath(new URL("../../", import.meta.url));
const destination = path.join(root, "packages/grida-cli");
const hash = (data) => createHash("sha256").update(data).digest("hex");

export async function generateNotices(check = false) {
  const platforms = JSON.parse(
    await readFile(path.join(destination, "native/platforms.json"), "utf8")
  );
  const version = (
    await exec("cargo", ["about", "--version"], { cwd: root })
  ).stdout.trim();
  assert.equal(
    version,
    "cargo-about 0.8.2",
    "Use the reviewed cargo-about version"
  );
  const scratch = await mkdtemp(path.join(tmpdir(), "grida-native-notices-"));
  try {
    const output = path.join(scratch, "licenses.json");
    await exec(
      "cargo",
      [
        "about",
        "generate",
        "--manifest-path",
        "crates/grida-cli/Cargo.toml",
        "--config",
        "scripts/cli-release/about.toml",
        "--offline",
        "--locked",
        "--fail",
        ...platforms.flatMap((p) => ["--target", p.target]),
        "--format",
        "json",
        "--output-file",
        output,
      ],
      { cwd: root, timeout: 120_000, maxBuffer: 4 * 1024 * 1024 }
    );
    const about = JSON.parse(await readFile(output, "utf8"));
    const crates = about.crates
      .filter((crate) => crate.package.source !== null)
      .map(({ package: p, license }) => ({
        name: p.name,
        version: p.version,
        license,
        repository: p.repository,
      }))
      .sort((a, b) =>
        `${a.name}@${a.version}`.localeCompare(`${b.name}@${b.version}`, "en")
      );
    const recognized = about.licenses
      .map((license) => ({
        id: license.id,
        text: license.text.replaceAll("\r\n", "\n"),
        crates: license.used_by
          .map(({ crate }) => `${crate.name}@${crate.version}`)
          .sort(),
      }))
      .sort((a, b) =>
        `${a.id}:${hash(a.text)}`.localeCompare(`${b.id}:${hash(b.text)}`, "en")
      );
    const supplemental = [];
    // Include packaged copyright/notice files even when license identification
    // synthesized standard SPDX text (notably AWS-LC's composite native notice).
    for (const { package: p } of about.crates) {
      if (p.source === null) continue;
      const directory = path.dirname(p.manifest_path);
      for (const filename of (await readdir(directory))
        .filter((name) =>
          /^(?:licen[cs]e|notice|copyright)(?:[._-].*)?$/i.test(name)
        )
        .sort()) {
        let text;
        try {
          text = await readFile(path.join(directory, filename), "utf8");
        } catch (error) {
          if (error.code === "EISDIR") continue;
          throw error;
        }
        assert(text.length < 1024 * 1024, "Unexpected license file size");
        supplemental.push({
          crate: `${p.name}@${p.version}`,
          file: filename,
          text: text.replaceAll("\r\n", "\n"),
        });
      }
    }
    supplemental.sort((a, b) =>
      `${a.crate}/${a.file}`.localeCompare(`${b.crate}/${b.file}`, "en")
    );
    const inventory = {
      format: 1,
      generator: version,
      cargo_lock_sha256: hash(await readFile(path.join(root, "Cargo.lock"))),
      targets: platforms.map((p) => p.target),
      crates,
    };
    let notice =
      "Grida native CLI — third-party notices\n\nGenerated by cargo-about 0.8.2 from the locked runtime/build dependency closure for the eight shipped targets. Development-only dependencies are excluded. License alternatives below record upstream declarations; the accepted texts and copyright notices follow.\n\n";
    notice += crates
      .map(
        (c) => `${c.name} ${c.version} — ${c.license}\n${c.repository ?? ""}`
      )
      .join("\n\n");
    const texts = new Map();
    const include = (text, label) => {
      const normalized = text.replace(/[\t ]+$/gm, "").trim();
      if (!texts.has(normalized)) texts.set(normalized, new Set());
      texts.get(normalized).add(label);
    };
    for (const license of recognized)
      include(license.text, `${license.id}: ${license.crates.join(", ")}`);
    for (const extra of supplemental)
      include(extra.text, `Upstream notice: ${extra.crate}/${extra.file}`);
    for (const [text, labels] of [...texts].sort(([a], [b]) =>
      hash(a).localeCompare(hash(b), "en")
    ))
      notice += `\n\n${"=".repeat(72)}\n${[...labels].sort().join("\n")}\n${"=".repeat(72)}\n${text}\n`;
    for (const [file, data] of [
      ["native/licenses.json", JSON.stringify(inventory, null, 2) + "\n"],
      ["THIRD-PARTY-NOTICES.txt", notice],
    ]) {
      if (check)
        assert.equal(
          await readFile(path.join(destination, file), "utf8"),
          data,
          `Refresh native ${file}`
        );
      else await writeFile(path.join(destination, file), data);
    }
    return {
      crates: crates.length,
      recognized_license_texts: recognized.length,
      supplemental_notice_files: supplemental.length,
      unique_texts: texts.size,
    };
  } finally {
    await rm(scratch, { recursive: true, force: true });
  }
}

if (
  process.argv[1] &&
  path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)
) {
  const { values } = parseArgs({ options: { check: { type: "boolean" } } });
  generateNotices(values.check)
    .then((result) => process.stdout.write(JSON.stringify(result) + "\n"))
    .catch((error) => {
      process.stderr.write(`${error.message}\n`);
      process.exitCode = 1;
    });
}
