export const GRIDA_FORMS_RESPONSE_BUCKET_UPLOAD_LIMIT = 52428800; // 50MB
export const GRIDA_FORMS_RESPONSE_MULTIPART_FILE_UOLOAD_LIMIT = 5242880; // 5MB
export const GRIDA_FORMS_RESPONSE_FILES_MAX_COUNT_PER_FIELD = 10; // 10 files
export const GRIDA_FORMS_RESPONSE_BUCKET = "grida-forms-response";
