/**
 * Cross-boundary FBS golden tests (Rust encode → TS decode).
 *
 * Decodes `.grida` files generated by:
 *   cargo run -p grida-dev -- svg-to-grida
 *
 * The Rust side asserts the same expectations on the same files
 * (crates/grida-canvas/tests/fbs_golden.rs).
 *
 * To test with custom SVGs:
 *   cargo run -p grida-dev -- svg-to-grida path/to/svgs -r
 *   pnpm vitest run fbs-cross-boundary
 */
import { describe, it, expect } from "vitest";
import { format } from "../../grida-canvas-io/format";
import fs from "fs";
import path from "path";

const GENERATED_DIR = path.resolve(
  __dirname,
  "../../../fixtures/test-svg/.generated"
);

function hasGeneratedDir(): boolean {
  return fs.existsSync(GENERATED_DIR);
}

function loadGolden(name: string) {
  const filePath = path.join(GENERATED_DIR, `${name}.grida`);
  const bytes = fs.readFileSync(filePath);
  return format.document.decode.fromFlatbuffer(new Uint8Array(bytes));
}

function listGoldens(): string[] {
  if (!hasGeneratedDir()) return [];
  return fs
    .readdirSync(GENERATED_DIR)
    .filter((f) => f.endsWith(".grida"))
    .map((f) => f.replace(".grida", ""));
}

// ─── Bulk decode: every .grida file must decode without error ─────────────

describe("FBS golden: all files decode (Rust encode → TS decode)", () => {
  const goldens = listGoldens();

  it.skipIf(goldens.length === 0)(
    "generated directory exists with files",
    () => {
      expect(goldens.length).toBeGreaterThan(0);
    }
  );

  it.each(goldens.map((g) => [g]))("%s decodes successfully", (name) => {
    const doc = loadGolden(name);
    expect(Object.keys(doc.nodes).length).toBeGreaterThan(0);
    expect(doc.scenes_ref.length).toBeGreaterThan(0);
  });
});

// ─── Specific assertions: targeted checks on known fields ─────────────────
//
// Each assertion here corresponds to a known cross-boundary issue that was
// fixed. When a new codec bug is found, add a targeted assertion — not a
// generic snap comparison.

describe.skipIf(!hasGeneratedDir())(
  "FBS golden: specific assertions (Rust encode → TS decode)",
  () => {
    it("gradient-vertical: xy1/xy2 endpoints", () => {
      const doc = loadGolden("paint-linear-gradient-vertical-01");
      const vector = Object.values(doc.nodes).find(
        (n) =>
          n.type === "vector" &&
          "fill_paints" in n &&
          Array.isArray((n as any).fill_paints) &&
          (n as any).fill_paints.length > 0
      ) as any;
      expect(vector).toBeDefined();

      const paint = vector.fill_paints[0];
      expect(paint.type).toBe("linear_gradient");
      expect(paint.xy1).toBeDefined();
      expect(paint.xy2).toBeDefined();
      expect(paint.xy1[0]).toBeCloseTo(-1, 1);
      expect(paint.xy1[1]).toBeCloseTo(-1, 1);
      expect(paint.xy2[0]).toBeCloseTo(-1, 1);
      expect(paint.xy2[1]).toBeCloseTo(1, 1);
    });

    // TODO: gradient transform normalization produces non-identity
    it.fails("gradient-horizontal: identity transform", () => {
      const doc = loadGolden("paint-linear-gradient-01");
      const vector = Object.values(doc.nodes).find(
        (n) =>
          n.type === "vector" &&
          "fill_paints" in n &&
          (n as any).fill_paints?.length > 0
      ) as any;
      const t = vector.fill_paints[0].transform;
      expect(t[0][0]).toBeCloseTo(1, 2);
      expect(t[0][1]).toBeCloseTo(0, 2);
      expect(t[1][0]).toBeCloseTo(0, 2);
      expect(t[1][1]).toBeCloseTo(1, 2);
    });

    it("transforms-nested: groups with translate(250,250)", () => {
      const doc = loadGolden("transforms-nested");
      const groups = Object.values(doc.nodes).filter(
        (n) => n.type === "group"
      );
      expect(groups.length).toBeGreaterThanOrEqual(3);
      const hasTranslate = groups.some(
        (g: any) =>
          Math.abs((g.layout_inset_left ?? 0) - 250) < 1 &&
          Math.abs((g.layout_inset_top ?? 0) - 250) < 1
      );
      expect(hasTranslate).toBe(true);
    });

    // Known limitation: TS SDK only supports rotation on groups.
    // Scale/skew preserved in FBS but lost in TS model.
    it.fails("transforms-nested: group with scale(0.8, 1.2)", () => {
      const doc = loadGolden("transforms-nested");
      const groups = Object.values(doc.nodes).filter(
        (n) => n.type === "group"
      ) as any[];
      const hasScale = groups.some(
        (g: any) =>
          g.post_layout_transform &&
          Math.abs(g.post_layout_transform[0][0] - 0.8) < 0.01 &&
          Math.abs(g.post_layout_transform[1][1] - 1.2) < 0.01
      );
      expect(hasScale).toBe(true);
    });

    it("stroke-dasharray: stroked vectors exist", () => {
      const doc = loadGolden("stroke-dasharray");
      const hasStroke = Object.values(doc.nodes).some(
        (n) =>
          n.type === "vector" &&
          "stroke_paints" in n &&
          Array.isArray((n as any).stroke_paints) &&
          (n as any).stroke_paints.length > 0
      );
      expect(hasStroke).toBe(true);
    });

    it("stroke-dasharray: dash array values preserved", () => {
      const doc = loadGolden("stroke-dasharray");
      const vector = Object.values(doc.nodes).find(
        (n) =>
          n.type === "vector" &&
          "stroke_paints" in n &&
          (n as any).stroke_paints?.length > 0
      ) as any;
      expect(vector).toBeDefined();
      expect(vector.stroke_dash_array).toBeDefined();
      expect(vector.stroke_dash_array.length).toBeGreaterThan(0);
    });
  }
);
