import { z } from "zod";

export const ZFormInputType = z.enum([
  "text",
  "textarea",
  "tel",
  "url",
  "checkbox",
  "checkboxes",
  "switch",
  "toggle",
  "toggle-group",
  "radio",
  "number",
  "date",
  "datetime-local",
  "month",
  "week",
  "time",
  "email",
  "file",
  "image",
  "select",
  "latlng",
  "password",
  "color",
  "country",
  "payment",
  "hidden",
  "signature",
  "range",
]);

export const ZFormFieldAutocompleteType = z.enum([
  "off",
  "on",
  "name",
  "honorific-prefix",
  "given-name",
  "additional-name",
  "family-name",
  "honorific-suffix",
  "nickname",
  "email",
  "username",
  "new-password",
  "current-password",
  "one-time-code",
  "organization-title",
  "organization",
  "street-address",
  "shipping",
  "billing",
  "address-line1",
  "address-line2",
  "address-line3",
  "address-level4",
  "address-level3",
  "address-level2",
  "address-level1",
  "country",
  "country-name",
  "postal-code",
  "cc-name",
  "cc-given-name",
  "cc-additional-name",
  "cc-family-name",
  "cc-number",
  "cc-exp",
  "cc-exp-month",
  "cc-exp-year",
  "cc-csc",
  "cc-type",
  "transaction-currency",
  "transaction-amount",
  "language",
  "bday",
  "bday-day",
  "bday-month",
  "bday-year",
  "sex",
  "tel",
  "tel-country-code",
  "tel-national",
  "tel-area-code",
  "tel-local",
  "tel-extension",
  "impp",
  "url",
  "photo",
  "webauthn",
]);

export const ZJSONOption = z.object({
  value: z.string(),
  label: z.string().optional(),
  src: z.string().optional(),
  disabled: z.boolean().optional(),
});

export const ZJSONField = z.object({
  name: z.string(),
  label: z.string().optional(),
  placeholder: z.string().optional(),
  required: z.boolean().optional(),
  pattern: z.string().optional(),
  type: ZFormInputType.or(ZFormInputType.array()), // Simplified for direct or array of `FormInputType`
  options: z.array(ZJSONOption.or(z.string()).or(z.number())).optional(),
  multiple: z.boolean().optional(),
  autocomplete: ZFormFieldAutocompleteType.or(
    ZFormFieldAutocompleteType.array()
  ).optional(),
});

export const ZJSONForm = z.object({
  title: z.string().optional(),
  name: z.string(),
  description: z.string().optional(),
  action: z.string().optional(),
  enctype: z
    .enum([
      "application/x-www-form-urlencoded",
      "multipart/form-data",
      "text/plain",
    ])
    .optional(),
  method: z.enum(["get", "post", "dialog"]).optional(),
  novalidate: z.boolean().optional(),
  target: z.enum(["_blank", "_self", "_parent", "_top"]).optional(),
  fields: z.array(ZJSONField).optional(),
});
