// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

/**
 * Rust: `Axis`
 */
export enum Axis {
  Horizontal = 0,
  Vertical = 1
}
