// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { BasicShapeNodeType } from '../grida/basic-shape-node-type';
import { CanonicalLayerShape, unionToCanonicalLayerShape, unionListToCanonicalLayerShape } from '../grida/canonical-layer-shape';
import { LayerTrait } from '../grida/layer-trait';
import { PaintStackItem } from '../grida/paint-stack-item';
import { RectangularCornerRadius } from '../grida/rectangular-corner-radius';
import { RectangularStrokeWidth } from '../grida/rectangular-stroke-width';
import { StrokeStyle } from '../grida/stroke-style';
import { SystemNodeTrait } from '../grida/system-node-trait';
import { VariableWidthProfile } from '../grida/variable-width-profile';


export class BasicShapeNode {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):BasicShapeNode {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsBasicShapeNode(bb:flatbuffers.ByteBuffer, obj?:BasicShapeNode):BasicShapeNode {
  return (obj || new BasicShapeNode()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsBasicShapeNode(bb:flatbuffers.ByteBuffer, obj?:BasicShapeNode):BasicShapeNode {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new BasicShapeNode()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

node(obj?:SystemNodeTrait):SystemNodeTrait|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new SystemNodeTrait()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

layer(obj?:LayerTrait):LayerTrait|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new LayerTrait()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

/**
 * shape of the type, must align with the shape. this is kept to keep the node type semantics.
 */
type():BasicShapeNodeType {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : BasicShapeNodeType.Rectangle;
}

shapeType():CanonicalLayerShape {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : CanonicalLayerShape.NONE;
}

shape<T extends flatbuffers.Table>(obj:any):any|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__union(obj, this.bb_pos + offset) : null;
}

cornerRadius():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

cornerSmoothing():number {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

fillPaints(index: number, obj?:PaintStackItem):PaintStackItem|null {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? (obj || new PaintStackItem()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

fillPaintsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

strokeStyle(obj?:StrokeStyle):StrokeStyle|null {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? (obj || new StrokeStyle()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

strokeWidth():number {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

strokeWidthProfile(obj?:VariableWidthProfile):VariableWidthProfile|null {
  const offset = this.bb!.__offset(this.bb_pos, 24);
  return offset ? (obj || new VariableWidthProfile()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

rectangularCornerRadius(obj?:RectangularCornerRadius):RectangularCornerRadius|null {
  const offset = this.bb!.__offset(this.bb_pos, 26);
  return offset ? (obj || new RectangularCornerRadius()).__init(this.bb_pos + offset, this.bb!) : null;
}

rectangularStrokeWidth(obj?:RectangularStrokeWidth):RectangularStrokeWidth|null {
  const offset = this.bb!.__offset(this.bb_pos, 28);
  return offset ? (obj || new RectangularStrokeWidth()).__init(this.bb_pos + offset, this.bb!) : null;
}

strokePaints(index: number, obj?:PaintStackItem):PaintStackItem|null {
  const offset = this.bb!.__offset(this.bb_pos, 30);
  return offset ? (obj || new PaintStackItem()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

strokePaintsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 30);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startBasicShapeNode(builder:flatbuffers.Builder) {
  builder.startObject(14);
}

static addNode(builder:flatbuffers.Builder, nodeOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, nodeOffset, 0);
}

static addLayer(builder:flatbuffers.Builder, layerOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, layerOffset, 0);
}

static addType(builder:flatbuffers.Builder, type:BasicShapeNodeType) {
  builder.addFieldInt8(2, type, BasicShapeNodeType.Rectangle);
}

static addShapeType(builder:flatbuffers.Builder, shapeType:CanonicalLayerShape) {
  builder.addFieldInt8(3, shapeType, CanonicalLayerShape.NONE);
}

static addShape(builder:flatbuffers.Builder, shapeOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, shapeOffset, 0);
}

static addCornerRadius(builder:flatbuffers.Builder, cornerRadius:number) {
  builder.addFieldFloat32(5, cornerRadius, 0.0);
}

static addCornerSmoothing(builder:flatbuffers.Builder, cornerSmoothing:number) {
  builder.addFieldFloat32(6, cornerSmoothing, 0.0);
}

static addFillPaints(builder:flatbuffers.Builder, fillPaintsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(7, fillPaintsOffset, 0);
}

static createFillPaintsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startFillPaintsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addStrokeStyle(builder:flatbuffers.Builder, strokeStyleOffset:flatbuffers.Offset) {
  builder.addFieldOffset(8, strokeStyleOffset, 0);
}

static addStrokeWidth(builder:flatbuffers.Builder, strokeWidth:number) {
  builder.addFieldFloat32(9, strokeWidth, 0.0);
}

static addStrokeWidthProfile(builder:flatbuffers.Builder, strokeWidthProfileOffset:flatbuffers.Offset) {
  builder.addFieldOffset(10, strokeWidthProfileOffset, 0);
}

static addRectangularCornerRadius(builder:flatbuffers.Builder, rectangularCornerRadiusOffset:flatbuffers.Offset) {
  builder.addFieldStruct(11, rectangularCornerRadiusOffset, 0);
}

static addRectangularStrokeWidth(builder:flatbuffers.Builder, rectangularStrokeWidthOffset:flatbuffers.Offset) {
  builder.addFieldStruct(12, rectangularStrokeWidthOffset, 0);
}

static addStrokePaints(builder:flatbuffers.Builder, strokePaintsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(13, strokePaintsOffset, 0);
}

static createStrokePaintsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startStrokePaintsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endBasicShapeNode(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // node
  builder.requiredField(offset, 6) // layer
  return offset;
}

}
