// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

/**
 * shape node type (flag within BasicShapeNode)
 */
export enum BasicShapeNodeType {
  Rectangle = 0,
  Ellipse = 1,
  Polygon = 2,
  RegularPolygon = 3,
  RegularStarPolygon = 4,
  Path = 5
}
