// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { BooleanPathOperation } from '../grida/boolean-path-operation';
import { CornerRadiusTrait } from '../grida/corner-radius-trait';
import { LayerTrait } from '../grida/layer-trait';
import { PaintStackItem } from '../grida/paint-stack-item';
import { StrokeGeometryTrait } from '../grida/stroke-geometry-trait';
import { SystemNodeTrait } from '../grida/system-node-trait';


/**
 * Node variant: Boolean operation.
 */
export class BooleanOperationNode {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):BooleanOperationNode {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsBooleanOperationNode(bb:flatbuffers.ByteBuffer, obj?:BooleanOperationNode):BooleanOperationNode {
  return (obj || new BooleanOperationNode()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsBooleanOperationNode(bb:flatbuffers.ByteBuffer, obj?:BooleanOperationNode):BooleanOperationNode {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new BooleanOperationNode()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

node(obj?:SystemNodeTrait):SystemNodeTrait|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new SystemNodeTrait()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

layer(obj?:LayerTrait):LayerTrait|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new LayerTrait()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

op():BooleanPathOperation {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : BooleanPathOperation.Union;
}

cornerRadius(obj?:CornerRadiusTrait):CornerRadiusTrait|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? (obj || new CornerRadiusTrait()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

fillPaints(index: number, obj?:PaintStackItem):PaintStackItem|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? (obj || new PaintStackItem()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

fillPaintsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

strokeGeometry(obj?:StrokeGeometryTrait):StrokeGeometryTrait|null {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? (obj || new StrokeGeometryTrait()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

strokePaints(index: number, obj?:PaintStackItem):PaintStackItem|null {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? (obj || new PaintStackItem()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

strokePaintsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startBooleanOperationNode(builder:flatbuffers.Builder) {
  builder.startObject(7);
}

static addNode(builder:flatbuffers.Builder, nodeOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, nodeOffset, 0);
}

static addLayer(builder:flatbuffers.Builder, layerOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, layerOffset, 0);
}

static addOp(builder:flatbuffers.Builder, op:BooleanPathOperation) {
  builder.addFieldInt8(2, op, BooleanPathOperation.Union);
}

static addCornerRadius(builder:flatbuffers.Builder, cornerRadiusOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, cornerRadiusOffset, 0);
}

static addFillPaints(builder:flatbuffers.Builder, fillPaintsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, fillPaintsOffset, 0);
}

static createFillPaintsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startFillPaintsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addStrokeGeometry(builder:flatbuffers.Builder, strokeGeometryOffset:flatbuffers.Offset) {
  builder.addFieldOffset(5, strokeGeometryOffset, 0);
}

static addStrokePaints(builder:flatbuffers.Builder, strokePaintsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(6, strokePaintsOffset, 0);
}

static createStrokePaintsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startStrokePaintsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endBooleanOperationNode(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // node
  builder.requiredField(offset, 6) // layer
  return offset;
}

}
