// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum BooleanPathOperation {
  Union = 0,
  Intersection = 1,
  Difference = 2,
  Xor = 3
}
