// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

/**
 * Rust: `math2::box_fit::BoxFit`
 */
export enum BoxFit {
  Contain = 0,
  Cover = 1,
  Fill = 2,
  None = 3
}
