// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { FillRule } from '../grida/fill-rule';


/**
 * path
 */
export class CanonicalShapePath {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):CanonicalShapePath {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsCanonicalShapePath(bb:flatbuffers.ByteBuffer, obj?:CanonicalShapePath):CanonicalShapePath {
  return (obj || new CanonicalShapePath()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsCanonicalShapePath(bb:flatbuffers.ByteBuffer, obj?:CanonicalShapePath):CanonicalShapePath {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new CanonicalShapePath()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

d():string|null
d(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
d(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

fillRule():FillRule {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : FillRule.NonZero;
}

static startCanonicalShapePath(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addD(builder:flatbuffers.Builder, dOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, dOffset, 0);
}

static addFillRule(builder:flatbuffers.Builder, fillRule:FillRule) {
  builder.addFieldInt8(1, fillRule, FillRule.NonZero);
}

static endCanonicalShapePath(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createCanonicalShapePath(builder:flatbuffers.Builder, dOffset:flatbuffers.Offset, fillRule:FillRule):flatbuffers.Offset {
  CanonicalShapePath.startCanonicalShapePath(builder);
  CanonicalShapePath.addD(builder, dOffset);
  CanonicalShapePath.addFillRule(builder, fillRule);
  return CanonicalShapePath.endCanonicalShapePath(builder);
}
}
