// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { CGPoint } from '../grida/cgpoint';
import { FillRule } from '../grida/fill-rule';


/**
 * polygon (any shapes defined by points)
 */
export class CanonicalShapePointsPolygon {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):CanonicalShapePointsPolygon {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsCanonicalShapePointsPolygon(bb:flatbuffers.ByteBuffer, obj?:CanonicalShapePointsPolygon):CanonicalShapePointsPolygon {
  return (obj || new CanonicalShapePointsPolygon()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsCanonicalShapePointsPolygon(bb:flatbuffers.ByteBuffer, obj?:CanonicalShapePointsPolygon):CanonicalShapePointsPolygon {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new CanonicalShapePointsPolygon()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

points(index: number, obj?:CGPoint):CGPoint|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new CGPoint()).__init(this.bb!.__vector(this.bb_pos + offset) + index * 8, this.bb!) : null;
}

pointsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

fillRule():FillRule {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : FillRule.NonZero;
}

static startCanonicalShapePointsPolygon(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addPoints(builder:flatbuffers.Builder, pointsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, pointsOffset, 0);
}

static startPointsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(8, numElems, 4);
}

static addFillRule(builder:flatbuffers.Builder, fillRule:FillRule) {
  builder.addFieldInt8(1, fillRule, FillRule.NonZero);
}

static endCanonicalShapePointsPolygon(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createCanonicalShapePointsPolygon(builder:flatbuffers.Builder, pointsOffset:flatbuffers.Offset, fillRule:FillRule):flatbuffers.Offset {
  CanonicalShapePointsPolygon.startCanonicalShapePointsPolygon(builder);
  CanonicalShapePointsPolygon.addPoints(builder, pointsOffset);
  CanonicalShapePointsPolygon.addFillRule(builder, fillRule);
  return CanonicalShapePointsPolygon.endCanonicalShapePointsPolygon(builder);
}
}
