// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

/**
 * regular polygon
 */
export class CanonicalShapeRegularPolygon {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):CanonicalShapeRegularPolygon {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsCanonicalShapeRegularPolygon(bb:flatbuffers.ByteBuffer, obj?:CanonicalShapeRegularPolygon):CanonicalShapeRegularPolygon {
  return (obj || new CanonicalShapeRegularPolygon()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsCanonicalShapeRegularPolygon(bb:flatbuffers.ByteBuffer, obj?:CanonicalShapeRegularPolygon):CanonicalShapeRegularPolygon {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new CanonicalShapeRegularPolygon()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

pointCount():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

static startCanonicalShapeRegularPolygon(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addPointCount(builder:flatbuffers.Builder, pointCount:number) {
  builder.addFieldInt32(0, pointCount, 0);
}

static endCanonicalShapeRegularPolygon(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createCanonicalShapeRegularPolygon(builder:flatbuffers.Builder, pointCount:number):flatbuffers.Offset {
  CanonicalShapeRegularPolygon.startCanonicalShapeRegularPolygon(builder);
  CanonicalShapeRegularPolygon.addPointCount(builder, pointCount);
  return CanonicalShapeRegularPolygon.endCanonicalShapeRegularPolygon(builder);
}
}
