// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

/**
 * rectangle, rounded rectangle
 */
export class CanonicalShapeRectangular {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):CanonicalShapeRectangular {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsCanonicalShapeRectangular(bb:flatbuffers.ByteBuffer, obj?:CanonicalShapeRectangular):CanonicalShapeRectangular {
  return (obj || new CanonicalShapeRectangular()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsCanonicalShapeRectangular(bb:flatbuffers.ByteBuffer, obj?:CanonicalShapeRectangular):CanonicalShapeRectangular {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new CanonicalShapeRectangular()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static startCanonicalShapeRectangular(builder:flatbuffers.Builder) {
  builder.startObject(0);
}

static endCanonicalShapeRectangular(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createCanonicalShapeRectangular(builder:flatbuffers.Builder):flatbuffers.Offset {
  CanonicalShapeRectangular.startCanonicalShapeRectangular(builder);
  return CanonicalShapeRectangular.endCanonicalShapeRectangular(builder);
}
}
