// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

/**
 * Rust: `EllipticalRingSectorShape` (arc/ring sector data for ellipses)
 */
export class CanonicalEllipticalShapeRingSectorParameters {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):CanonicalEllipticalShapeRingSectorParameters {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsCanonicalEllipticalShapeRingSectorParameters(bb:flatbuffers.ByteBuffer, obj?:CanonicalEllipticalShapeRingSectorParameters):CanonicalEllipticalShapeRingSectorParameters {
  return (obj || new CanonicalEllipticalShapeRingSectorParameters()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsCanonicalEllipticalShapeRingSectorParameters(bb:flatbuffers.ByteBuffer, obj?:CanonicalEllipticalShapeRingSectorParameters):CanonicalEllipticalShapeRingSectorParameters {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new CanonicalEllipticalShapeRingSectorParameters()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

/**
 * Inner radius ratio (0..1)
 */
innerRadiusRatio():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

/**
 * Start angle in degrees
 */
startAngle():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

/**
 * Sweep angle in degrees (end_angle = start_angle + angle)
 */
angle():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 360.0;
}

static startCanonicalEllipticalShapeRingSectorParameters(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addInnerRadiusRatio(builder:flatbuffers.Builder, innerRadiusRatio:number) {
  builder.addFieldFloat32(0, innerRadiusRatio, 0.0);
}

static addStartAngle(builder:flatbuffers.Builder, startAngle:number) {
  builder.addFieldFloat32(1, startAngle, 0.0);
}

static addAngle(builder:flatbuffers.Builder, angle:number) {
  builder.addFieldFloat32(2, angle, 360.0);
}

static endCanonicalEllipticalShapeRingSectorParameters(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createCanonicalEllipticalShapeRingSectorParameters(builder:flatbuffers.Builder, innerRadiusRatio:number, startAngle:number, angle:number):flatbuffers.Offset {
  CanonicalEllipticalShapeRingSectorParameters.startCanonicalEllipticalShapeRingSectorParameters(builder);
  CanonicalEllipticalShapeRingSectorParameters.addInnerRadiusRatio(builder, innerRadiusRatio);
  CanonicalEllipticalShapeRingSectorParameters.addStartAngle(builder, startAngle);
  CanonicalEllipticalShapeRingSectorParameters.addAngle(builder, angle);
  return CanonicalEllipticalShapeRingSectorParameters.endCanonicalEllipticalShapeRingSectorParameters(builder);
}
}
