// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import { CanonicalShapeElliptical } from '../grida/canonical-shape-elliptical';
import { CanonicalShapePath } from '../grida/canonical-shape-path';
import { CanonicalShapePointsPolygon } from '../grida/canonical-shape-points-polygon';
import { CanonicalShapeRectangular } from '../grida/canonical-shape-rectangular';
import { CanonicalShapeRegularPolygon } from '../grida/canonical-shape-regular-polygon';
import { CanonicalShapeRegularStarPolygon } from '../grida/canonical-shape-regular-star-polygon';


/**
 * Canonical layer shape descriptor (geometry-only, layout-resolved).
 *
 * `CanonicalLayerShape` is a *minimal*, *layout-independent* description of a
 * primitive shape used by layer-backed nodes (e.g. `BasicShapeNode`).
 *
 * Core semantics:
 * - This union intentionally does NOT encode size (no width/height).
 * - The concrete geometry is produced by mapping the selected shape variant into
 *   the node’s resolved layout box at render time.
 * - Shape-specific parameters are expressed in normalized or ratio form:
 *     * points/polygon/path use 0..1 normalized coordinates (scaled to the box)
 *     * ellipse ring/sector uses ratios + angles (interpreted in the box)
 * - All styling (fills, strokes, effects, corner traits, etc.) lives outside the
 *   shape descriptor on the owning node/traits. This union is geometry-only.
 *
 * Evolution rules:
 * - New primitive shape variants may be added by introducing a new `CanonicalShape*`
 *   table and adding it to this union (additive change).
 * - Consumers must tolerate unknown union members (e.g. skip, treat as `UnknownNode`,
 *   or fall back to a rectangle) rather than hard-failing, to preserve forward
 *   compatibility.
 *
 * Notes:
 * - The “Canonical” prefix indicates the representation is the stable, box-mapped
 *   geometry form used in the archive, not a fully resolved mesh/path at a fixed size.
 * - Even when a variant currently has no fields (e.g. rectangular), it is kept as a
 *   distinct member to preserve explicit author intent and allow future extensions
 *   without changing other variants.
 */
export enum CanonicalLayerShape {
  NONE = 0,
  CanonicalShapeRectangular = 1,
  CanonicalShapeElliptical = 2,
  CanonicalShapePointsPolygon = 3,
  CanonicalShapeRegularPolygon = 4,
  CanonicalShapeRegularStarPolygon = 5,
  CanonicalShapePath = 6
}

export function unionToCanonicalLayerShape(
  type: CanonicalLayerShape,
  accessor: (obj:CanonicalShapeElliptical|CanonicalShapePath|CanonicalShapePointsPolygon|CanonicalShapeRectangular|CanonicalShapeRegularPolygon|CanonicalShapeRegularStarPolygon) => CanonicalShapeElliptical|CanonicalShapePath|CanonicalShapePointsPolygon|CanonicalShapeRectangular|CanonicalShapeRegularPolygon|CanonicalShapeRegularStarPolygon|null
): CanonicalShapeElliptical|CanonicalShapePath|CanonicalShapePointsPolygon|CanonicalShapeRectangular|CanonicalShapeRegularPolygon|CanonicalShapeRegularStarPolygon|null {
  switch(CanonicalLayerShape[type]) {
    case 'NONE': return null; 
    case 'CanonicalShapeRectangular': return accessor(new CanonicalShapeRectangular())! as CanonicalShapeRectangular;
    case 'CanonicalShapeElliptical': return accessor(new CanonicalShapeElliptical())! as CanonicalShapeElliptical;
    case 'CanonicalShapePointsPolygon': return accessor(new CanonicalShapePointsPolygon())! as CanonicalShapePointsPolygon;
    case 'CanonicalShapeRegularPolygon': return accessor(new CanonicalShapeRegularPolygon())! as CanonicalShapeRegularPolygon;
    case 'CanonicalShapeRegularStarPolygon': return accessor(new CanonicalShapeRegularStarPolygon())! as CanonicalShapeRegularStarPolygon;
    case 'CanonicalShapePath': return accessor(new CanonicalShapePath())! as CanonicalShapePath;
    default: return null;
  }
}

export function unionListToCanonicalLayerShape(
  type: CanonicalLayerShape, 
  accessor: (index: number, obj:CanonicalShapeElliptical|CanonicalShapePath|CanonicalShapePointsPolygon|CanonicalShapeRectangular|CanonicalShapeRegularPolygon|CanonicalShapeRegularStarPolygon) => CanonicalShapeElliptical|CanonicalShapePath|CanonicalShapePointsPolygon|CanonicalShapeRectangular|CanonicalShapeRegularPolygon|CanonicalShapeRegularStarPolygon|null, 
  index: number
): CanonicalShapeElliptical|CanonicalShapePath|CanonicalShapePointsPolygon|CanonicalShapeRectangular|CanonicalShapeRegularPolygon|CanonicalShapeRegularStarPolygon|null {
  switch(CanonicalLayerShape[type]) {
    case 'NONE': return null; 
    case 'CanonicalShapeRectangular': return accessor(index, new CanonicalShapeRectangular())! as CanonicalShapeRectangular;
    case 'CanonicalShapeElliptical': return accessor(index, new CanonicalShapeElliptical())! as CanonicalShapeElliptical;
    case 'CanonicalShapePointsPolygon': return accessor(index, new CanonicalShapePointsPolygon())! as CanonicalShapePointsPolygon;
    case 'CanonicalShapeRegularPolygon': return accessor(index, new CanonicalShapeRegularPolygon())! as CanonicalShapeRegularPolygon;
    case 'CanonicalShapeRegularStarPolygon': return accessor(index, new CanonicalShapeRegularStarPolygon())! as CanonicalShapeRegularStarPolygon;
    case 'CanonicalShapePath': return accessor(index, new CanonicalShapePath())! as CanonicalShapePath;
    default: return null;
  }
}
