// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

/**
 * regular star-ish polygon
 */
export class CanonicalShapeRegularStarPolygon {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):CanonicalShapeRegularStarPolygon {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsCanonicalShapeRegularStarPolygon(bb:flatbuffers.ByteBuffer, obj?:CanonicalShapeRegularStarPolygon):CanonicalShapeRegularStarPolygon {
  return (obj || new CanonicalShapeRegularStarPolygon()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsCanonicalShapeRegularStarPolygon(bb:flatbuffers.ByteBuffer, obj?:CanonicalShapeRegularStarPolygon):CanonicalShapeRegularStarPolygon {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new CanonicalShapeRegularStarPolygon()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

pointCount():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

innerRadiusRatio():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

static startCanonicalShapeRegularStarPolygon(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addPointCount(builder:flatbuffers.Builder, pointCount:number) {
  builder.addFieldInt32(0, pointCount, 0);
}

static addInnerRadiusRatio(builder:flatbuffers.Builder, innerRadiusRatio:number) {
  builder.addFieldFloat32(1, innerRadiusRatio, 0.0);
}

static endCanonicalShapeRegularStarPolygon(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createCanonicalShapeRegularStarPolygon(builder:flatbuffers.Builder, pointCount:number, innerRadiusRatio:number):flatbuffers.Offset {
  CanonicalShapeRegularStarPolygon.startCanonicalShapeRegularStarPolygon(builder);
  CanonicalShapeRegularStarPolygon.addPointCount(builder, pointCount);
  CanonicalShapeRegularStarPolygon.addInnerRadiusRatio(builder, innerRadiusRatio);
  return CanonicalShapeRegularStarPolygon.endCanonicalShapeRegularStarPolygon(builder);
}
}
