// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { NodeIdentifier } from '../grida/node-identifier';
import { NodeSlot } from '../grida/node-slot';


export class CanvasDocument {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):CanvasDocument {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsCanvasDocument(bb:flatbuffers.ByteBuffer, obj?:CanvasDocument):CanvasDocument {
  return (obj || new CanvasDocument()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsCanvasDocument(bb:flatbuffers.ByteBuffer, obj?:CanvasDocument):CanvasDocument {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new CanvasDocument()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

/**
 * Schema version string (keep in sync with TS `grida.program.document.SCHEMA_VERSION`).
 */
schemaVersion():string|null
schemaVersion(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
schemaVersion(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

/**
 * Flat node repository.
 *
 * Stored as `[NodeSlot]` (vector of wrapper tables) rather than `[Node]`
 * (vector of unions) to maintain compatibility with Rust FlatBuffers codegen,
 * which does not support vectors of unions directly.
 */
nodes(index: number, obj?:NodeSlot):NodeSlot|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new NodeSlot()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

nodesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

/**
 * Scene node ids (scene nodes are also stored in `nodes`).
 */
scenes(index: number, obj?:NodeIdentifier):NodeIdentifier|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new NodeIdentifier()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

scenesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startCanvasDocument(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addSchemaVersion(builder:flatbuffers.Builder, schemaVersionOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, schemaVersionOffset, 0);
}

static addNodes(builder:flatbuffers.Builder, nodesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, nodesOffset, 0);
}

static createNodesVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startNodesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addScenes(builder:flatbuffers.Builder, scenesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, scenesOffset, 0);
}

static createScenesVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startScenesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endCanvasDocument(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createCanvasDocument(builder:flatbuffers.Builder, schemaVersionOffset:flatbuffers.Offset, nodesOffset:flatbuffers.Offset, scenesOffset:flatbuffers.Offset):flatbuffers.Offset {
  CanvasDocument.startCanvasDocument(builder);
  CanvasDocument.addSchemaVersion(builder, schemaVersionOffset);
  CanvasDocument.addNodes(builder, nodesOffset);
  CanvasDocument.addScenes(builder, scenesOffset);
  return CanvasDocument.endCanvasDocument(builder);
}
}
