// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

/**
 * Rust: `Radius { rx: f32, ry: f32 }`
 */
export class CGRadius {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):CGRadius {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

rx():number {
  return this.bb!.readFloat32(this.bb_pos);
}

ry():number {
  return this.bb!.readFloat32(this.bb_pos + 4);
}

static sizeOf():number {
  return 8;
}

static createCGRadius(builder:flatbuffers.Builder, rx: number, ry: number):flatbuffers.Offset {
  builder.prep(4, 8);
  builder.writeFloat32(ry);
  builder.writeFloat32(rx);
  return builder.offset();
}

}
