// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

/**
 * Rust: `CGTransform2D { m00..m12: f32 }` (and compatible with math2 `AffineTransform`).
 *
 * Matrix layout:
 * [ m00  m01  m02 ]
 * [ m10  m11  m12 ]
 * [  0    0    1  ]
 *
 * Struct representation (no defaults in FlatBuffers structs).
 */
export class CGTransform2D {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):CGTransform2D {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

m00():number {
  return this.bb!.readFloat32(this.bb_pos);
}

m01():number {
  return this.bb!.readFloat32(this.bb_pos + 4);
}

m02():number {
  return this.bb!.readFloat32(this.bb_pos + 8);
}

m10():number {
  return this.bb!.readFloat32(this.bb_pos + 12);
}

m11():number {
  return this.bb!.readFloat32(this.bb_pos + 16);
}

m12():number {
  return this.bb!.readFloat32(this.bb_pos + 20);
}

static sizeOf():number {
  return 24;
}

static createCGTransform2D(builder:flatbuffers.Builder, m00: number, m01: number, m02: number, m10: number, m11: number, m12: number):flatbuffers.Offset {
  builder.prep(4, 24);
  builder.writeFloat32(m12);
  builder.writeFloat32(m11);
  builder.writeFloat32(m10);
  builder.writeFloat32(m02);
  builder.writeFloat32(m01);
  builder.writeFloat32(m00);
  return builder.offset();
}

}
