// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { CGRadius } from '../grida/cgradius';


export class CornerRadiusTrait {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):CornerRadiusTrait {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsCornerRadiusTrait(bb:flatbuffers.ByteBuffer, obj?:CornerRadiusTrait):CornerRadiusTrait {
  return (obj || new CornerRadiusTrait()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsCornerRadiusTrait(bb:flatbuffers.ByteBuffer, obj?:CornerRadiusTrait):CornerRadiusTrait {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new CornerRadiusTrait()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

cornerRadius(obj?:CGRadius):CGRadius|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new CGRadius()).__init(this.bb_pos + offset, this.bb!) : null;
}

cornerSmoothing():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

static startCornerRadiusTrait(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addCornerRadius(builder:flatbuffers.Builder, cornerRadiusOffset:flatbuffers.Offset) {
  builder.addFieldStruct(0, cornerRadiusOffset, 0);
}

static addCornerSmoothing(builder:flatbuffers.Builder, cornerSmoothing:number) {
  builder.addFieldFloat32(1, cornerSmoothing, 0.0);
}

static endCornerRadiusTrait(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createCornerRadiusTrait(builder:flatbuffers.Builder, cornerRadiusOffset:flatbuffers.Offset, cornerSmoothing:number):flatbuffers.Offset {
  CornerRadiusTrait.startCornerRadiusTrait(builder);
  CornerRadiusTrait.addCornerRadius(builder, cornerRadiusOffset);
  CornerRadiusTrait.addCornerSmoothing(builder, cornerSmoothing);
  return CornerRadiusTrait.endCornerRadiusTrait(builder);
}
}
