// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum CrossAxisAlignment {
  None = 0,
  Start = 1,
  End = 2,
  Center = 3,
  Stretch = 4
}
