// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { BlendMode } from '../grida/blend-mode';
import { CGTransform2D } from '../grida/cgtransform2-d';
import { GradientStop } from '../grida/gradient-stop';


export class DiamondGradientPaint {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):DiamondGradientPaint {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsDiamondGradientPaint(bb:flatbuffers.ByteBuffer, obj?:DiamondGradientPaint):DiamondGradientPaint {
  return (obj || new DiamondGradientPaint()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsDiamondGradientPaint(bb:flatbuffers.ByteBuffer, obj?:DiamondGradientPaint):DiamondGradientPaint {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new DiamondGradientPaint()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

active():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : true;
}

/**
 * transform of the gradient, if empty(unset) canonical is identity
 */
transform(obj?:CGTransform2D):CGTransform2D|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new CGTransform2D()).__init(this.bb_pos + offset, this.bb!) : null;
}

stops(index: number, obj?:GradientStop):GradientStop|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new GradientStop()).__init(this.bb!.__vector(this.bb_pos + offset) + index * 20, this.bb!) : null;
}

stopsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

opacity():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 1.0;
}

blendMode():BlendMode {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : BlendMode.Normal;
}

static startDiamondGradientPaint(builder:flatbuffers.Builder) {
  builder.startObject(5);
}

static addActive(builder:flatbuffers.Builder, active:boolean) {
  builder.addFieldInt8(0, +active, +true);
}

static addTransform(builder:flatbuffers.Builder, transformOffset:flatbuffers.Offset) {
  builder.addFieldStruct(1, transformOffset, 0);
}

static addStops(builder:flatbuffers.Builder, stopsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, stopsOffset, 0);
}

static startStopsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(20, numElems, 4);
}

static addOpacity(builder:flatbuffers.Builder, opacity:number) {
  builder.addFieldFloat32(3, opacity, 1.0);
}

static addBlendMode(builder:flatbuffers.Builder, blendMode:BlendMode) {
  builder.addFieldInt8(4, blendMode, BlendMode.Normal);
}

static endDiamondGradientPaint(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
