// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class EdgePointPosition2D {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):EdgePointPosition2D {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsEdgePointPosition2D(bb:flatbuffers.ByteBuffer, obj?:EdgePointPosition2D):EdgePointPosition2D {
  return (obj || new EdgePointPosition2D()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsEdgePointPosition2D(bb:flatbuffers.ByteBuffer, obj?:EdgePointPosition2D):EdgePointPosition2D {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new EdgePointPosition2D()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

x():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

y():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

static startEdgePointPosition2D(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addX(builder:flatbuffers.Builder, x:number) {
  builder.addFieldFloat32(0, x, 0.0);
}

static addY(builder:flatbuffers.Builder, y:number) {
  builder.addFieldFloat32(1, y, 0.0);
}

static endEdgePointPosition2D(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createEdgePointPosition2D(builder:flatbuffers.Builder, x:number, y:number):flatbuffers.Offset {
  EdgePointPosition2D.startEdgePointPosition2D(builder);
  EdgePointPosition2D.addX(builder, x);
  EdgePointPosition2D.addY(builder, y);
  return EdgePointPosition2D.endEdgePointPosition2D(builder);
}
}
