// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { EdgePoint, unionToEdgePoint, unionListToEdgePoint } from '../grida/edge-point';


export class Edge2D {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Edge2D {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsEdge2D(bb:flatbuffers.ByteBuffer, obj?:Edge2D):Edge2D {
  return (obj || new Edge2D()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsEdge2D(bb:flatbuffers.ByteBuffer, obj?:Edge2D):Edge2D {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Edge2D()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

id():string|null
id(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
id(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

aType():EdgePoint {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : EdgePoint.NONE;
}

a<T extends flatbuffers.Table>(obj:any):any|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__union(obj, this.bb_pos + offset) : null;
}

bType():EdgePoint {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : EdgePoint.NONE;
}

b<T extends flatbuffers.Table>(obj:any):any|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__union(obj, this.bb_pos + offset) : null;
}

static startEdge2D(builder:flatbuffers.Builder) {
  builder.startObject(5);
}

static addId(builder:flatbuffers.Builder, idOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, idOffset, 0);
}

static addAType(builder:flatbuffers.Builder, aType:EdgePoint) {
  builder.addFieldInt8(1, aType, EdgePoint.NONE);
}

static addA(builder:flatbuffers.Builder, aOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, aOffset, 0);
}

static addBType(builder:flatbuffers.Builder, bType:EdgePoint) {
  builder.addFieldInt8(3, bType, EdgePoint.NONE);
}

static addB(builder:flatbuffers.Builder, bOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, bOffset, 0);
}

static endEdge2D(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createEdge2D(builder:flatbuffers.Builder, idOffset:flatbuffers.Offset, aType:EdgePoint, aOffset:flatbuffers.Offset, bType:EdgePoint, bOffset:flatbuffers.Offset):flatbuffers.Offset {
  Edge2D.startEdge2D(builder);
  Edge2D.addId(builder, idOffset);
  Edge2D.addAType(builder, aType);
  Edge2D.addA(builder, aOffset);
  Edge2D.addBType(builder, bType);
  Edge2D.addB(builder, bOffset);
  return Edge2D.endEdge2D(builder);
}
}
