// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import { EdgePointNodeAnchor } from '../grida/edge-point-node-anchor';
import { EdgePointPosition2D } from '../grida/edge-point-position2-d';


export enum EdgePoint {
  NONE = 0,
  EdgePointPosition2D = 1,
  EdgePointNodeAnchor = 2
}

export function unionToEdgePoint(
  type: EdgePoint,
  accessor: (obj:EdgePointNodeAnchor|EdgePointPosition2D) => EdgePointNodeAnchor|EdgePointPosition2D|null
): EdgePointNodeAnchor|EdgePointPosition2D|null {
  switch(EdgePoint[type]) {
    case 'NONE': return null; 
    case 'EdgePointPosition2D': return accessor(new EdgePointPosition2D())! as EdgePointPosition2D;
    case 'EdgePointNodeAnchor': return accessor(new EdgePointNodeAnchor())! as EdgePointNodeAnchor;
    default: return null;
  }
}

export function unionListToEdgePoint(
  type: EdgePoint, 
  accessor: (index: number, obj:EdgePointNodeAnchor|EdgePointPosition2D) => EdgePointNodeAnchor|EdgePointPosition2D|null, 
  index: number
): EdgePointNodeAnchor|EdgePointPosition2D|null {
  switch(EdgePoint[type]) {
    case 'NONE': return null; 
    case 'EdgePointPosition2D': return accessor(index, new EdgePointPosition2D())! as EdgePointPosition2D;
    case 'EdgePointNodeAnchor': return accessor(index, new EdgePointNodeAnchor())! as EdgePointNodeAnchor;
    default: return null;
  }
}
