// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import { FeGaussianBlur } from '../grida/fe-gaussian-blur';
import { FeProgressiveBlur } from '../grida/fe-progressive-blur';


/**
 * Rust: `FeBlur` (enum)
 */
export enum FeBlur {
  NONE = 0,
  FeGaussianBlur = 1,
  FeProgressiveBlur = 2
}

export function unionToFeBlur(
  type: FeBlur,
  accessor: (obj:FeGaussianBlur|FeProgressiveBlur) => FeGaussianBlur|FeProgressiveBlur|null
): FeGaussianBlur|FeProgressiveBlur|null {
  switch(FeBlur[type]) {
    case 'NONE': return null; 
    case 'FeGaussianBlur': return accessor(new FeGaussianBlur())! as FeGaussianBlur;
    case 'FeProgressiveBlur': return accessor(new FeProgressiveBlur())! as FeProgressiveBlur;
    default: return null;
  }
}

export function unionListToFeBlur(
  type: FeBlur, 
  accessor: (index: number, obj:FeGaussianBlur|FeProgressiveBlur) => FeGaussianBlur|FeProgressiveBlur|null, 
  index: number
): FeGaussianBlur|FeProgressiveBlur|null {
  switch(FeBlur[type]) {
    case 'NONE': return null; 
    case 'FeGaussianBlur': return accessor(index, new FeGaussianBlur())! as FeGaussianBlur;
    case 'FeProgressiveBlur': return accessor(index, new FeProgressiveBlur())! as FeProgressiveBlur;
    default: return null;
  }
}
