// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

/**
 * Rust: `FeGaussianBlur { radius: f32 }`
 */
export class FeGaussianBlur {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):FeGaussianBlur {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsFeGaussianBlur(bb:flatbuffers.ByteBuffer, obj?:FeGaussianBlur):FeGaussianBlur {
  return (obj || new FeGaussianBlur()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsFeGaussianBlur(bb:flatbuffers.ByteBuffer, obj?:FeGaussianBlur):FeGaussianBlur {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new FeGaussianBlur()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

radius():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

static startFeGaussianBlur(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addRadius(builder:flatbuffers.Builder, radius:number) {
  builder.addFieldFloat32(0, radius, 0.0);
}

static endFeGaussianBlur(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createFeGaussianBlur(builder:flatbuffers.Builder, radius:number):flatbuffers.Offset {
  FeGaussianBlur.startFeGaussianBlur(builder);
  FeGaussianBlur.addRadius(builder, radius);
  return FeGaussianBlur.endFeGaussianBlur(builder);
}
}
