// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

/**
 * Rust: `FeLiquidGlass`
 */
export class FeLiquidGlass {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):FeLiquidGlass {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsFeLiquidGlass(bb:flatbuffers.ByteBuffer, obj?:FeLiquidGlass):FeLiquidGlass {
  return (obj || new FeLiquidGlass()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsFeLiquidGlass(bb:flatbuffers.ByteBuffer, obj?:FeLiquidGlass):FeLiquidGlass {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new FeLiquidGlass()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

active():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : true;
}

lightIntensity():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

lightAngle():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

refraction():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

depth():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

dispersion():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

blurRadius():number {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

static startFeLiquidGlass(builder:flatbuffers.Builder) {
  builder.startObject(7);
}

static addActive(builder:flatbuffers.Builder, active:boolean) {
  builder.addFieldInt8(0, +active, +true);
}

static addLightIntensity(builder:flatbuffers.Builder, lightIntensity:number) {
  builder.addFieldFloat32(1, lightIntensity, 0.0);
}

static addLightAngle(builder:flatbuffers.Builder, lightAngle:number) {
  builder.addFieldFloat32(2, lightAngle, 0.0);
}

static addRefraction(builder:flatbuffers.Builder, refraction:number) {
  builder.addFieldFloat32(3, refraction, 0.0);
}

static addDepth(builder:flatbuffers.Builder, depth:number) {
  builder.addFieldFloat32(4, depth, 0.0);
}

static addDispersion(builder:flatbuffers.Builder, dispersion:number) {
  builder.addFieldFloat32(5, dispersion, 0.0);
}

static addBlurRadius(builder:flatbuffers.Builder, blurRadius:number) {
  builder.addFieldFloat32(6, blurRadius, 0.0);
}

static endFeLiquidGlass(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createFeLiquidGlass(builder:flatbuffers.Builder, active:boolean, lightIntensity:number, lightAngle:number, refraction:number, depth:number, dispersion:number, blurRadius:number):flatbuffers.Offset {
  FeLiquidGlass.startFeLiquidGlass(builder);
  FeLiquidGlass.addActive(builder, active);
  FeLiquidGlass.addLightIntensity(builder, lightIntensity);
  FeLiquidGlass.addLightAngle(builder, lightAngle);
  FeLiquidGlass.addRefraction(builder, refraction);
  FeLiquidGlass.addDepth(builder, depth);
  FeLiquidGlass.addDispersion(builder, dispersion);
  FeLiquidGlass.addBlurRadius(builder, blurRadius);
  return FeLiquidGlass.endFeLiquidGlass(builder);
}
}
