// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { FeBlur, unionToFeBlur, unionListToFeBlur } from '../grida/fe-blur';


/**
 * Rust: `FeLayerBlur { blur: FeBlur, active: bool }`
 */
export class FeLayerBlur {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):FeLayerBlur {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsFeLayerBlur(bb:flatbuffers.ByteBuffer, obj?:FeLayerBlur):FeLayerBlur {
  return (obj || new FeLayerBlur()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsFeLayerBlur(bb:flatbuffers.ByteBuffer, obj?:FeLayerBlur):FeLayerBlur {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new FeLayerBlur()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

active():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : true;
}

blurType():FeBlur {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : FeBlur.NONE;
}

blur<T extends flatbuffers.Table>(obj:any):any|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__union(obj, this.bb_pos + offset) : null;
}

static startFeLayerBlur(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addActive(builder:flatbuffers.Builder, active:boolean) {
  builder.addFieldInt8(0, +active, +true);
}

static addBlurType(builder:flatbuffers.Builder, blurType:FeBlur) {
  builder.addFieldInt8(1, blurType, FeBlur.NONE);
}

static addBlur(builder:flatbuffers.Builder, blurOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, blurOffset, 0);
}

static endFeLayerBlur(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createFeLayerBlur(builder:flatbuffers.Builder, active:boolean, blurType:FeBlur, blurOffset:flatbuffers.Offset):flatbuffers.Offset {
  FeLayerBlur.startFeLayerBlur(builder);
  FeLayerBlur.addActive(builder, active);
  FeLayerBlur.addBlurType(builder, blurType);
  FeLayerBlur.addBlur(builder, blurOffset);
  return FeLayerBlur.endFeLayerBlur(builder);
}
}
