// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { BlendMode } from '../grida/blend-mode';
import { NoiseEffectColors } from '../grida/noise-effect-colors';


/**
 * Rust: `FeNoiseEffect`
 */
export class FeNoiseEffect {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):FeNoiseEffect {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsFeNoiseEffect(bb:flatbuffers.ByteBuffer, obj?:FeNoiseEffect):FeNoiseEffect {
  return (obj || new FeNoiseEffect()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsFeNoiseEffect(bb:flatbuffers.ByteBuffer, obj?:FeNoiseEffect):FeNoiseEffect {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new FeNoiseEffect()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

active():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : true;
}

noiseSize():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

density():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

numOctaves():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

seed():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

coloring(obj?:NoiseEffectColors):NoiseEffectColors|null {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? (obj || new NoiseEffectColors()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

blendMode():BlendMode {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : BlendMode.Normal;
}

static startFeNoiseEffect(builder:flatbuffers.Builder) {
  builder.startObject(7);
}

static addActive(builder:flatbuffers.Builder, active:boolean) {
  builder.addFieldInt8(0, +active, +true);
}

static addNoiseSize(builder:flatbuffers.Builder, noiseSize:number) {
  builder.addFieldFloat32(1, noiseSize, 0.0);
}

static addDensity(builder:flatbuffers.Builder, density:number) {
  builder.addFieldFloat32(2, density, 0.0);
}

static addNumOctaves(builder:flatbuffers.Builder, numOctaves:number) {
  builder.addFieldInt32(3, numOctaves, 0);
}

static addSeed(builder:flatbuffers.Builder, seed:number) {
  builder.addFieldFloat32(4, seed, 0.0);
}

static addColoring(builder:flatbuffers.Builder, coloringOffset:flatbuffers.Offset) {
  builder.addFieldOffset(5, coloringOffset, 0);
}

static addBlendMode(builder:flatbuffers.Builder, blendMode:BlendMode) {
  builder.addFieldInt8(6, blendMode, BlendMode.Normal);
}

static endFeNoiseEffect(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
