// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Alignment } from '../grida/alignment';


/**
 * Rust: `FeProgressiveBlur { start: Alignment, end: Alignment, radius, radius2 }`
 */
export class FeProgressiveBlur {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):FeProgressiveBlur {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsFeProgressiveBlur(bb:flatbuffers.ByteBuffer, obj?:FeProgressiveBlur):FeProgressiveBlur {
  return (obj || new FeProgressiveBlur()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsFeProgressiveBlur(bb:flatbuffers.ByteBuffer, obj?:FeProgressiveBlur):FeProgressiveBlur {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new FeProgressiveBlur()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

start(obj?:Alignment):Alignment|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new Alignment()).__init(this.bb_pos + offset, this.bb!) : null;
}

end(obj?:Alignment):Alignment|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new Alignment()).__init(this.bb_pos + offset, this.bb!) : null;
}

radius():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

radius2():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

static startFeProgressiveBlur(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addStart(builder:flatbuffers.Builder, startOffset:flatbuffers.Offset) {
  builder.addFieldStruct(0, startOffset, 0);
}

static addEnd(builder:flatbuffers.Builder, endOffset:flatbuffers.Offset) {
  builder.addFieldStruct(1, endOffset, 0);
}

static addRadius(builder:flatbuffers.Builder, radius:number) {
  builder.addFieldFloat32(2, radius, 0.0);
}

static addRadius2(builder:flatbuffers.Builder, radius2:number) {
  builder.addFieldFloat32(3, radius2, 0.0);
}

static endFeProgressiveBlur(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
