// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { RGBA32F } from '../grida/rgba32-f';


/**
 * Rust: `FeShadow { dx, dy, blur, spread, color, active }`
 */
export class FeShadow {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):FeShadow {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsFeShadow(bb:flatbuffers.ByteBuffer, obj?:FeShadow):FeShadow {
  return (obj || new FeShadow()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsFeShadow(bb:flatbuffers.ByteBuffer, obj?:FeShadow):FeShadow {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new FeShadow()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

active():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : true;
}

dx():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

dy():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

blur():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

spread():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

color(obj?:RGBA32F):RGBA32F|null {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? (obj || new RGBA32F()).__init(this.bb_pos + offset, this.bb!) : null;
}

static startFeShadow(builder:flatbuffers.Builder) {
  builder.startObject(6);
}

static addActive(builder:flatbuffers.Builder, active:boolean) {
  builder.addFieldInt8(0, +active, +true);
}

static addDx(builder:flatbuffers.Builder, dx:number) {
  builder.addFieldFloat32(1, dx, 0.0);
}

static addDy(builder:flatbuffers.Builder, dy:number) {
  builder.addFieldFloat32(2, dy, 0.0);
}

static addBlur(builder:flatbuffers.Builder, blur:number) {
  builder.addFieldFloat32(3, blur, 0.0);
}

static addSpread(builder:flatbuffers.Builder, spread:number) {
  builder.addFieldFloat32(4, spread, 0.0);
}

static addColor(builder:flatbuffers.Builder, colorOffset:flatbuffers.Offset) {
  builder.addFieldStruct(5, colorOffset, 0);
}

static endFeShadow(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
