// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

/**
 * Rust: `FilterShadowEffect` (enum)
 */
export enum FilterShadowEffectKind {
  DropShadow = 0,
  InnerShadow = 1
}
