// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { FeShadow } from '../grida/fe-shadow';
import { FilterShadowEffectKind } from '../grida/filter-shadow-effect-kind';


/**
 * Struct-tagged representation of Rust `FilterShadowEffect`.
 */
export class FilterShadowEffect {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):FilterShadowEffect {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsFilterShadowEffect(bb:flatbuffers.ByteBuffer, obj?:FilterShadowEffect):FilterShadowEffect {
  return (obj || new FilterShadowEffect()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsFilterShadowEffect(bb:flatbuffers.ByteBuffer, obj?:FilterShadowEffect):FilterShadowEffect {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new FilterShadowEffect()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

kind():FilterShadowEffectKind {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : FilterShadowEffectKind.DropShadow;
}

shadow(obj?:FeShadow):FeShadow|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new FeShadow()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startFilterShadowEffect(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addKind(builder:flatbuffers.Builder, kind:FilterShadowEffectKind) {
  builder.addFieldInt8(0, kind, FilterShadowEffectKind.DropShadow);
}

static addShadow(builder:flatbuffers.Builder, shadowOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, shadowOffset, 0);
}

static endFilterShadowEffect(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
