// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { OpenTypeFeatureTag } from '../grida/open-type-feature-tag';


/**
 * Rust: `FontFeature { tag: String, value: bool }`
 */
export class FontFeature {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):FontFeature {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsFontFeature(bb:flatbuffers.ByteBuffer, obj?:FontFeature):FontFeature {
  return (obj || new FontFeature()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsFontFeature(bb:flatbuffers.ByteBuffer, obj?:FontFeature):FontFeature {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new FontFeature()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

/**
 * OpenType feature tag (4-byte encoding).
 * Codecs should convert between string ("kern") and OpenTypeFeatureTag struct.
 */
openTypeFeatureTag(obj?:OpenTypeFeatureTag):OpenTypeFeatureTag|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new OpenTypeFeatureTag()).__init(this.bb_pos + offset, this.bb!) : null;
}

openTypeFeatureValue():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

static startFontFeature(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addOpenTypeFeatureTag(builder:flatbuffers.Builder, openTypeFeatureTagOffset:flatbuffers.Offset) {
  builder.addFieldStruct(0, openTypeFeatureTagOffset, 0);
}

static addOpenTypeFeatureValue(builder:flatbuffers.Builder, openTypeFeatureValue:boolean) {
  builder.addFieldInt8(1, +openTypeFeatureValue, +false);
}

static endFontFeature(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createFontFeature(builder:flatbuffers.Builder, openTypeFeatureTagOffset:flatbuffers.Offset, openTypeFeatureValue:boolean):flatbuffers.Offset {
  FontFeature.startFontFeature(builder);
  FontFeature.addOpenTypeFeatureTag(builder, openTypeFeatureTagOffset);
  FontFeature.addOpenTypeFeatureValue(builder, openTypeFeatureValue);
  return FontFeature.endFontFeature(builder);
}
}
