// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { FontOpticalSizingKind } from '../grida/font-optical-sizing-kind';


export class FontOpticalSizing {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):FontOpticalSizing {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

kind():FontOpticalSizingKind {
  return this.bb!.readUint8(this.bb_pos);
}

value():number {
  return this.bb!.readFloat32(this.bb_pos + 4);
}

static sizeOf():number {
  return 8;
}

static createFontOpticalSizing(builder:flatbuffers.Builder, kind: FontOpticalSizingKind, value: number):flatbuffers.Offset {
  builder.prep(4, 8);
  builder.writeFloat32(value);
  builder.pad(3);
  builder.writeInt8(kind);
  return builder.offset();
}

}
