// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

/**
 * Rust: `FontOpticalSizing` (Auto | None | Fixed(f32))
 */
export enum FontOpticalSizingKind {
  Auto = 0,
  None = 1,
  Fixed = 2
}
