// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

/**
 * Rust: `FontVariation { axis: String, value: f32 }`
 */
export class FontVariation {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):FontVariation {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsFontVariation(bb:flatbuffers.ByteBuffer, obj?:FontVariation):FontVariation {
  return (obj || new FontVariation()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsFontVariation(bb:flatbuffers.ByteBuffer, obj?:FontVariation):FontVariation {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new FontVariation()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

variationAxis():string|null
variationAxis(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
variationAxis(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

variationValue():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

static startFontVariation(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addVariationAxis(builder:flatbuffers.Builder, variationAxisOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, variationAxisOffset, 0);
}

static addVariationValue(builder:flatbuffers.Builder, variationValue:number) {
  builder.addFieldFloat32(1, variationValue, 0.0);
}

static endFontVariation(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // variation_axis
  return offset;
}

static createFontVariation(builder:flatbuffers.Builder, variationAxisOffset:flatbuffers.Offset, variationValue:number):flatbuffers.Offset {
  FontVariation.startFontVariation(builder);
  FontVariation.addVariationAxis(builder, variationAxisOffset);
  FontVariation.addVariationValue(builder, variationValue);
  return FontVariation.endFontVariation(builder);
}
}
