// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { RGBA32F } from '../grida/rgba32-f';


export class GradientStop {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):GradientStop {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

stopOffset():number {
  return this.bb!.readFloat32(this.bb_pos);
}

stopColor(obj?:RGBA32F):RGBA32F|null {
  return (obj || new RGBA32F()).__init(this.bb_pos + 4, this.bb!);
}

static sizeOf():number {
  return 20;
}

static createGradientStop(builder:flatbuffers.Builder, stop_offset: number, stop_color_r: number, stop_color_g: number, stop_color_b: number, stop_color_a: number):flatbuffers.Offset {
  builder.prep(4, 20);
  builder.prep(4, 16);
  builder.writeFloat32(stop_color_a);
  builder.writeFloat32(stop_color_b);
  builder.writeFloat32(stop_color_g);
  builder.writeFloat32(stop_color_r);
  builder.writeFloat32(stop_offset);
  return builder.offset();
}

}
