// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { CanvasDocument } from '../grida/canvas-document';


/**
 * Top-level root for all use cases: `.grida` files, single-scene transfers
 * (SVG import, clipboard), and future IPC payloads.
 *
 * FBS has no native multi-root-type support, so we keep one root type and
 * one codec path. Introduce a new root table only when a genuinely
 * different payload shape is needed.
 */
export class GridaFile {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):GridaFile {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsGridaFile(bb:flatbuffers.ByteBuffer, obj?:GridaFile):GridaFile {
  return (obj || new GridaFile()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsGridaFile(bb:flatbuffers.ByteBuffer, obj?:GridaFile):GridaFile {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new GridaFile()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static bufferHasIdentifier(bb:flatbuffers.ByteBuffer):boolean {
  return bb.__has_identifier('GRID');
}

document(obj?:CanvasDocument):CanvasDocument|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new CanvasDocument()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startGridaFile(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addDocument(builder:flatbuffers.Builder, documentOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, documentOffset, 0);
}

static endGridaFile(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static finishGridaFileBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, 'GRID');
}

static finishSizePrefixedGridaFileBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, 'GRID', true);
}

static createGridaFile(builder:flatbuffers.Builder, documentOffset:flatbuffers.Offset):flatbuffers.Offset {
  GridaFile.startGridaFile(builder);
  GridaFile.addDocument(builder, documentOffset);
  return GridaFile.endGridaFile(builder);
}
}
