// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Axis } from '../grida/axis';


export class Guide2D {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Guide2D {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsGuide2D(bb:flatbuffers.ByteBuffer, obj?:Guide2D):Guide2D {
  return (obj || new Guide2D()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsGuide2D(bb:flatbuffers.ByteBuffer, obj?:Guide2D):Guide2D {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Guide2D()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

axis():Axis {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : Axis.Horizontal;
}

guideOffset():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

static startGuide2D(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addAxis(builder:flatbuffers.Builder, axis:Axis) {
  builder.addFieldInt8(0, axis, Axis.Horizontal);
}

static addGuideOffset(builder:flatbuffers.Builder, guideOffset:number) {
  builder.addFieldFloat32(1, guideOffset, 0.0);
}

static endGuide2D(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createGuide2D(builder:flatbuffers.Builder, axis:Axis, guideOffset:number):flatbuffers.Offset {
  Guide2D.startGuide2D(builder);
  Guide2D.addAxis(builder, axis);
  Guide2D.addGuideOffset(builder, guideOffset);
  return Guide2D.endGuide2D(builder);
}
}
