// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { ImageRepeat } from '../grida/image-repeat';


/**
 * Rust: `ImageTile`
 */
export class ImageTile {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ImageTile {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

scale():number {
  return this.bb!.readFloat32(this.bb_pos);
}

repeat():ImageRepeat {
  return this.bb!.readUint8(this.bb_pos + 4);
}

static sizeOf():number {
  return 8;
}

static createImageTile(builder:flatbuffers.Builder, scale: number, repeat: ImageRepeat):flatbuffers.Offset {
  builder.prep(4, 8);
  builder.pad(3);
  builder.writeInt8(repeat);
  builder.writeFloat32(scale);
  return builder.offset();
}

}
