// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { ImageTile } from '../grida/image-tile';


/**
 * Rust: `ImagePaintFit::Tile(ImageTile)`
 */
export class ImagePaintFitTile {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ImagePaintFitTile {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsImagePaintFitTile(bb:flatbuffers.ByteBuffer, obj?:ImagePaintFitTile):ImagePaintFitTile {
  return (obj || new ImagePaintFitTile()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsImagePaintFitTile(bb:flatbuffers.ByteBuffer, obj?:ImagePaintFitTile):ImagePaintFitTile {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ImagePaintFitTile()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

tile(obj?:ImageTile):ImageTile|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new ImageTile()).__init(this.bb_pos + offset, this.bb!) : null;
}

static startImagePaintFitTile(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addTile(builder:flatbuffers.Builder, tileOffset:flatbuffers.Offset) {
  builder.addFieldStruct(0, tileOffset, 0);
}

static endImagePaintFitTile(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createImagePaintFitTile(builder:flatbuffers.Builder, tileOffset:flatbuffers.Offset):flatbuffers.Offset {
  ImagePaintFitTile.startImagePaintFitTile(builder);
  ImagePaintFitTile.addTile(builder, tileOffset);
  return ImagePaintFitTile.endImagePaintFitTile(builder);
}
}
