// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Alignment } from '../grida/alignment';
import { BlendMode } from '../grida/blend-mode';
import { ImageFilters } from '../grida/image-filters';
import { ImagePaintFit, unionToImagePaintFit, unionListToImagePaintFit } from '../grida/image-paint-fit';
import { ResourceRef, unionToResourceRef, unionListToResourceRef } from '../grida/resource-ref';


/**
 * Rust: `ImagePaint`
 */
export class ImagePaint {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ImagePaint {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsImagePaint(bb:flatbuffers.ByteBuffer, obj?:ImagePaint):ImagePaint {
  return (obj || new ImagePaint()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsImagePaint(bb:flatbuffers.ByteBuffer, obj?:ImagePaint):ImagePaint {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ImagePaint()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

active():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : true;
}

imageType():ResourceRef {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : ResourceRef.NONE;
}

image<T extends flatbuffers.Table>(obj:any):any|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__union(obj, this.bb_pos + offset) : null;
}

quarterTurns():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 0;
}

/**
 * NOTE: Rust field name is `alignement` (typo preserved for 1:1)
 */
alignement(obj?:Alignment):Alignment|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? (obj || new Alignment()).__init(this.bb_pos + offset, this.bb!) : null;
}

fitType():ImagePaintFit {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : ImagePaintFit.NONE;
}

fit<T extends flatbuffers.Table>(obj:any):any|null {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.__union(obj, this.bb_pos + offset) : null;
}

opacity():number {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 1.0;
}

blendMode():BlendMode {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : BlendMode.Normal;
}

filters(obj?:ImageFilters):ImageFilters|null {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? (obj || new ImageFilters()).__init(this.bb_pos + offset, this.bb!) : null;
}

static startImagePaint(builder:flatbuffers.Builder) {
  builder.startObject(10);
}

static addActive(builder:flatbuffers.Builder, active:boolean) {
  builder.addFieldInt8(0, +active, +true);
}

static addImageType(builder:flatbuffers.Builder, imageType:ResourceRef) {
  builder.addFieldInt8(1, imageType, ResourceRef.NONE);
}

static addImage(builder:flatbuffers.Builder, imageOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, imageOffset, 0);
}

static addQuarterTurns(builder:flatbuffers.Builder, quarterTurns:number) {
  builder.addFieldInt8(3, quarterTurns, 0);
}

static addAlignement(builder:flatbuffers.Builder, alignementOffset:flatbuffers.Offset) {
  builder.addFieldStruct(4, alignementOffset, 0);
}

static addFitType(builder:flatbuffers.Builder, fitType:ImagePaintFit) {
  builder.addFieldInt8(5, fitType, ImagePaintFit.NONE);
}

static addFit(builder:flatbuffers.Builder, fitOffset:flatbuffers.Offset) {
  builder.addFieldOffset(6, fitOffset, 0);
}

static addOpacity(builder:flatbuffers.Builder, opacity:number) {
  builder.addFieldFloat32(7, opacity, 1.0);
}

static addBlendMode(builder:flatbuffers.Builder, blendMode:BlendMode) {
  builder.addFieldInt8(8, blendMode, BlendMode.Normal);
}

static addFilters(builder:flatbuffers.Builder, filtersOffset:flatbuffers.Offset) {
  builder.addFieldStruct(9, filtersOffset, 0);
}

static endImagePaint(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
