// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

/**
 * Rust: `ImageMaskType`
 */
export enum ImageMaskType {
  Alpha = 0,
  Luminance = 1
}
