// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { BoxFit } from '../grida/box-fit';


/**
 * Rust: `ImagePaintFit::Fit(BoxFit)`
 */
export class ImagePaintFitFit {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ImagePaintFitFit {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsImagePaintFitFit(bb:flatbuffers.ByteBuffer, obj?:ImagePaintFitFit):ImagePaintFitFit {
  return (obj || new ImagePaintFitFit()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsImagePaintFitFit(bb:flatbuffers.ByteBuffer, obj?:ImagePaintFitFit):ImagePaintFitFit {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ImagePaintFitFit()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

boxFit():BoxFit {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : BoxFit.Cover;
}

static startImagePaintFitFit(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addBoxFit(builder:flatbuffers.Builder, boxFit:BoxFit) {
  builder.addFieldInt8(0, boxFit, BoxFit.Cover);
}

static endImagePaintFitFit(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createImagePaintFitFit(builder:flatbuffers.Builder, boxFit:BoxFit):flatbuffers.Offset {
  ImagePaintFitFit.startImagePaintFitFit(builder);
  ImagePaintFitFit.addBoxFit(builder, boxFit);
  return ImagePaintFitFit.endImagePaintFitFit(builder);
}
}
