// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

/**
 * Rust: `ImageRepeat`
 */
export enum ImageRepeat {
  RepeatX = 0,
  RepeatY = 1,
  Repeat = 2
}
