// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { CGTransform2D } from '../grida/cgtransform2-d';


/**
 * Rust: `ImagePaintFit::Transform(AffineTransform)`
 */
export class ImagePaintFitTransform {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ImagePaintFitTransform {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsImagePaintFitTransform(bb:flatbuffers.ByteBuffer, obj?:ImagePaintFitTransform):ImagePaintFitTransform {
  return (obj || new ImagePaintFitTransform()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsImagePaintFitTransform(bb:flatbuffers.ByteBuffer, obj?:ImagePaintFitTransform):ImagePaintFitTransform {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ImagePaintFitTransform()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

transform(obj?:CGTransform2D):CGTransform2D|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new CGTransform2D()).__init(this.bb_pos + offset, this.bb!) : null;
}

static startImagePaintFitTransform(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addTransform(builder:flatbuffers.Builder, transformOffset:flatbuffers.Offset) {
  builder.addFieldStruct(0, transformOffset, 0);
}

static endImagePaintFitTransform(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createImagePaintFitTransform(builder:flatbuffers.Builder, transformOffset:flatbuffers.Offset):flatbuffers.Offset {
  ImagePaintFitTransform.startImagePaintFitTransform(builder);
  ImagePaintFitTransform.addTransform(builder, transformOffset);
  return ImagePaintFitTransform.endImagePaintFitTransform(builder);
}
}
