// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import { ImagePaintFitFit } from '../grida/image-paint-fit-fit';
import { ImagePaintFitTile } from '../grida/image-paint-fit-tile';
import { ImagePaintFitTransform } from '../grida/image-paint-fit-transform';


/**
 * Rust: `ImagePaintFit`
 */
export enum ImagePaintFit {
  NONE = 0,
  ImagePaintFitFit = 1,
  ImagePaintFitTransform = 2,
  ImagePaintFitTile = 3
}

export function unionToImagePaintFit(
  type: ImagePaintFit,
  accessor: (obj:ImagePaintFitFit|ImagePaintFitTile|ImagePaintFitTransform) => ImagePaintFitFit|ImagePaintFitTile|ImagePaintFitTransform|null
): ImagePaintFitFit|ImagePaintFitTile|ImagePaintFitTransform|null {
  switch(ImagePaintFit[type]) {
    case 'NONE': return null; 
    case 'ImagePaintFitFit': return accessor(new ImagePaintFitFit())! as ImagePaintFitFit;
    case 'ImagePaintFitTransform': return accessor(new ImagePaintFitTransform())! as ImagePaintFitTransform;
    case 'ImagePaintFitTile': return accessor(new ImagePaintFitTile())! as ImagePaintFitTile;
    default: return null;
  }
}

export function unionListToImagePaintFit(
  type: ImagePaintFit, 
  accessor: (index: number, obj:ImagePaintFitFit|ImagePaintFitTile|ImagePaintFitTransform) => ImagePaintFitFit|ImagePaintFitTile|ImagePaintFitTransform|null, 
  index: number
): ImagePaintFitFit|ImagePaintFitTile|ImagePaintFitTransform|null {
  switch(ImagePaintFit[type]) {
    case 'NONE': return null; 
    case 'ImagePaintFitFit': return accessor(index, new ImagePaintFitFit())! as ImagePaintFitFit;
    case 'ImagePaintFitTransform': return accessor(index, new ImagePaintFitTransform())! as ImagePaintFitTransform;
    case 'ImagePaintFitTile': return accessor(index, new ImagePaintFitTile())! as ImagePaintFitTile;
    default: return null;
  }
}
