// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { LayerTrait } from '../grida/layer-trait';
import { SystemNodeTrait } from '../grida/system-node-trait';


/**
 * Node variant: Initial container.
 */
export class InitialContainerNode {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):InitialContainerNode {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsInitialContainerNode(bb:flatbuffers.ByteBuffer, obj?:InitialContainerNode):InitialContainerNode {
  return (obj || new InitialContainerNode()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsInitialContainerNode(bb:flatbuffers.ByteBuffer, obj?:InitialContainerNode):InitialContainerNode {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new InitialContainerNode()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

node(obj?:SystemNodeTrait):SystemNodeTrait|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new SystemNodeTrait()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

layer(obj?:LayerTrait):LayerTrait|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new LayerTrait()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startInitialContainerNode(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addNode(builder:flatbuffers.Builder, nodeOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, nodeOffset, 0);
}

static addLayer(builder:flatbuffers.Builder, layerOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, layerOffset, 0);
}

static endInitialContainerNode(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // node
  builder.requiredField(offset, 6) // layer
  return offset;
}

}
