// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

/**
 * Rust: `LayerMaskType::Geometry`
 */
export class LayerMaskTypeGeometry {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):LayerMaskTypeGeometry {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsLayerMaskTypeGeometry(bb:flatbuffers.ByteBuffer, obj?:LayerMaskTypeGeometry):LayerMaskTypeGeometry {
  return (obj || new LayerMaskTypeGeometry()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsLayerMaskTypeGeometry(bb:flatbuffers.ByteBuffer, obj?:LayerMaskTypeGeometry):LayerMaskTypeGeometry {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new LayerMaskTypeGeometry()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static startLayerMaskTypeGeometry(builder:flatbuffers.Builder) {
  builder.startObject(0);
}

static endLayerMaskTypeGeometry(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createLayerMaskTypeGeometry(builder:flatbuffers.Builder):flatbuffers.Offset {
  LayerMaskTypeGeometry.startLayerMaskTypeGeometry(builder);
  return LayerMaskTypeGeometry.endLayerMaskTypeGeometry(builder);
}
}
