// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { FeBackdropBlur } from '../grida/fe-backdrop-blur';
import { FeLayerBlur } from '../grida/fe-layer-blur';
import { FeLiquidGlass } from '../grida/fe-liquid-glass';
import { FeNoiseEffect } from '../grida/fe-noise-effect';
import { FilterShadowEffect } from '../grida/filter-shadow-effect';


/**
 * Effects trait used by nodes (Rust: `LayerEffects`).
 *
 * Note: must be a table because it contains vectors (FlatBuffers structs cannot contain vectors).
 */
export class LayerEffects {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):LayerEffects {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsLayerEffects(bb:flatbuffers.ByteBuffer, obj?:LayerEffects):LayerEffects {
  return (obj || new LayerEffects()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsLayerEffects(bb:flatbuffers.ByteBuffer, obj?:LayerEffects):LayerEffects {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new LayerEffects()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

feBlur(obj?:FeLayerBlur):FeLayerBlur|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new FeLayerBlur()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

feBackdropBlur(obj?:FeBackdropBlur):FeBackdropBlur|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new FeBackdropBlur()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

feGlass(obj?:FeLiquidGlass):FeLiquidGlass|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new FeLiquidGlass()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

feShadows(index: number, obj?:FilterShadowEffect):FilterShadowEffect|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? (obj || new FilterShadowEffect()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

feShadowsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

feNoises(index: number, obj?:FeNoiseEffect):FeNoiseEffect|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? (obj || new FeNoiseEffect()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

feNoisesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startLayerEffects(builder:flatbuffers.Builder) {
  builder.startObject(5);
}

static addFeBlur(builder:flatbuffers.Builder, feBlurOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, feBlurOffset, 0);
}

static addFeBackdropBlur(builder:flatbuffers.Builder, feBackdropBlurOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, feBackdropBlurOffset, 0);
}

static addFeGlass(builder:flatbuffers.Builder, feGlassOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, feGlassOffset, 0);
}

static addFeShadows(builder:flatbuffers.Builder, feShadowsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, feShadowsOffset, 0);
}

static createFeShadowsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startFeShadowsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addFeNoises(builder:flatbuffers.Builder, feNoisesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, feNoisesOffset, 0);
}

static createFeNoisesVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startFeNoisesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endLayerEffects(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
