// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import { LayerMaskTypeGeometry } from '../grida/layer-mask-type-geometry';
import { LayerMaskTypeImage } from '../grida/layer-mask-type-image';


/**
 * Rust: `LayerMaskType`
 */
export enum LayerMaskType {
  NONE = 0,
  LayerMaskTypeImage = 1,
  LayerMaskTypeGeometry = 2
}

export function unionToLayerMaskType(
  type: LayerMaskType,
  accessor: (obj:LayerMaskTypeGeometry|LayerMaskTypeImage) => LayerMaskTypeGeometry|LayerMaskTypeImage|null
): LayerMaskTypeGeometry|LayerMaskTypeImage|null {
  switch(LayerMaskType[type]) {
    case 'NONE': return null; 
    case 'LayerMaskTypeImage': return accessor(new LayerMaskTypeImage())! as LayerMaskTypeImage;
    case 'LayerMaskTypeGeometry': return accessor(new LayerMaskTypeGeometry())! as LayerMaskTypeGeometry;
    default: return null;
  }
}

export function unionListToLayerMaskType(
  type: LayerMaskType, 
  accessor: (index: number, obj:LayerMaskTypeGeometry|LayerMaskTypeImage) => LayerMaskTypeGeometry|LayerMaskTypeImage|null, 
  index: number
): LayerMaskTypeGeometry|LayerMaskTypeImage|null {
  switch(LayerMaskType[type]) {
    case 'NONE': return null; 
    case 'LayerMaskTypeImage': return accessor(index, new LayerMaskTypeImage())! as LayerMaskTypeImage;
    case 'LayerMaskTypeGeometry': return accessor(index, new LayerMaskTypeGeometry())! as LayerMaskTypeGeometry;
    default: return null;
  }
}
