// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { ImageMaskType } from '../grida/image-mask-type';


/**
 * Rust: `LayerMaskType::Image(ImageMaskType)`
 */
export class LayerMaskTypeImage {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):LayerMaskTypeImage {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsLayerMaskTypeImage(bb:flatbuffers.ByteBuffer, obj?:LayerMaskTypeImage):LayerMaskTypeImage {
  return (obj || new LayerMaskTypeImage()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsLayerMaskTypeImage(bb:flatbuffers.ByteBuffer, obj?:LayerMaskTypeImage):LayerMaskTypeImage {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new LayerMaskTypeImage()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

imageMaskType():ImageMaskType {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : ImageMaskType.Alpha;
}

static startLayerMaskTypeImage(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addImageMaskType(builder:flatbuffers.Builder, imageMaskType:ImageMaskType) {
  builder.addFieldInt8(0, imageMaskType, ImageMaskType.Alpha);
}

static endLayerMaskTypeImage(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createLayerMaskTypeImage(builder:flatbuffers.Builder, imageMaskType:ImageMaskType):flatbuffers.Offset {
  LayerMaskTypeImage.startLayerMaskTypeImage(builder);
  LayerMaskTypeImage.addImageMaskType(builder, imageMaskType);
  return LayerMaskTypeImage.endLayerMaskTypeImage(builder);
}
}
