// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Alignment } from '../grida/alignment';
import { CGTransform2D } from '../grida/cgtransform2-d';
import { LayerBlendMode } from '../grida/layer-blend-mode';
import { LayerEffects } from '../grida/layer-effects';
import { LayerMaskType, unionToLayerMaskType, unionListToLayerMaskType } from '../grida/layer-mask-type';
import { LayoutStyle } from '../grida/layout-style';
import { ParentReference } from '../grida/parent-reference';


/**
 * Shared layer fields used by all layer-node variants.
 * Layer is what usually user think of as a node. each layer is non-virtual, a real render target.
 */
export class LayerTrait {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):LayerTrait {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsLayerTrait(bb:flatbuffers.ByteBuffer, obj?:LayerTrait):LayerTrait {
  return (obj || new LayerTrait()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsLayerTrait(bb:flatbuffers.ByteBuffer, obj?:LayerTrait):LayerTrait {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new LayerTrait()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

/**
 * Parent reference (optional; root nodes omit this).
 *
 * When present, this node is a child of the referenced parent.
 * Children are ordered by `position` (lexicographic sort).
 *
 * Reference: Aligned with Figma's `ParentIndex` pattern (fig.kiwi).
 * This replaces the previous `children:[NodeIdentifier]` array model.
 *
 * To compute children of a parent node:
 * 1. Filter all nodes where `parent.parent_id == parent.id`
 * 2. Sort by `parent.position` (lexicographic comparison)
 */
parent(obj?:ParentReference):ParentReference|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new ParentReference()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

/**
 * opacity of the layer.
 */
opacity():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 1.0;
}

/**
 * Blend mode (archive model).
 *
 * Default is `pass_through`.
 */
blendMode():LayerBlendMode {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : LayerBlendMode.PassThrough;
}

maskTypeType():LayerMaskType {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : LayerMaskType.NONE;
}

/**
 * Rust: `LayerMaskType` (union; NONE means the node is not a mask)
 */
maskType<T extends flatbuffers.Table>(obj:any):any|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__union(obj, this.bb_pos + offset) : null;
}

/**
 * layer effects.
 */
effects(obj?:LayerEffects):LayerEffects|null {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? (obj || new LayerEffects()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

/**
 * Geometry transform baseline (identity by default).
 * Layout (optional, depending on node type / usage).
 */
layout(obj?:LayoutStyle):LayoutStyle|null {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? (obj || new LayoutStyle()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

/**
 * post-layout transform, this reflects how css transform is applied after the layout is resolved. this is currently how grida handles rotation. in the future, this might change.
 */
postLayoutTransform(obj?:CGTransform2D):CGTransform2D|null {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? (obj || new CGTransform2D()).__init(this.bb_pos + offset, this.bb!) : null;
}

postLayoutTransformOrigin(obj?:Alignment):Alignment|null {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? (obj || new Alignment()).__init(this.bb_pos + offset, this.bb!) : null;
}

static startLayerTrait(builder:flatbuffers.Builder) {
  builder.startObject(9);
}

static addParent(builder:flatbuffers.Builder, parentOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, parentOffset, 0);
}

static addOpacity(builder:flatbuffers.Builder, opacity:number) {
  builder.addFieldFloat32(1, opacity, 1.0);
}

static addBlendMode(builder:flatbuffers.Builder, blendMode:LayerBlendMode) {
  builder.addFieldInt8(2, blendMode, LayerBlendMode.PassThrough);
}

static addMaskTypeType(builder:flatbuffers.Builder, maskTypeType:LayerMaskType) {
  builder.addFieldInt8(3, maskTypeType, LayerMaskType.NONE);
}

static addMaskType(builder:flatbuffers.Builder, maskTypeOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, maskTypeOffset, 0);
}

static addEffects(builder:flatbuffers.Builder, effectsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(5, effectsOffset, 0);
}

static addLayout(builder:flatbuffers.Builder, layoutOffset:flatbuffers.Offset) {
  builder.addFieldOffset(6, layoutOffset, 0);
}

static addPostLayoutTransform(builder:flatbuffers.Builder, postLayoutTransformOffset:flatbuffers.Offset) {
  builder.addFieldStruct(7, postLayoutTransformOffset, 0);
}

static addPostLayoutTransformOrigin(builder:flatbuffers.Builder, postLayoutTransformOriginOffset:flatbuffers.Offset) {
  builder.addFieldStruct(8, postLayoutTransformOriginOffset, 0);
}

static endLayerTrait(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // parent
  return offset;
}

}
