// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

/**
 * x,y static positioning model
 */
export class LayoutPositioningCartesian {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):LayoutPositioningCartesian {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsLayoutPositioningCartesian(bb:flatbuffers.ByteBuffer, obj?:LayoutPositioningCartesian):LayoutPositioningCartesian {
  return (obj || new LayoutPositioningCartesian()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsLayoutPositioningCartesian(bb:flatbuffers.ByteBuffer, obj?:LayoutPositioningCartesian):LayoutPositioningCartesian {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new LayoutPositioningCartesian()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

x():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

y():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

static startLayoutPositioningCartesian(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addX(builder:flatbuffers.Builder, x:number) {
  builder.addFieldFloat32(0, x, 0.0);
}

static addY(builder:flatbuffers.Builder, y:number) {
  builder.addFieldFloat32(1, y, 0.0);
}

static endLayoutPositioningCartesian(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createLayoutPositioningCartesian(builder:flatbuffers.Builder, x:number, y:number):flatbuffers.Offset {
  LayoutPositioningCartesian.startLayoutPositioningCartesian(builder);
  LayoutPositioningCartesian.addX(builder, x);
  LayoutPositioningCartesian.addY(builder, y);
  return LayoutPositioningCartesian.endLayoutPositioningCartesian(builder);
}
}
