// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { LayoutPositioning } from '../grida/layout-positioning';


export class LayoutChildStyle {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):LayoutChildStyle {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsLayoutChildStyle(bb:flatbuffers.ByteBuffer, obj?:LayoutChildStyle):LayoutChildStyle {
  return (obj || new LayoutChildStyle()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsLayoutChildStyle(bb:flatbuffers.ByteBuffer, obj?:LayoutChildStyle):LayoutChildStyle {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new LayoutChildStyle()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

layoutPositioning():LayoutPositioning {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : LayoutPositioning.Auto;
}

layoutGrow():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

static startLayoutChildStyle(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addLayoutPositioning(builder:flatbuffers.Builder, layoutPositioning:LayoutPositioning) {
  builder.addFieldInt8(0, layoutPositioning, LayoutPositioning.Auto);
}

static addLayoutGrow(builder:flatbuffers.Builder, layoutGrow:number) {
  builder.addFieldFloat32(1, layoutGrow, 0.0);
}

static endLayoutChildStyle(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createLayoutChildStyle(builder:flatbuffers.Builder, layoutPositioning:LayoutPositioning, layoutGrow:number):flatbuffers.Offset {
  LayoutChildStyle.startLayoutChildStyle(builder);
  LayoutChildStyle.addLayoutPositioning(builder, layoutPositioning);
  LayoutChildStyle.addLayoutGrow(builder, layoutGrow);
  return LayoutChildStyle.endLayoutChildStyle(builder);
}
}
