// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Axis } from '../grida/axis';
import { CrossAxisAlignment } from '../grida/cross-axis-alignment';
import { EdgeInsets } from '../grida/edge-insets';
import { LayoutMode } from '../grida/layout-mode';
import { LayoutWrap } from '../grida/layout-wrap';
import { MainAxisAlignment } from '../grida/main-axis-alignment';


export class LayoutContainerStyle {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):LayoutContainerStyle {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsLayoutContainerStyle(bb:flatbuffers.ByteBuffer, obj?:LayoutContainerStyle):LayoutContainerStyle {
  return (obj || new LayoutContainerStyle()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsLayoutContainerStyle(bb:flatbuffers.ByteBuffer, obj?:LayoutContainerStyle):LayoutContainerStyle {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new LayoutContainerStyle()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

layoutMode():LayoutMode {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : LayoutMode.Normal;
}

layoutDirection():Axis {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : Axis.Horizontal;
}

layoutWrap():LayoutWrap {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : LayoutWrap.None;
}

layoutMainAxisAlignment():MainAxisAlignment {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : MainAxisAlignment.None;
}

layoutCrossAxisAlignment():CrossAxisAlignment {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : CrossAxisAlignment.None;
}

layoutPadding(obj?:EdgeInsets):EdgeInsets|null {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? (obj || new EdgeInsets()).__init(this.bb_pos + offset, this.bb!) : null;
}

layoutMainAxisGap():number {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

layoutCrossAxisGap():number {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

static startLayoutContainerStyle(builder:flatbuffers.Builder) {
  builder.startObject(8);
}

static addLayoutMode(builder:flatbuffers.Builder, layoutMode:LayoutMode) {
  builder.addFieldInt8(0, layoutMode, LayoutMode.Normal);
}

static addLayoutDirection(builder:flatbuffers.Builder, layoutDirection:Axis) {
  builder.addFieldInt8(1, layoutDirection, Axis.Horizontal);
}

static addLayoutWrap(builder:flatbuffers.Builder, layoutWrap:LayoutWrap) {
  builder.addFieldInt8(2, layoutWrap, LayoutWrap.None);
}

static addLayoutMainAxisAlignment(builder:flatbuffers.Builder, layoutMainAxisAlignment:MainAxisAlignment) {
  builder.addFieldInt8(3, layoutMainAxisAlignment, MainAxisAlignment.None);
}

static addLayoutCrossAxisAlignment(builder:flatbuffers.Builder, layoutCrossAxisAlignment:CrossAxisAlignment) {
  builder.addFieldInt8(4, layoutCrossAxisAlignment, CrossAxisAlignment.None);
}

static addLayoutPadding(builder:flatbuffers.Builder, layoutPaddingOffset:flatbuffers.Offset) {
  builder.addFieldStruct(5, layoutPaddingOffset, 0);
}

static addLayoutMainAxisGap(builder:flatbuffers.Builder, layoutMainAxisGap:number) {
  builder.addFieldFloat32(6, layoutMainAxisGap, 0.0);
}

static addLayoutCrossAxisGap(builder:flatbuffers.Builder, layoutCrossAxisGap:number) {
  builder.addFieldFloat32(7, layoutCrossAxisGap, 0.0);
}

static endLayoutContainerStyle(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
