// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { LayoutDimensionUnit } from '../grida/layout-dimension-unit';


/**
 * Dimension value. (width/height)
 *
 * Canonical mapping:
 * - TS `number` or `{type:"length", unit:"px"}` -> `Px`
 * - TS `{type:"percentage"}` -> `Percent`
 */
export class LayoutDimensionValue {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):LayoutDimensionValue {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsLayoutDimensionValue(bb:flatbuffers.ByteBuffer, obj?:LayoutDimensionValue):LayoutDimensionValue {
  return (obj || new LayoutDimensionValue()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsLayoutDimensionValue(bb:flatbuffers.ByteBuffer, obj?:LayoutDimensionValue):LayoutDimensionValue {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new LayoutDimensionValue()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

unit():LayoutDimensionUnit {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : LayoutDimensionUnit.LengthPx;
}

value():number|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : null;
}

static startLayoutDimensionValue(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addUnit(builder:flatbuffers.Builder, unit:LayoutDimensionUnit) {
  builder.addFieldInt8(0, unit, LayoutDimensionUnit.LengthPx);
}

static addValue(builder:flatbuffers.Builder, value:number) {
  builder.addFieldFloat32(1, value, null);
}

static endLayoutDimensionValue(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createLayoutDimensionValue(builder:flatbuffers.Builder, unit:LayoutDimensionUnit, value:number|null):flatbuffers.Offset {
  LayoutDimensionValue.startLayoutDimensionValue(builder);
  LayoutDimensionValue.addUnit(builder, unit);
  if (value !== null)
    LayoutDimensionValue.addValue(builder, value);
  return LayoutDimensionValue.endLayoutDimensionValue(builder);
}
}
