// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { LayoutChildStyle } from '../grida/layout-child-style';
import { LayoutContainerStyle } from '../grida/layout-container-style';
import { LayoutDimensionStyle } from '../grida/layout-dimension-style';
import { LayoutPositioningBasis, unionToLayoutPositioningBasis, unionListToLayoutPositioningBasis } from '../grida/layout-positioning-basis';


export class LayoutStyle {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):LayoutStyle {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsLayoutStyle(bb:flatbuffers.ByteBuffer, obj?:LayoutStyle):LayoutStyle {
  return (obj || new LayoutStyle()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsLayoutStyle(bb:flatbuffers.ByteBuffer, obj?:LayoutStyle):LayoutStyle {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new LayoutStyle()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

layoutPositionType():LayoutPositioningBasis {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : LayoutPositioningBasis.NONE;
}

layoutPosition<T extends flatbuffers.Table>(obj:any):any|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__union(obj, this.bb_pos + offset) : null;
}

layoutDimensions(obj?:LayoutDimensionStyle):LayoutDimensionStyle|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new LayoutDimensionStyle()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

layoutContainer(obj?:LayoutContainerStyle):LayoutContainerStyle|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? (obj || new LayoutContainerStyle()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

layoutChild(obj?:LayoutChildStyle):LayoutChildStyle|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? (obj || new LayoutChildStyle()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startLayoutStyle(builder:flatbuffers.Builder) {
  builder.startObject(5);
}

static addLayoutPositionType(builder:flatbuffers.Builder, layoutPositionType:LayoutPositioningBasis) {
  builder.addFieldInt8(0, layoutPositionType, LayoutPositioningBasis.NONE);
}

static addLayoutPosition(builder:flatbuffers.Builder, layoutPositionOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, layoutPositionOffset, 0);
}

static addLayoutDimensions(builder:flatbuffers.Builder, layoutDimensionsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, layoutDimensionsOffset, 0);
}

static addLayoutContainer(builder:flatbuffers.Builder, layoutContainerOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, layoutContainerOffset, 0);
}

static addLayoutChild(builder:flatbuffers.Builder, layoutChildOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, layoutChildOffset, 0);
}

static endLayoutStyle(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
