// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { CGSize } from '../grida/cgsize';
import { LayoutDimensionValue } from '../grida/layout-dimension-value';


/**
 * `LayoutDimensionStyle {}`
 */
export class LayoutDimensionStyle {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):LayoutDimensionStyle {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsLayoutDimensionStyle(bb:flatbuffers.ByteBuffer, obj?:LayoutDimensionStyle):LayoutDimensionStyle {
  return (obj || new LayoutDimensionStyle()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsLayoutDimensionStyle(bb:flatbuffers.ByteBuffer, obj?:LayoutDimensionStyle):LayoutDimensionStyle {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new LayoutDimensionStyle()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

/**
 * unset = auto
 */
layoutTargetWidth(obj?:LayoutDimensionValue):LayoutDimensionValue|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new LayoutDimensionValue()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

/**
 * unset = auto
 */
layoutTargetHeight(obj?:LayoutDimensionValue):LayoutDimensionValue|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new LayoutDimensionValue()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

/**
 * Preferred layout aspect ratio.
 *
 * Represents a proportional relationship between width and height expressed
 * as a ratio pair (e.g. `(16, 9)`, `(4, 3)`, `(1, 1)`).
 * 
 * (0, 0) represents and is handled as "unset".
 *
 * Notes:
 * - This does not define geometry by itself. It is a sizing preference that
 *   layout engines may consult when resolving under-specified dimensions
 *   (e.g. when either width or height is "auto") or when proportional sizing
 *   is explicitly required by the layout model.
 * - When both width and height are definitively specified, this should have
 *   no effect and must not override explicit dimensions.
 * - Layout engines may ignore this if aspect-ratio-aware sizing is not supported.
 *
 * Encoding:
 * - Stored as a tuple (width, height) for parity with TS `layout_target_aspect_ratio?: [number, number]`.
 */
layoutTargetAspectRatio(obj?:CGSize):CGSize|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new CGSize()).__init(this.bb_pos + offset, this.bb!) : null;
}

static startLayoutDimensionStyle(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addLayoutTargetWidth(builder:flatbuffers.Builder, layoutTargetWidthOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, layoutTargetWidthOffset, 0);
}

static addLayoutTargetHeight(builder:flatbuffers.Builder, layoutTargetHeightOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, layoutTargetHeightOffset, 0);
}

static addLayoutTargetAspectRatio(builder:flatbuffers.Builder, layoutTargetAspectRatioOffset:flatbuffers.Offset) {
  builder.addFieldStruct(2, layoutTargetAspectRatioOffset, 0);
}

static endLayoutDimensionStyle(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
