// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import { LayoutPositioningCartesian } from '../grida/layout-positioning-cartesian';
import { LayoutPositioningInset } from '../grida/layout-positioning-inset';


export enum LayoutPositioningBasis {
  NONE = 0,
  LayoutPositioningCartesian = 1,
  LayoutPositioningInset = 2
}

export function unionToLayoutPositioningBasis(
  type: LayoutPositioningBasis,
  accessor: (obj:LayoutPositioningCartesian|LayoutPositioningInset) => LayoutPositioningCartesian|LayoutPositioningInset|null
): LayoutPositioningCartesian|LayoutPositioningInset|null {
  switch(LayoutPositioningBasis[type]) {
    case 'NONE': return null; 
    case 'LayoutPositioningCartesian': return accessor(new LayoutPositioningCartesian())! as LayoutPositioningCartesian;
    case 'LayoutPositioningInset': return accessor(new LayoutPositioningInset())! as LayoutPositioningInset;
    default: return null;
  }
}

export function unionListToLayoutPositioningBasis(
  type: LayoutPositioningBasis, 
  accessor: (index: number, obj:LayoutPositioningCartesian|LayoutPositioningInset) => LayoutPositioningCartesian|LayoutPositioningInset|null, 
  index: number
): LayoutPositioningCartesian|LayoutPositioningInset|null {
  switch(LayoutPositioningBasis[type]) {
    case 'NONE': return null; 
    case 'LayoutPositioningCartesian': return accessor(index, new LayoutPositioningCartesian())! as LayoutPositioningCartesian;
    case 'LayoutPositioningInset': return accessor(index, new LayoutPositioningInset())! as LayoutPositioningInset;
    default: return null;
  }
}
