// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { PositioningSideOffsetValue } from '../grida/positioning-side-offset-value';


/**
 * left, top, right, bottom positioning model (css standard)
 */
export class LayoutPositioningInset {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):LayoutPositioningInset {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsLayoutPositioningInset(bb:flatbuffers.ByteBuffer, obj?:LayoutPositioningInset):LayoutPositioningInset {
  return (obj || new LayoutPositioningInset()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsLayoutPositioningInset(bb:flatbuffers.ByteBuffer, obj?:LayoutPositioningInset):LayoutPositioningInset {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new LayoutPositioningInset()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

top(obj?:PositioningSideOffsetValue):PositioningSideOffsetValue|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new PositioningSideOffsetValue()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

right(obj?:PositioningSideOffsetValue):PositioningSideOffsetValue|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new PositioningSideOffsetValue()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

bottom(obj?:PositioningSideOffsetValue):PositioningSideOffsetValue|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new PositioningSideOffsetValue()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

left(obj?:PositioningSideOffsetValue):PositioningSideOffsetValue|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? (obj || new PositioningSideOffsetValue()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startLayoutPositioningInset(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addTop(builder:flatbuffers.Builder, topOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, topOffset, 0);
}

static addRight(builder:flatbuffers.Builder, rightOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, rightOffset, 0);
}

static addBottom(builder:flatbuffers.Builder, bottomOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, bottomOffset, 0);
}

static addLeft(builder:flatbuffers.Builder, leftOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, leftOffset, 0);
}

static endLayoutPositioningInset(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
