// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Alignment } from '../grida/alignment';
import { BlendMode } from '../grida/blend-mode';
import { CGTransform2D } from '../grida/cgtransform2-d';
import { GradientStop } from '../grida/gradient-stop';
import { TileMode } from '../grida/tile-mode';


export class LinearGradientPaint {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):LinearGradientPaint {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsLinearGradientPaint(bb:flatbuffers.ByteBuffer, obj?:LinearGradientPaint):LinearGradientPaint {
  return (obj || new LinearGradientPaint()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsLinearGradientPaint(bb:flatbuffers.ByteBuffer, obj?:LinearGradientPaint):LinearGradientPaint {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new LinearGradientPaint()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

active():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : true;
}

xy1(obj?:Alignment):Alignment|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new Alignment()).__init(this.bb_pos + offset, this.bb!) : null;
}

xy2(obj?:Alignment):Alignment|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new Alignment()).__init(this.bb_pos + offset, this.bb!) : null;
}

tileMode():TileMode {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : TileMode.Clamp;
}

/**
 * transform of the gradient, if empty(unset) canonical is identity
 */
transform(obj?:CGTransform2D):CGTransform2D|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? (obj || new CGTransform2D()).__init(this.bb_pos + offset, this.bb!) : null;
}

stops(index: number, obj?:GradientStop):GradientStop|null {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? (obj || new GradientStop()).__init(this.bb!.__vector(this.bb_pos + offset) + index * 20, this.bb!) : null;
}

stopsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

opacity():number {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 1.0;
}

blendMode():BlendMode {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : BlendMode.Normal;
}

static startLinearGradientPaint(builder:flatbuffers.Builder) {
  builder.startObject(8);
}

static addActive(builder:flatbuffers.Builder, active:boolean) {
  builder.addFieldInt8(0, +active, +true);
}

static addXy1(builder:flatbuffers.Builder, xy1Offset:flatbuffers.Offset) {
  builder.addFieldStruct(1, xy1Offset, 0);
}

static addXy2(builder:flatbuffers.Builder, xy2Offset:flatbuffers.Offset) {
  builder.addFieldStruct(2, xy2Offset, 0);
}

static addTileMode(builder:flatbuffers.Builder, tileMode:TileMode) {
  builder.addFieldInt8(3, tileMode, TileMode.Clamp);
}

static addTransform(builder:flatbuffers.Builder, transformOffset:flatbuffers.Offset) {
  builder.addFieldStruct(4, transformOffset, 0);
}

static addStops(builder:flatbuffers.Builder, stopsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(5, stopsOffset, 0);
}

static startStopsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(20, numElems, 4);
}

static addOpacity(builder:flatbuffers.Builder, opacity:number) {
  builder.addFieldFloat32(6, opacity, 1.0);
}

static addBlendMode(builder:flatbuffers.Builder, blendMode:BlendMode) {
  builder.addFieldInt8(7, blendMode, BlendMode.Normal);
}

static endLinearGradientPaint(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
