// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum MainAxisAlignment {
  None = 0,
  Start = 1,
  End = 2,
  Center = 3,
  SpaceBetween = 4,
  SpaceAround = 5,
  SpaceEvenly = 6,
  Stretch = 7
}
