// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { LayerTrait } from '../grida/layer-trait';
import { MarkdownEmbedNodeProperties } from '../grida/markdown-embed-node-properties';
import { SystemNodeTrait } from '../grida/system-node-trait';


/**
 * Node variant: Markdown embed (render-only).
 *
 * Stores GFM markdown source and renders it directly to a Skia Picture
 * at paint time. Not structurally editable — treated as a single text block.
 */
export class MarkdownEmbedNode {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):MarkdownEmbedNode {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsMarkdownEmbedNode(bb:flatbuffers.ByteBuffer, obj?:MarkdownEmbedNode):MarkdownEmbedNode {
  return (obj || new MarkdownEmbedNode()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsMarkdownEmbedNode(bb:flatbuffers.ByteBuffer, obj?:MarkdownEmbedNode):MarkdownEmbedNode {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new MarkdownEmbedNode()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

node(obj?:SystemNodeTrait):SystemNodeTrait|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new SystemNodeTrait()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

layer(obj?:LayerTrait):LayerTrait|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new LayerTrait()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

properties(obj?:MarkdownEmbedNodeProperties):MarkdownEmbedNodeProperties|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new MarkdownEmbedNodeProperties()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startMarkdownEmbedNode(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addNode(builder:flatbuffers.Builder, nodeOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, nodeOffset, 0);
}

static addLayer(builder:flatbuffers.Builder, layerOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, layerOffset, 0);
}

static addProperties(builder:flatbuffers.Builder, propertiesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, propertiesOffset, 0);
}

static endMarkdownEmbedNode(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // node
  builder.requiredField(offset, 6) // layer
  return offset;
}

}
