// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { PaintStackItem } from '../grida/paint-stack-item';
import { RectangularCornerRadiusTrait } from '../grida/rectangular-corner-radius-trait';


/**
 * Properties for a Markdown embed node.
 */
export class MarkdownEmbedNodeProperties {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):MarkdownEmbedNodeProperties {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsMarkdownEmbedNodeProperties(bb:flatbuffers.ByteBuffer, obj?:MarkdownEmbedNodeProperties):MarkdownEmbedNodeProperties {
  return (obj || new MarkdownEmbedNodeProperties()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsMarkdownEmbedNodeProperties(bb:flatbuffers.ByteBuffer, obj?:MarkdownEmbedNodeProperties):MarkdownEmbedNodeProperties {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new MarkdownEmbedNodeProperties()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

/**
 * Background fill paints for the markdown container.
 */
fillPaints(index: number, obj?:PaintStackItem):PaintStackItem|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new PaintStackItem()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

fillPaintsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

/**
 * The GitHub Flavored Markdown source text.
 */
markdown():string|null
markdown(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
markdown(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

/**
 * Per-corner rectangular corner radius.
 */
cornerRadius(obj?:RectangularCornerRadiusTrait):RectangularCornerRadiusTrait|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new RectangularCornerRadiusTrait()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startMarkdownEmbedNodeProperties(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addFillPaints(builder:flatbuffers.Builder, fillPaintsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, fillPaintsOffset, 0);
}

static createFillPaintsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startFillPaintsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addMarkdown(builder:flatbuffers.Builder, markdownOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, markdownOffset, 0);
}

static addCornerRadius(builder:flatbuffers.Builder, cornerRadiusOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, cornerRadiusOffset, 0);
}

static endMarkdownEmbedNodeProperties(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
