// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import { AttributedTextNode } from '../grida/attributed-text-node';
import { BasicShapeNode } from '../grida/basic-shape-node';
import { BooleanOperationNode } from '../grida/boolean-operation-node';
import { ContainerNode } from '../grida/container-node';
import { GroupNode } from '../grida/group-node';
import { InitialContainerNode } from '../grida/initial-container-node';
import { LineNode } from '../grida/line-node';
import { MarkdownEmbedNode } from '../grida/markdown-embed-node';
import { PathNode } from '../grida/path-node';
import { SceneNode } from '../grida/scene-node';
import { TextSpanNode } from '../grida/text-span-node';
import { TrayNode } from '../grida/tray-node';
import { UnknownNode } from '../grida/unknown-node';
import { VectorNode } from '../grida/vector-node';


export enum Node {
  NONE = 0,
  UnknownNode = 1,
  SceneNode = 2,
  GroupNode = 3,
  InitialContainerNode = 4,
  ContainerNode = 5,
  BooleanOperationNode = 6,
  BasicShapeNode = 7,
  LineNode = 8,
  VectorNode = 9,
  TextSpanNode = 10,
  PathNode = 11,
  AttributedTextNode = 12,
  TrayNode = 13,
  MarkdownEmbedNode = 14
}

export function unionToNode(
  type: Node,
  accessor: (obj:AttributedTextNode|BasicShapeNode|BooleanOperationNode|ContainerNode|GroupNode|InitialContainerNode|LineNode|MarkdownEmbedNode|PathNode|SceneNode|TextSpanNode|TrayNode|UnknownNode|VectorNode) => AttributedTextNode|BasicShapeNode|BooleanOperationNode|ContainerNode|GroupNode|InitialContainerNode|LineNode|MarkdownEmbedNode|PathNode|SceneNode|TextSpanNode|TrayNode|UnknownNode|VectorNode|null
): AttributedTextNode|BasicShapeNode|BooleanOperationNode|ContainerNode|GroupNode|InitialContainerNode|LineNode|MarkdownEmbedNode|PathNode|SceneNode|TextSpanNode|TrayNode|UnknownNode|VectorNode|null {
  switch(Node[type]) {
    case 'NONE': return null; 
    case 'UnknownNode': return accessor(new UnknownNode())! as UnknownNode;
    case 'SceneNode': return accessor(new SceneNode())! as SceneNode;
    case 'GroupNode': return accessor(new GroupNode())! as GroupNode;
    case 'InitialContainerNode': return accessor(new InitialContainerNode())! as InitialContainerNode;
    case 'ContainerNode': return accessor(new ContainerNode())! as ContainerNode;
    case 'BooleanOperationNode': return accessor(new BooleanOperationNode())! as BooleanOperationNode;
    case 'BasicShapeNode': return accessor(new BasicShapeNode())! as BasicShapeNode;
    case 'LineNode': return accessor(new LineNode())! as LineNode;
    case 'VectorNode': return accessor(new VectorNode())! as VectorNode;
    case 'TextSpanNode': return accessor(new TextSpanNode())! as TextSpanNode;
    case 'PathNode': return accessor(new PathNode())! as PathNode;
    case 'AttributedTextNode': return accessor(new AttributedTextNode())! as AttributedTextNode;
    case 'TrayNode': return accessor(new TrayNode())! as TrayNode;
    case 'MarkdownEmbedNode': return accessor(new MarkdownEmbedNode())! as MarkdownEmbedNode;
    default: return null;
  }
}

export function unionListToNode(
  type: Node, 
  accessor: (index: number, obj:AttributedTextNode|BasicShapeNode|BooleanOperationNode|ContainerNode|GroupNode|InitialContainerNode|LineNode|MarkdownEmbedNode|PathNode|SceneNode|TextSpanNode|TrayNode|UnknownNode|VectorNode) => AttributedTextNode|BasicShapeNode|BooleanOperationNode|ContainerNode|GroupNode|InitialContainerNode|LineNode|MarkdownEmbedNode|PathNode|SceneNode|TextSpanNode|TrayNode|UnknownNode|VectorNode|null, 
  index: number
): AttributedTextNode|BasicShapeNode|BooleanOperationNode|ContainerNode|GroupNode|InitialContainerNode|LineNode|MarkdownEmbedNode|PathNode|SceneNode|TextSpanNode|TrayNode|UnknownNode|VectorNode|null {
  switch(Node[type]) {
    case 'NONE': return null; 
    case 'UnknownNode': return accessor(index, new UnknownNode())! as UnknownNode;
    case 'SceneNode': return accessor(index, new SceneNode())! as SceneNode;
    case 'GroupNode': return accessor(index, new GroupNode())! as GroupNode;
    case 'InitialContainerNode': return accessor(index, new InitialContainerNode())! as InitialContainerNode;
    case 'ContainerNode': return accessor(index, new ContainerNode())! as ContainerNode;
    case 'BooleanOperationNode': return accessor(index, new BooleanOperationNode())! as BooleanOperationNode;
    case 'BasicShapeNode': return accessor(index, new BasicShapeNode())! as BasicShapeNode;
    case 'LineNode': return accessor(index, new LineNode())! as LineNode;
    case 'VectorNode': return accessor(index, new VectorNode())! as VectorNode;
    case 'TextSpanNode': return accessor(index, new TextSpanNode())! as TextSpanNode;
    case 'PathNode': return accessor(index, new PathNode())! as PathNode;
    case 'AttributedTextNode': return accessor(index, new AttributedTextNode())! as AttributedTextNode;
    case 'TrayNode': return accessor(index, new TrayNode())! as TrayNode;
    case 'MarkdownEmbedNode': return accessor(index, new MarkdownEmbedNode())! as MarkdownEmbedNode;
    default: return null;
  }
}
