// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Node, unionToNode, unionListToNode } from '../grida/node';


/**
 * Wrapper table for a single Node union entry in a flat node vector.
 *
 * FlatBuffers Rust codegen does not support `[Node]` (vector of unions) directly.
 * Using `[NodeSlot]` (vector of tables each containing a union field) is the
 * canonical workaround — identical in spirit to `PaintStackItem` wrapping `Paint`.
 * See: https://github.com/google/flatbuffers/issues/8011
 */
export class NodeSlot {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):NodeSlot {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsNodeSlot(bb:flatbuffers.ByteBuffer, obj?:NodeSlot):NodeSlot {
  return (obj || new NodeSlot()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsNodeSlot(bb:flatbuffers.ByteBuffer, obj?:NodeSlot):NodeSlot {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new NodeSlot()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

nodeType():Node {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : Node.NONE;
}

node<T extends flatbuffers.Table>(obj:any):any|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__union(obj, this.bb_pos + offset) : null;
}

static startNodeSlot(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addNodeType(builder:flatbuffers.Builder, nodeType:Node) {
  builder.addFieldInt8(0, nodeType, Node.NONE);
}

static addNode(builder:flatbuffers.Builder, nodeOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, nodeOffset, 0);
}

static endNodeSlot(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createNodeSlot(builder:flatbuffers.Builder, nodeType:Node, nodeOffset:flatbuffers.Offset):flatbuffers.Offset {
  NodeSlot.startNodeSlot(builder);
  NodeSlot.addNodeType(builder, nodeType);
  NodeSlot.addNode(builder, nodeOffset);
  return NodeSlot.endNodeSlot(builder);
}
}
