// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

/**
 * Node identifier (temporary: string-based for compatibility with current editor).
 *
 * TODO: Update to use packed u32 (actor:8 | counter:24) for better performance.
 * Range: 0..=4_294_967_295.
 *
 * Current implementation uses string IDs to match TS editor model.
 * Future: migrate to struct NodeIdentifier { packed:uint; } for efficiency.
 */
export class NodeIdentifier {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):NodeIdentifier {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsNodeIdentifier(bb:flatbuffers.ByteBuffer, obj?:NodeIdentifier):NodeIdentifier {
  return (obj || new NodeIdentifier()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsNodeIdentifier(bb:flatbuffers.ByteBuffer, obj?:NodeIdentifier):NodeIdentifier {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new NodeIdentifier()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

/**
 * Required: unique identifier string for the node.
 */
id():string|null
id(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
id(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startNodeIdentifier(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addId(builder:flatbuffers.Builder, idOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, idOffset, 0);
}

static endNodeIdentifier(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // id
  return offset;
}

static createNodeIdentifier(builder:flatbuffers.Builder, idOffset:flatbuffers.Offset):flatbuffers.Offset {
  NodeIdentifier.startNodeIdentifier(builder);
  NodeIdentifier.addId(builder, idOffset);
  return NodeIdentifier.endNodeIdentifier(builder);
}
}
