// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

/**
 * Rust: `NoiseEffectColors` (enum)
 */
export enum NoiseEffectColorsKind {
  Mono = 0,
  Duo = 1,
  Multi = 2
}
