// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

/**
 * `None`
 */
export class None {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):None {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsNone(bb:flatbuffers.ByteBuffer, obj?:None):None {
  return (obj || new None()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsNone(bb:flatbuffers.ByteBuffer, obj?:None):None {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new None()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static startNone(builder:flatbuffers.Builder) {
  builder.startObject(0);
}

static endNone(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createNone(builder:flatbuffers.Builder):flatbuffers.Offset {
  None.startNone(builder);
  return None.endNone(builder);
}
}
