// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

/**
 * OpenType feature tag (4-byte ASCII, standard OpenType format).
 *
 * OpenType feature tags are exactly 4 characters, stored as 4 bytes.
 * This matches the binary OpenType format where tags are stored as [u8; 4].
 *
 * Examples:
 *   "kern" = {a:0x6B, b:0x65, c:0x72, d:0x6E}
 *   "liga" = {a:0x6C, b:0x69, c:0x67, d:0x61}
 *   "ss01" = {a:0x73, b:0x73, c:0x30, d:0x31}
 *
 * Codecs should convert between string tags (e.g., "kern") and this struct.
 * This approach allows any 4-character OpenType tag without schema evolution.
 */
export class OpenTypeFeatureTag {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):OpenTypeFeatureTag {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

a():number {
  return this.bb!.readUint8(this.bb_pos);
}

b():number {
  return this.bb!.readUint8(this.bb_pos + 1);
}

c():number {
  return this.bb!.readUint8(this.bb_pos + 2);
}

d():number {
  return this.bb!.readUint8(this.bb_pos + 3);
}

static sizeOf():number {
  return 4;
}

static createOpenTypeFeatureTag(builder:flatbuffers.Builder, a: number, b: number, c: number, d: number):flatbuffers.Offset {
  builder.prep(1, 4);
  builder.writeInt8(d);
  builder.writeInt8(c);
  builder.writeInt8(b);
  builder.writeInt8(a);
  return builder.offset();
}

}
