// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import { DiamondGradientPaint } from '../grida/diamond-gradient-paint';
import { ImagePaint } from '../grida/image-paint';
import { LinearGradientPaint } from '../grida/linear-gradient-paint';
import { RadialGradientPaint } from '../grida/radial-gradient-paint';
import { SolidPaint } from '../grida/solid-paint';
import { SweepGradientPaint } from '../grida/sweep-gradient-paint';


export enum Paint {
  NONE = 0,
  SolidPaint = 1,
  LinearGradientPaint = 2,
  RadialGradientPaint = 3,
  SweepGradientPaint = 4,
  DiamondGradientPaint = 5,
  ImagePaint = 6
}

export function unionToPaint(
  type: Paint,
  accessor: (obj:DiamondGradientPaint|ImagePaint|LinearGradientPaint|RadialGradientPaint|SolidPaint|SweepGradientPaint) => DiamondGradientPaint|ImagePaint|LinearGradientPaint|RadialGradientPaint|SolidPaint|SweepGradientPaint|null
): DiamondGradientPaint|ImagePaint|LinearGradientPaint|RadialGradientPaint|SolidPaint|SweepGradientPaint|null {
  switch(Paint[type]) {
    case 'NONE': return null; 
    case 'SolidPaint': return accessor(new SolidPaint())! as SolidPaint;
    case 'LinearGradientPaint': return accessor(new LinearGradientPaint())! as LinearGradientPaint;
    case 'RadialGradientPaint': return accessor(new RadialGradientPaint())! as RadialGradientPaint;
    case 'SweepGradientPaint': return accessor(new SweepGradientPaint())! as SweepGradientPaint;
    case 'DiamondGradientPaint': return accessor(new DiamondGradientPaint())! as DiamondGradientPaint;
    case 'ImagePaint': return accessor(new ImagePaint())! as ImagePaint;
    default: return null;
  }
}

export function unionListToPaint(
  type: Paint, 
  accessor: (index: number, obj:DiamondGradientPaint|ImagePaint|LinearGradientPaint|RadialGradientPaint|SolidPaint|SweepGradientPaint) => DiamondGradientPaint|ImagePaint|LinearGradientPaint|RadialGradientPaint|SolidPaint|SweepGradientPaint|null, 
  index: number
): DiamondGradientPaint|ImagePaint|LinearGradientPaint|RadialGradientPaint|SolidPaint|SweepGradientPaint|null {
  switch(Paint[type]) {
    case 'NONE': return null; 
    case 'SolidPaint': return accessor(index, new SolidPaint())! as SolidPaint;
    case 'LinearGradientPaint': return accessor(index, new LinearGradientPaint())! as LinearGradientPaint;
    case 'RadialGradientPaint': return accessor(index, new RadialGradientPaint())! as RadialGradientPaint;
    case 'SweepGradientPaint': return accessor(index, new SweepGradientPaint())! as SweepGradientPaint;
    case 'DiamondGradientPaint': return accessor(index, new DiamondGradientPaint())! as DiamondGradientPaint;
    case 'ImagePaint': return accessor(index, new ImagePaint())! as ImagePaint;
    default: return null;
  }
}
