// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Paint, unionToPaint, unionListToPaint } from '../grida/paint';


export class PaintStackItem {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):PaintStackItem {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsPaintStackItem(bb:flatbuffers.ByteBuffer, obj?:PaintStackItem):PaintStackItem {
  return (obj || new PaintStackItem()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsPaintStackItem(bb:flatbuffers.ByteBuffer, obj?:PaintStackItem):PaintStackItem {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new PaintStackItem()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

paintType():Paint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : Paint.NONE;
}

paint<T extends flatbuffers.Table>(obj:any):any|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__union(obj, this.bb_pos + offset) : null;
}

static startPaintStackItem(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addPaintType(builder:flatbuffers.Builder, paintType:Paint) {
  builder.addFieldInt8(0, paintType, Paint.NONE);
}

static addPaint(builder:flatbuffers.Builder, paintOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, paintOffset, 0);
}

static endPaintStackItem(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createPaintStackItem(builder:flatbuffers.Builder, paintType:Paint, paintOffset:flatbuffers.Offset):flatbuffers.Offset {
  PaintStackItem.startPaintStackItem(builder);
  PaintStackItem.addPaintType(builder, paintType);
  PaintStackItem.addPaint(builder, paintOffset);
  return PaintStackItem.endPaintStackItem(builder);
}
}
