// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { NodeIdentifier } from '../grida/node-identifier';


/**
 * Parent reference with fractional index position for ordering.
 *
 * Uses fractional indexing (orderable strings) to enable conflict-free
 * ordering in collaborative systems. The position string is designed to
 * sort correctly when compared lexicographically.
 *
 * Examples of fractional index strings: "!", " ~\"", "Qd&", "QeU", "Qe7", "QeO"
 *
 * Reference: Figma uses this same pattern (see `ParentIndex` in fig.kiwi).
 * This enables:
 * - Flat node structure (no nested children arrays)
 * - Efficient node moves (single node update, no parent reordering)
 * - Concurrent editing friendly ordering
 *
 * Note: Table (not struct) because it contains NodeIdentifier (a table).
 * This field is optional (can be null for root nodes).
 */
export class ParentReference {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ParentReference {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsParentReference(bb:flatbuffers.ByteBuffer, obj?:ParentReference):ParentReference {
  return (obj || new ParentReference()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsParentReference(bb:flatbuffers.ByteBuffer, obj?:ParentReference):ParentReference {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ParentReference()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

/**
 * Parent node identifier
 */
parentId(obj?:NodeIdentifier):NodeIdentifier|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new NodeIdentifier()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

/**
 * Fractional index position string for ordering among siblings.
 * Empty string means "unsorted" or "default position".
 * Children are sorted by lexicographic comparison of position strings.
 */
position():string|null
position(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
position(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startParentReference(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addParentId(builder:flatbuffers.Builder, parentIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, parentIdOffset, 0);
}

static addPosition(builder:flatbuffers.Builder, positionOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, positionOffset, 0);
}

static endParentReference(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // parent_id
  return offset;
}

static createParentReference(builder:flatbuffers.Builder, parentIdOffset:flatbuffers.Offset, positionOffset:flatbuffers.Offset):flatbuffers.Offset {
  ParentReference.startParentReference(builder);
  ParentReference.addParentId(builder, parentIdOffset);
  ParentReference.addPosition(builder, positionOffset);
  return ParentReference.endParentReference(builder);
}
}
