// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { FillRule } from '../grida/fill-rule';
import { LayerTrait } from '../grida/layer-trait';
import { PaintStackItem } from '../grida/paint-stack-item';
import { StrokeGeometryTrait } from '../grida/stroke-geometry-trait';
import { SystemNodeTrait } from '../grida/system-node-trait';


/**
 * Node variant: Path (raw SVG path data).
 *
 * Render-only node that stores SVG path data as a string. Avoids the overhead
 * of vector network conversion. Not editable — use VectorNode for editable
 * vector shapes.
 */
export class PathNode {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):PathNode {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsPathNode(bb:flatbuffers.ByteBuffer, obj?:PathNode):PathNode {
  return (obj || new PathNode()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsPathNode(bb:flatbuffers.ByteBuffer, obj?:PathNode):PathNode {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new PathNode()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

node(obj?:SystemNodeTrait):SystemNodeTrait|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new SystemNodeTrait()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

layer(obj?:LayerTrait):LayerTrait|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new LayerTrait()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

strokeGeometry(obj?:StrokeGeometryTrait):StrokeGeometryTrait|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new StrokeGeometryTrait()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

fillPaints(index: number, obj?:PaintStackItem):PaintStackItem|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? (obj || new PaintStackItem()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

fillPaintsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

strokePaints(index: number, obj?:PaintStackItem):PaintStackItem|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? (obj || new PaintStackItem()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

strokePaintsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

/**
 * Raw SVG path data string (e.g. "M0,0 L10,10 Z").
 */
data():string|null
data(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
data(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

fillRule():FillRule {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : FillRule.NonZero;
}

static startPathNode(builder:flatbuffers.Builder) {
  builder.startObject(7);
}

static addNode(builder:flatbuffers.Builder, nodeOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, nodeOffset, 0);
}

static addLayer(builder:flatbuffers.Builder, layerOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, layerOffset, 0);
}

static addStrokeGeometry(builder:flatbuffers.Builder, strokeGeometryOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, strokeGeometryOffset, 0);
}

static addFillPaints(builder:flatbuffers.Builder, fillPaintsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, fillPaintsOffset, 0);
}

static createFillPaintsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startFillPaintsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addStrokePaints(builder:flatbuffers.Builder, strokePaintsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, strokePaintsOffset, 0);
}

static createStrokePaintsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startStrokePaintsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addData(builder:flatbuffers.Builder, dataOffset:flatbuffers.Offset) {
  builder.addFieldOffset(5, dataOffset, 0);
}

static addFillRule(builder:flatbuffers.Builder, fillRule:FillRule) {
  builder.addFieldInt8(6, fillRule, FillRule.NonZero);
}

static endPathNode(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // node
  builder.requiredField(offset, 6) // layer
  return offset;
}

}
