// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { PositioningSideOffsetKind } from '../grida/positioning-side-offset-kind';


export class PositioningSideOffsetValue {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):PositioningSideOffsetValue {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsPositioningSideOffsetValue(bb:flatbuffers.ByteBuffer, obj?:PositioningSideOffsetValue):PositioningSideOffsetValue {
  return (obj || new PositioningSideOffsetValue()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsPositioningSideOffsetValue(bb:flatbuffers.ByteBuffer, obj?:PositioningSideOffsetValue):PositioningSideOffsetValue {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new PositioningSideOffsetValue()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

kind():PositioningSideOffsetKind {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : PositioningSideOffsetKind.Px;
}

value():number|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : null;
}

static startPositioningSideOffsetValue(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addKind(builder:flatbuffers.Builder, kind:PositioningSideOffsetKind) {
  builder.addFieldInt8(0, kind, PositioningSideOffsetKind.Px);
}

static addValue(builder:flatbuffers.Builder, value:number) {
  builder.addFieldFloat32(1, value, null);
}

static endPositioningSideOffsetValue(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createPositioningSideOffsetValue(builder:flatbuffers.Builder, kind:PositioningSideOffsetKind, value:number|null):flatbuffers.Offset {
  PositioningSideOffsetValue.startPositioningSideOffsetValue(builder);
  PositioningSideOffsetValue.addKind(builder, kind);
  if (value !== null)
    PositioningSideOffsetValue.addValue(builder, value);
  return PositioningSideOffsetValue.endPositioningSideOffsetValue(builder);
}
}
