// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { CGRadius } from '../grida/cgradius';


/**
 * Rust: `RectangularCornerRadius { tl,tr,bl,br: Radius }`
 */
export class RectangularCornerRadius {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):RectangularCornerRadius {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

tl(obj?:CGRadius):CGRadius|null {
  return (obj || new CGRadius()).__init(this.bb_pos, this.bb!);
}

tr(obj?:CGRadius):CGRadius|null {
  return (obj || new CGRadius()).__init(this.bb_pos + 8, this.bb!);
}

bl(obj?:CGRadius):CGRadius|null {
  return (obj || new CGRadius()).__init(this.bb_pos + 16, this.bb!);
}

br(obj?:CGRadius):CGRadius|null {
  return (obj || new CGRadius()).__init(this.bb_pos + 24, this.bb!);
}

static sizeOf():number {
  return 32;
}

static createRectangularCornerRadius(builder:flatbuffers.Builder, tl_rx: number, tl_ry: number, tr_rx: number, tr_ry: number, bl_rx: number, bl_ry: number, br_rx: number, br_ry: number):flatbuffers.Offset {
  builder.prep(4, 32);
  builder.prep(4, 8);
  builder.writeFloat32(br_ry);
  builder.writeFloat32(br_rx);
  builder.prep(4, 8);
  builder.writeFloat32(bl_ry);
  builder.writeFloat32(bl_rx);
  builder.prep(4, 8);
  builder.writeFloat32(tr_ry);
  builder.writeFloat32(tr_rx);
  builder.prep(4, 8);
  builder.writeFloat32(tl_ry);
  builder.writeFloat32(tl_rx);
  return builder.offset();
}

}
