// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { RectangularStrokeWidth } from '../grida/rectangular-stroke-width';
import { StrokeStyle } from '../grida/stroke-style';
import { VariableWidthProfile } from '../grida/variable-width-profile';


export class RectangularStrokeGeometryTrait {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):RectangularStrokeGeometryTrait {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsRectangularStrokeGeometryTrait(bb:flatbuffers.ByteBuffer, obj?:RectangularStrokeGeometryTrait):RectangularStrokeGeometryTrait {
  return (obj || new RectangularStrokeGeometryTrait()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsRectangularStrokeGeometryTrait(bb:flatbuffers.ByteBuffer, obj?:RectangularStrokeGeometryTrait):RectangularStrokeGeometryTrait {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new RectangularStrokeGeometryTrait()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

rectangularStrokeWidth(obj?:RectangularStrokeWidth):RectangularStrokeWidth|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new RectangularStrokeWidth()).__init(this.bb_pos + offset, this.bb!) : null;
}

strokeStyle(obj?:StrokeStyle):StrokeStyle|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new StrokeStyle()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

strokeWidthProfile(obj?:VariableWidthProfile):VariableWidthProfile|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new VariableWidthProfile()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startRectangularStrokeGeometryTrait(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addRectangularStrokeWidth(builder:flatbuffers.Builder, rectangularStrokeWidthOffset:flatbuffers.Offset) {
  builder.addFieldStruct(0, rectangularStrokeWidthOffset, 0);
}

static addStrokeStyle(builder:flatbuffers.Builder, strokeStyleOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, strokeStyleOffset, 0);
}

static addStrokeWidthProfile(builder:flatbuffers.Builder, strokeWidthProfileOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, strokeWidthProfileOffset, 0);
}

static endRectangularStrokeGeometryTrait(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
