// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

/**
 * Per-side stroke widths (archive model).
 *
 * Struct representation. Note: structs cannot be null/omitted; all-zeros can be
 * interpreted as "not used" by codec/runtime if desired.
 */
export class RectangularStrokeWidth {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):RectangularStrokeWidth {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

strokeTopWidth():number {
  return this.bb!.readFloat32(this.bb_pos);
}

strokeRightWidth():number {
  return this.bb!.readFloat32(this.bb_pos + 4);
}

strokeBottomWidth():number {
  return this.bb!.readFloat32(this.bb_pos + 8);
}

strokeLeftWidth():number {
  return this.bb!.readFloat32(this.bb_pos + 12);
}

static sizeOf():number {
  return 16;
}

static createRectangularStrokeWidth(builder:flatbuffers.Builder, stroke_top_width: number, stroke_right_width: number, stroke_bottom_width: number, stroke_left_width: number):flatbuffers.Offset {
  builder.prep(4, 16);
  builder.writeFloat32(stroke_left_width);
  builder.writeFloat32(stroke_bottom_width);
  builder.writeFloat32(stroke_right_width);
  builder.writeFloat32(stroke_top_width);
  return builder.offset();
}

}
