// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { RectangularCornerRadius } from '../grida/rectangular-corner-radius';


export class RectangularCornerRadiusTrait {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):RectangularCornerRadiusTrait {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsRectangularCornerRadiusTrait(bb:flatbuffers.ByteBuffer, obj?:RectangularCornerRadiusTrait):RectangularCornerRadiusTrait {
  return (obj || new RectangularCornerRadiusTrait()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsRectangularCornerRadiusTrait(bb:flatbuffers.ByteBuffer, obj?:RectangularCornerRadiusTrait):RectangularCornerRadiusTrait {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new RectangularCornerRadiusTrait()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

rectangularCornerRadius(obj?:RectangularCornerRadius):RectangularCornerRadius|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new RectangularCornerRadius()).__init(this.bb_pos + offset, this.bb!) : null;
}

cornerSmoothing():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

static startRectangularCornerRadiusTrait(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addRectangularCornerRadius(builder:flatbuffers.Builder, rectangularCornerRadiusOffset:flatbuffers.Offset) {
  builder.addFieldStruct(0, rectangularCornerRadiusOffset, 0);
}

static addCornerSmoothing(builder:flatbuffers.Builder, cornerSmoothing:number) {
  builder.addFieldFloat32(1, cornerSmoothing, 0.0);
}

static endRectangularCornerRadiusTrait(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createRectangularCornerRadiusTrait(builder:flatbuffers.Builder, rectangularCornerRadiusOffset:flatbuffers.Offset, cornerSmoothing:number):flatbuffers.Offset {
  RectangularCornerRadiusTrait.startRectangularCornerRadiusTrait(builder);
  RectangularCornerRadiusTrait.addRectangularCornerRadius(builder, rectangularCornerRadiusOffset);
  RectangularCornerRadiusTrait.addCornerSmoothing(builder, cornerSmoothing);
  return RectangularCornerRadiusTrait.endRectangularCornerRadiusTrait(builder);
}
}
