// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

/**
 * Rust: `ResourceRef::HASH(String)`
 */
export class ResourceRefHASH {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ResourceRefHASH {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsResourceRefHASH(bb:flatbuffers.ByteBuffer, obj?:ResourceRefHASH):ResourceRefHASH {
  return (obj || new ResourceRefHASH()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsResourceRefHASH(bb:flatbuffers.ByteBuffer, obj?:ResourceRefHASH):ResourceRefHASH {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ResourceRefHASH()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

hash():string|null
hash(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
hash(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startResourceRefHASH(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addHash(builder:flatbuffers.Builder, hashOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, hashOffset, 0);
}

static endResourceRefHASH(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createResourceRefHASH(builder:flatbuffers.Builder, hashOffset:flatbuffers.Offset):flatbuffers.Offset {
  ResourceRefHASH.startResourceRefHASH(builder);
  ResourceRefHASH.addHash(builder, hashOffset);
  return ResourceRefHASH.endResourceRefHASH(builder);
}
}
