// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import { ResourceRefHASH } from '../grida/resource-ref-hash';
import { ResourceRefRID } from '../grida/resource-ref-rid';


/**
 * Rust: `ResourceRef`
 */
export enum ResourceRef {
  NONE = 0,
  ResourceRefHASH = 1,
  ResourceRefRID = 2
}

export function unionToResourceRef(
  type: ResourceRef,
  accessor: (obj:ResourceRefHASH|ResourceRefRID) => ResourceRefHASH|ResourceRefRID|null
): ResourceRefHASH|ResourceRefRID|null {
  switch(ResourceRef[type]) {
    case 'NONE': return null; 
    case 'ResourceRefHASH': return accessor(new ResourceRefHASH())! as ResourceRefHASH;
    case 'ResourceRefRID': return accessor(new ResourceRefRID())! as ResourceRefRID;
    default: return null;
  }
}

export function unionListToResourceRef(
  type: ResourceRef, 
  accessor: (index: number, obj:ResourceRefHASH|ResourceRefRID) => ResourceRefHASH|ResourceRefRID|null, 
  index: number
): ResourceRefHASH|ResourceRefRID|null {
  switch(ResourceRef[type]) {
    case 'NONE': return null; 
    case 'ResourceRefHASH': return accessor(index, new ResourceRefHASH())! as ResourceRefHASH;
    case 'ResourceRefRID': return accessor(index, new ResourceRefRID())! as ResourceRefRID;
    default: return null;
  }
}
