// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

/**
 * Rust: `ResourceRef::RID(String)`
 */
export class ResourceRefRID {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ResourceRefRID {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsResourceRefRID(bb:flatbuffers.ByteBuffer, obj?:ResourceRefRID):ResourceRefRID {
  return (obj || new ResourceRefRID()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsResourceRefRID(bb:flatbuffers.ByteBuffer, obj?:ResourceRefRID):ResourceRefRID {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ResourceRefRID()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

rid():string|null
rid(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
rid(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startResourceRefRID(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addRid(builder:flatbuffers.Builder, ridOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, ridOffset, 0);
}

static endResourceRefRID(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createResourceRefRID(builder:flatbuffers.Builder, ridOffset:flatbuffers.Offset):flatbuffers.Offset {
  ResourceRefRID.startResourceRefRID(builder);
  ResourceRefRID.addRid(builder, ridOffset);
  return ResourceRefRID.endResourceRefRID(builder);
}
}
