// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

/**
 * RGBA in linear float space (0..1).
 */
export class RGBA32F {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):RGBA32F {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

r():number {
  return this.bb!.readFloat32(this.bb_pos);
}

g():number {
  return this.bb!.readFloat32(this.bb_pos + 4);
}

b():number {
  return this.bb!.readFloat32(this.bb_pos + 8);
}

a():number {
  return this.bb!.readFloat32(this.bb_pos + 12);
}

static sizeOf():number {
  return 16;
}

static createRGBA32F(builder:flatbuffers.Builder, r: number, g: number, b: number, a: number):flatbuffers.Offset {
  builder.prep(4, 16);
  builder.writeFloat32(a);
  builder.writeFloat32(b);
  builder.writeFloat32(g);
  builder.writeFloat32(r);
  return builder.offset();
}

}
