// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Edge2D } from '../grida/edge2-d';
import { Guide2D } from '../grida/guide2-d';
import { RGBA32F } from '../grida/rgba32-f';
import { SceneConstraintsChildren } from '../grida/scene-constraints-children';
import { SystemNodeTrait } from '../grida/system-node-trait';


/**
 * Node variant: Scene.
 *
 * SceneNode is special and doesn't use NodeCommon like other nodes.
 * It inlines only the relevant fields from NodeCommon.
 */
export class SceneNode {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):SceneNode {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSceneNode(bb:flatbuffers.ByteBuffer, obj?:SceneNode):SceneNode {
  return (obj || new SceneNode()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSceneNode(bb:flatbuffers.ByteBuffer, obj?:SceneNode):SceneNode {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SceneNode()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

node(obj?:SystemNodeTrait):SystemNodeTrait|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new SystemNodeTrait()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

/**
 * Scene-specific properties.
 */
constraintsChildren():SceneConstraintsChildren {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : SceneConstraintsChildren.Single;
}

/**
 * Scene background color (solid color only, RGBA32F).
 *
 * This is a simple solid color background. For gradient or image backgrounds,
 * use a background container node instead.
 */
sceneBackgroundColor(obj?:RGBA32F):RGBA32F|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new RGBA32F()).__init(this.bb_pos + offset, this.bb!) : null;
}

guides(index: number, obj?:Guide2D):Guide2D|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? (obj || new Guide2D()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

guidesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

edges(index: number, obj?:Edge2D):Edge2D|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? (obj || new Edge2D()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

edgesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

/**
 * Fractional index position string for ordering among siblings.
 * Empty string means "unsorted" or "default position".
 * Children are sorted by lexicographic comparison of position strings.
 */
position():string|null
position(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
position(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startSceneNode(builder:flatbuffers.Builder) {
  builder.startObject(6);
}

static addNode(builder:flatbuffers.Builder, nodeOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, nodeOffset, 0);
}

static addConstraintsChildren(builder:flatbuffers.Builder, constraintsChildren:SceneConstraintsChildren) {
  builder.addFieldInt8(1, constraintsChildren, SceneConstraintsChildren.Single);
}

static addSceneBackgroundColor(builder:flatbuffers.Builder, sceneBackgroundColorOffset:flatbuffers.Offset) {
  builder.addFieldStruct(2, sceneBackgroundColorOffset, 0);
}

static addGuides(builder:flatbuffers.Builder, guidesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, guidesOffset, 0);
}

static createGuidesVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startGuidesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addEdges(builder:flatbuffers.Builder, edgesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, edgesOffset, 0);
}

static createEdgesVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startEdgesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addPosition(builder:flatbuffers.Builder, positionOffset:flatbuffers.Offset) {
  builder.addFieldOffset(5, positionOffset, 0);
}

static endSceneNode(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // node
  return offset;
}

}
