// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { BlendMode } from '../grida/blend-mode';
import { RGBA32F } from '../grida/rgba32-f';


export class SolidPaint {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):SolidPaint {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSolidPaint(bb:flatbuffers.ByteBuffer, obj?:SolidPaint):SolidPaint {
  return (obj || new SolidPaint()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSolidPaint(bb:flatbuffers.ByteBuffer, obj?:SolidPaint):SolidPaint {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SolidPaint()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

active():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : true;
}

color(obj?:RGBA32F):RGBA32F|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new RGBA32F()).__init(this.bb_pos + offset, this.bb!) : null;
}

blendMode():BlendMode {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : BlendMode.Normal;
}

static startSolidPaint(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addActive(builder:flatbuffers.Builder, active:boolean) {
  builder.addFieldInt8(0, +active, +true);
}

static addColor(builder:flatbuffers.Builder, colorOffset:flatbuffers.Offset) {
  builder.addFieldStruct(1, colorOffset, 0);
}

static addBlendMode(builder:flatbuffers.Builder, blendMode:BlendMode) {
  builder.addFieldInt8(2, blendMode, BlendMode.Normal);
}

static endSolidPaint(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
