// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { StrokeStyle } from '../grida/stroke-style';
import { VariableWidthProfile } from '../grida/variable-width-profile';


export class StrokeGeometryTrait {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):StrokeGeometryTrait {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsStrokeGeometryTrait(bb:flatbuffers.ByteBuffer, obj?:StrokeGeometryTrait):StrokeGeometryTrait {
  return (obj || new StrokeGeometryTrait()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsStrokeGeometryTrait(bb:flatbuffers.ByteBuffer, obj?:StrokeGeometryTrait):StrokeGeometryTrait {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new StrokeGeometryTrait()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

strokeWidth():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

strokeStyle(obj?:StrokeStyle):StrokeStyle|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new StrokeStyle()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

strokeWidthProfile(obj?:VariableWidthProfile):VariableWidthProfile|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new VariableWidthProfile()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startStrokeGeometryTrait(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addStrokeWidth(builder:flatbuffers.Builder, strokeWidth:number) {
  builder.addFieldFloat32(0, strokeWidth, 0.0);
}

static addStrokeStyle(builder:flatbuffers.Builder, strokeStyleOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, strokeStyleOffset, 0);
}

static addStrokeWidthProfile(builder:flatbuffers.Builder, strokeWidthProfileOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, strokeWidthProfileOffset, 0);
}

static endStrokeGeometryTrait(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
