// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

/**
 * Marker decoration placed at stroke endpoints or vector vertices.
 *
 * Unlike StrokeCap (which maps to native backend caps like Skia PaintCap),
 * StrokeMarkerPreset represents explicit marker geometry drawn on top of the
 * stroke path. When a decoration is present at an endpoint, the renderer
 * uses Butt cap at that endpoint and draws the marker geometry instead.
 *
 * See: docs/wg/feat-2d/curve-decoration.md
 */
export enum StrokeMarkerPreset {
  /**
   * No decoration (endpoint uses the node's stroke_cap as normal).
   */
  None = 0,

  /**
   * Right triangle (90° at tip), open stroked chevron — not filled.
   */
  RightTriangleOpen = 1,

  /**
   * Filled equilateral triangle pointing forward.
   */
  EquilateralTriangle = 2,

  /**
   * Filled circle.
   */
  Circle = 3,

  /**
   * Filled axis-aligned square.
   */
  Square = 4,

  /**
   * Filled diamond (square rotated 45°).
   */
  Diamond = 5,

  /**
   * Filled vertical bar (rectangle) perpendicular to the stroke.
   */
  VerticalBar = 6
}
