// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { StrokeAlign } from '../grida/stroke-align';
import { StrokeCap } from '../grida/stroke-cap';
import { StrokeJoin } from '../grida/stroke-join';


export class StrokeStyle {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):StrokeStyle {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsStrokeStyle(bb:flatbuffers.ByteBuffer, obj?:StrokeStyle):StrokeStyle {
  return (obj || new StrokeStyle()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsStrokeStyle(bb:flatbuffers.ByteBuffer, obj?:StrokeStyle):StrokeStyle {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new StrokeStyle()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

strokeAlign():StrokeAlign {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : StrokeAlign.Inside;
}

strokeCap():StrokeCap {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : StrokeCap.Butt;
}

strokeJoin():StrokeJoin {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : StrokeJoin.Miter;
}

strokeMiterLimit():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 4.0;
}

/**
 * dash array in logical pixels. Empty or omitted means "no dash".
 */
strokeDashArray(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readFloat32(this.bb!.__vector(this.bb_pos + offset) + index * 4) : 0;
}

strokeDashArrayLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

strokeDashArrayArray():Float32Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? new Float32Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

static startStrokeStyle(builder:flatbuffers.Builder) {
  builder.startObject(5);
}

static addStrokeAlign(builder:flatbuffers.Builder, strokeAlign:StrokeAlign) {
  builder.addFieldInt8(0, strokeAlign, StrokeAlign.Inside);
}

static addStrokeCap(builder:flatbuffers.Builder, strokeCap:StrokeCap) {
  builder.addFieldInt8(1, strokeCap, StrokeCap.Butt);
}

static addStrokeJoin(builder:flatbuffers.Builder, strokeJoin:StrokeJoin) {
  builder.addFieldInt8(2, strokeJoin, StrokeJoin.Miter);
}

static addStrokeMiterLimit(builder:flatbuffers.Builder, strokeMiterLimit:number) {
  builder.addFieldFloat32(3, strokeMiterLimit, 4.0);
}

static addStrokeDashArray(builder:flatbuffers.Builder, strokeDashArrayOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, strokeDashArrayOffset, 0);
}

static createStrokeDashArrayVector(builder:flatbuffers.Builder, data:number[]|Float32Array):flatbuffers.Offset;
/**
 * @deprecated This Uint8Array overload will be removed in the future.
 */
static createStrokeDashArrayVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset;
static createStrokeDashArrayVector(builder:flatbuffers.Builder, data:number[]|Float32Array|Uint8Array):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addFloat32(data[i]!);
  }
  return builder.endVector();
}

static startStrokeDashArrayVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endStrokeStyle(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createStrokeStyle(builder:flatbuffers.Builder, strokeAlign:StrokeAlign, strokeCap:StrokeCap, strokeJoin:StrokeJoin, strokeMiterLimit:number, strokeDashArrayOffset:flatbuffers.Offset):flatbuffers.Offset {
  StrokeStyle.startStrokeStyle(builder);
  StrokeStyle.addStrokeAlign(builder, strokeAlign);
  StrokeStyle.addStrokeCap(builder, strokeCap);
  StrokeStyle.addStrokeJoin(builder, strokeJoin);
  StrokeStyle.addStrokeMiterLimit(builder, strokeMiterLimit);
  StrokeStyle.addStrokeDashArray(builder, strokeDashArrayOffset);
  return StrokeStyle.endStrokeStyle(builder);
}
}
