// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { PaintStackItem } from '../grida/paint-stack-item';
import { StrokeGeometryTrait } from '../grida/stroke-geometry-trait';
import { TextStyleRec } from '../grida/text-style-rec';


/**
 * A styled text run within an attributed string.
 * Byte offsets into the parent text string.
 * Mirrors node-level paint/stroke patterns — per-run fills, strokes,
 * and stroke geometry are optional overrides of the node-level defaults.
 */
export class StyledTextRunItem {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):StyledTextRunItem {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsStyledTextRunItem(bb:flatbuffers.ByteBuffer, obj?:StyledTextRunItem):StyledTextRunItem {
  return (obj || new StyledTextRunItem()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsStyledTextRunItem(bb:flatbuffers.ByteBuffer, obj?:StyledTextRunItem):StyledTextRunItem {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new StyledTextRunItem()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

start():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

end():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

textStyle(obj?:TextStyleRec):TextStyleRec|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new TextStyleRec()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

fillPaints(index: number, obj?:PaintStackItem):PaintStackItem|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? (obj || new PaintStackItem()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

fillPaintsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

strokePaints(index: number, obj?:PaintStackItem):PaintStackItem|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? (obj || new PaintStackItem()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

strokePaintsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

strokeGeometry(obj?:StrokeGeometryTrait):StrokeGeometryTrait|null {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? (obj || new StrokeGeometryTrait()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startStyledTextRunItem(builder:flatbuffers.Builder) {
  builder.startObject(6);
}

static addStart(builder:flatbuffers.Builder, start:number) {
  builder.addFieldInt32(0, start, 0);
}

static addEnd(builder:flatbuffers.Builder, end:number) {
  builder.addFieldInt32(1, end, 0);
}

static addTextStyle(builder:flatbuffers.Builder, textStyleOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, textStyleOffset, 0);
}

static addFillPaints(builder:flatbuffers.Builder, fillPaintsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, fillPaintsOffset, 0);
}

static createFillPaintsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startFillPaintsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addStrokePaints(builder:flatbuffers.Builder, strokePaintsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, strokePaintsOffset, 0);
}

static createStrokePaintsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startStrokePaintsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addStrokeGeometry(builder:flatbuffers.Builder, strokeGeometryOffset:flatbuffers.Offset) {
  builder.addFieldOffset(5, strokeGeometryOffset, 0);
}

static endStyledTextRunItem(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
