// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { NodeIdentifier } from '../grida/node-identifier';


/**
 * Universal node trait.
 */
export class SystemNodeTrait {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):SystemNodeTrait {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSystemNodeTrait(bb:flatbuffers.ByteBuffer, obj?:SystemNodeTrait):SystemNodeTrait {
  return (obj || new SystemNodeTrait()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSystemNodeTrait(bb:flatbuffers.ByteBuffer, obj?:SystemNodeTrait):SystemNodeTrait {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SystemNodeTrait()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

/**
 * unique identifier for the node. (required)
 */
id(obj?:NodeIdentifier):NodeIdentifier|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new NodeIdentifier()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

/**
 * whether the node is active. (visible, active)
 */
active():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : true;
}

/**
 * name of the node. (optional)
 */
name():string|null
name(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
name(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

/**
 * whether the node is locked. (locked, editor)
 */
locked():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

static startSystemNodeTrait(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addId(builder:flatbuffers.Builder, idOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, idOffset, 0);
}

static addActive(builder:flatbuffers.Builder, active:boolean) {
  builder.addFieldInt8(1, +active, +true);
}

static addName(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, nameOffset, 0);
}

static addLocked(builder:flatbuffers.Builder, locked:boolean) {
  builder.addFieldInt8(3, +locked, +false);
}

static endSystemNodeTrait(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // id
  return offset;
}

static createSystemNodeTrait(builder:flatbuffers.Builder, idOffset:flatbuffers.Offset, active:boolean, nameOffset:flatbuffers.Offset, locked:boolean):flatbuffers.Offset {
  SystemNodeTrait.startSystemNodeTrait(builder);
  SystemNodeTrait.addId(builder, idOffset);
  SystemNodeTrait.addActive(builder, active);
  SystemNodeTrait.addName(builder, nameOffset);
  SystemNodeTrait.addLocked(builder, locked);
  return SystemNodeTrait.endSystemNodeTrait(builder);
}
}
