// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { PaintStackItem } from '../grida/paint-stack-item';
import { StrokeGeometryTrait } from '../grida/stroke-geometry-trait';
import { TextAlign } from '../grida/text-align';
import { TextAlignVertical } from '../grida/text-align-vertical';
import { TextStyleRec } from '../grida/text-style-rec';


export class TextSpanNodeProperties {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):TextSpanNodeProperties {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsTextSpanNodeProperties(bb:flatbuffers.ByteBuffer, obj?:TextSpanNodeProperties):TextSpanNodeProperties {
  return (obj || new TextSpanNodeProperties()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsTextSpanNodeProperties(bb:flatbuffers.ByteBuffer, obj?:TextSpanNodeProperties):TextSpanNodeProperties {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new TextSpanNodeProperties()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

strokeGeometry(obj?:StrokeGeometryTrait):StrokeGeometryTrait|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new StrokeGeometryTrait()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

fillPaints(index: number, obj?:PaintStackItem):PaintStackItem|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new PaintStackItem()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

fillPaintsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

strokePaints(index: number, obj?:PaintStackItem):PaintStackItem|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new PaintStackItem()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

strokePaintsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

text():string|null
text(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
text(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

textStyle(obj?:TextStyleRec):TextStyleRec|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? (obj || new TextStyleRec()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

textAlign():TextAlign {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : TextAlign.Left;
}

textAlignVertical():TextAlignVertical {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : TextAlignVertical.Top;
}

maxLines():number {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

ellipsis():string|null
ellipsis(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
ellipsis(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startTextSpanNodeProperties(builder:flatbuffers.Builder) {
  builder.startObject(9);
}

static addStrokeGeometry(builder:flatbuffers.Builder, strokeGeometryOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, strokeGeometryOffset, 0);
}

static addFillPaints(builder:flatbuffers.Builder, fillPaintsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, fillPaintsOffset, 0);
}

static createFillPaintsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startFillPaintsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addStrokePaints(builder:flatbuffers.Builder, strokePaintsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, strokePaintsOffset, 0);
}

static createStrokePaintsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startStrokePaintsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addText(builder:flatbuffers.Builder, textOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, textOffset, 0);
}

static addTextStyle(builder:flatbuffers.Builder, textStyleOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, textStyleOffset, 0);
}

static addTextAlign(builder:flatbuffers.Builder, textAlign:TextAlign) {
  builder.addFieldInt8(5, textAlign, TextAlign.Left);
}

static addTextAlignVertical(builder:flatbuffers.Builder, textAlignVertical:TextAlignVertical) {
  builder.addFieldInt8(6, textAlignVertical, TextAlignVertical.Top);
}

static addMaxLines(builder:flatbuffers.Builder, maxLines:number) {
  builder.addFieldInt32(7, maxLines, 0);
}

static addEllipsis(builder:flatbuffers.Builder, ellipsisOffset:flatbuffers.Offset) {
  builder.addFieldOffset(8, ellipsisOffset, 0);
}

static endTextSpanNodeProperties(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
