// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

/**
 * Rust: `TextTransform`
 */
export enum TextTransform {
  None = 0,
  Uppercase = 1,
  Lowercase = 2,
  Capitalize = 3
}
