// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum TextAlign {
  Left = 0,
  Right = 1,
  Center = 2,
  Justify = 3
}
