// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { TextDimensionKind } from '../grida/text-dimension-kind';


export class TextDimension {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):TextDimension {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsTextDimension(bb:flatbuffers.ByteBuffer, obj?:TextDimension):TextDimension {
  return (obj || new TextDimension()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsTextDimension(bb:flatbuffers.ByteBuffer, obj?:TextDimension):TextDimension {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new TextDimension()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

kind():TextDimensionKind {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : TextDimensionKind.Normal;
}

value():number|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : null;
}

static startTextDimension(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addKind(builder:flatbuffers.Builder, kind:TextDimensionKind) {
  builder.addFieldInt8(0, kind, TextDimensionKind.Normal);
}

static addValue(builder:flatbuffers.Builder, value:number) {
  builder.addFieldFloat32(1, value, null);
}

static endTextDimension(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createTextDimension(builder:flatbuffers.Builder, kind:TextDimensionKind, value:number|null):flatbuffers.Offset {
  TextDimension.startTextDimension(builder);
  TextDimension.addKind(builder, kind);
  if (value !== null)
    TextDimension.addValue(builder, value);
  return TextDimension.endTextDimension(builder);
}
}
