// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { RGBA32F } from '../grida/rgba32-f';
import { TextDecorationLine } from '../grida/text-decoration-line';
import { TextDecorationStyle } from '../grida/text-decoration-style';


/**
 * Rust: `TextDecorationRec`
 *
 * Archive model notes:
 * - `decoration_color` uses RGBA32F (float space) to match this schema's color choice.
 */
export class TextDecorationRec {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):TextDecorationRec {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsTextDecorationRec(bb:flatbuffers.ByteBuffer, obj?:TextDecorationRec):TextDecorationRec {
  return (obj || new TextDecorationRec()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsTextDecorationRec(bb:flatbuffers.ByteBuffer, obj?:TextDecorationRec):TextDecorationRec {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new TextDecorationRec()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

textDecorationLine():TextDecorationLine {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : TextDecorationLine.None;
}

textDecorationStyle():TextDecorationStyle {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : TextDecorationStyle.Solid;
}

textDecorationSkipInk():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : true;
}

textDecorationThickness():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 1.0;
}

/**
 * decoration color override, if unset, inherits
 */
textDecorationColor(obj?:RGBA32F):RGBA32F|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? (obj || new RGBA32F()).__init(this.bb_pos + offset, this.bb!) : null;
}

static startTextDecorationRec(builder:flatbuffers.Builder) {
  builder.startObject(5);
}

static addTextDecorationLine(builder:flatbuffers.Builder, textDecorationLine:TextDecorationLine) {
  builder.addFieldInt8(0, textDecorationLine, TextDecorationLine.None);
}

static addTextDecorationStyle(builder:flatbuffers.Builder, textDecorationStyle:TextDecorationStyle) {
  builder.addFieldInt8(1, textDecorationStyle, TextDecorationStyle.Solid);
}

static addTextDecorationSkipInk(builder:flatbuffers.Builder, textDecorationSkipInk:boolean) {
  builder.addFieldInt8(2, +textDecorationSkipInk, +true);
}

static addTextDecorationThickness(builder:flatbuffers.Builder, textDecorationThickness:number) {
  builder.addFieldFloat32(3, textDecorationThickness, 1.0);
}

static addTextDecorationColor(builder:flatbuffers.Builder, textDecorationColorOffset:flatbuffers.Offset) {
  builder.addFieldStruct(4, textDecorationColorOffset, 0);
}

static endTextDecorationRec(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
