// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

/**
 * `TextLineHeight` (Normal | Fixed(f32) | Factor(f32))
 * `TextLetterSpacing` (Normal | Fixed(f32) | Factor(f32))
 * `TextWordSpacing` (Normal | Fixed(f32) | Factor(f32))
 */
export enum TextDimensionKind {
  Normal = 0,
  Fixed = 1,
  Factor = 2
}
