// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

/**
 * Rust: `TextDecorationLine`
 */
export enum TextDecorationLine {
  None = 0,
  Underline = 1,
  Overline = 2,
  LineThrough = 3
}
