// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { FontFeature } from '../grida/font-feature';
import { FontOpticalSizing } from '../grida/font-optical-sizing';
import { FontVariation } from '../grida/font-variation';
import { FontWeight } from '../grida/font-weight';
import { TextDecorationRec } from '../grida/text-decoration-rec';
import { TextDimension } from '../grida/text-dimension';
import { TextTransform } from '../grida/text-transform';


/**
 * `TextStyleRec {}`
 */
export class TextStyleRec {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):TextStyleRec {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsTextStyleRec(bb:flatbuffers.ByteBuffer, obj?:TextStyleRec):TextStyleRec {
  return (obj || new TextStyleRec()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsTextStyleRec(bb:flatbuffers.ByteBuffer, obj?:TextStyleRec):TextStyleRec {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new TextStyleRec()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

textDecoration(obj?:TextDecorationRec):TextDecorationRec|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new TextDecorationRec()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

fontFamily():string|null
fontFamily(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
fontFamily(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

fontSize():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 14.0;
}

fontWeight(obj?:FontWeight):FontWeight|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? (obj || new FontWeight()).__init(this.bb_pos + offset, this.bb!) : null;
}

fontWidth():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

fontStyleItalic():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

fontKerning():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : true;
}

fontOpticalSizing(obj?:FontOpticalSizing):FontOpticalSizing|null {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? (obj || new FontOpticalSizing()).__init(this.bb_pos + offset, this.bb!) : null;
}

fontFeatures(index: number, obj?:FontFeature):FontFeature|null {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? (obj || new FontFeature()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

fontFeaturesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

fontVariations(index: number, obj?:FontVariation):FontVariation|null {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? (obj || new FontVariation()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

fontVariationsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

letterSpacing(obj?:TextDimension):TextDimension|null {
  const offset = this.bb!.__offset(this.bb_pos, 24);
  return offset ? (obj || new TextDimension()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

wordSpacing(obj?:TextDimension):TextDimension|null {
  const offset = this.bb!.__offset(this.bb_pos, 26);
  return offset ? (obj || new TextDimension()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

lineHeight(obj?:TextDimension):TextDimension|null {
  const offset = this.bb!.__offset(this.bb_pos, 28);
  return offset ? (obj || new TextDimension()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

textTransform():TextTransform {
  const offset = this.bb!.__offset(this.bb_pos, 30);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : TextTransform.None;
}

static startTextStyleRec(builder:flatbuffers.Builder) {
  builder.startObject(14);
}

static addTextDecoration(builder:flatbuffers.Builder, textDecorationOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, textDecorationOffset, 0);
}

static addFontFamily(builder:flatbuffers.Builder, fontFamilyOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, fontFamilyOffset, 0);
}

static addFontSize(builder:flatbuffers.Builder, fontSize:number) {
  builder.addFieldFloat32(2, fontSize, 14.0);
}

static addFontWeight(builder:flatbuffers.Builder, fontWeightOffset:flatbuffers.Offset) {
  builder.addFieldStruct(3, fontWeightOffset, 0);
}

static addFontWidth(builder:flatbuffers.Builder, fontWidth:number) {
  builder.addFieldFloat32(4, fontWidth, 0.0);
}

static addFontStyleItalic(builder:flatbuffers.Builder, fontStyleItalic:boolean) {
  builder.addFieldInt8(5, +fontStyleItalic, +false);
}

static addFontKerning(builder:flatbuffers.Builder, fontKerning:boolean) {
  builder.addFieldInt8(6, +fontKerning, +true);
}

static addFontOpticalSizing(builder:flatbuffers.Builder, fontOpticalSizingOffset:flatbuffers.Offset) {
  builder.addFieldStruct(7, fontOpticalSizingOffset, 0);
}

static addFontFeatures(builder:flatbuffers.Builder, fontFeaturesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(8, fontFeaturesOffset, 0);
}

static createFontFeaturesVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startFontFeaturesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addFontVariations(builder:flatbuffers.Builder, fontVariationsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(9, fontVariationsOffset, 0);
}

static createFontVariationsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startFontVariationsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addLetterSpacing(builder:flatbuffers.Builder, letterSpacingOffset:flatbuffers.Offset) {
  builder.addFieldOffset(10, letterSpacingOffset, 0);
}

static addWordSpacing(builder:flatbuffers.Builder, wordSpacingOffset:flatbuffers.Offset) {
  builder.addFieldOffset(11, wordSpacingOffset, 0);
}

static addLineHeight(builder:flatbuffers.Builder, lineHeightOffset:flatbuffers.Offset) {
  builder.addFieldOffset(12, lineHeightOffset, 0);
}

static addTextTransform(builder:flatbuffers.Builder, textTransform:TextTransform) {
  builder.addFieldInt8(13, textTransform, TextTransform.None);
}

static endTextStyleRec(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 6) // font_family
  builder.requiredField(offset, 10) // font_weight
  return offset;
}

}
