// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { SystemNodeTrait } from '../grida/system-node-trait';


/**
 * Placeholder, unused.
 */
export class UnknownNode {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):UnknownNode {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsUnknownNode(bb:flatbuffers.ByteBuffer, obj?:UnknownNode):UnknownNode {
  return (obj || new UnknownNode()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsUnknownNode(bb:flatbuffers.ByteBuffer, obj?:UnknownNode):UnknownNode {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new UnknownNode()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

node(obj?:SystemNodeTrait):SystemNodeTrait|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new SystemNodeTrait()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startUnknownNode(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addNode(builder:flatbuffers.Builder, nodeOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, nodeOffset, 0);
}

static endUnknownNode(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // node
  return offset;
}

static createUnknownNode(builder:flatbuffers.Builder, nodeOffset:flatbuffers.Offset):flatbuffers.Offset {
  UnknownNode.startUnknownNode(builder);
  UnknownNode.addNode(builder, nodeOffset);
  return UnknownNode.endUnknownNode(builder);
}
}
