// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

/**
 * Rust: `Uv(pub f32, pub f32)` (normalized [0, 1] domain)
 */
export class UV {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):UV {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

u():number {
  return this.bb!.readFloat32(this.bb_pos);
}

v():number {
  return this.bb!.readFloat32(this.bb_pos + 4);
}

static sizeOf():number {
  return 8;
}

static createUV(builder:flatbuffers.Builder, u: number, v: number):flatbuffers.Offset {
  builder.prep(4, 8);
  builder.writeFloat32(v);
  builder.writeFloat32(u);
  return builder.offset();
}

}
