// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { VariableWidthStop } from '../grida/variable-width-stop';


/**
 * Variable-width stroke profile.
 *
 * Notes:
 * - This matches TS `cg.VariableWidthProfile` and Rust `grida::cg::varwidth::{WidthStop, VarWidthProfile}` at the wire level.
 * - `base` is intentionally not stored here; renderers should derive a base half-width from the node's `stroke_width`
 *   when `stops` is empty (see Rust `VarWidthSampler` behavior).
 */
export class VariableWidthProfile {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):VariableWidthProfile {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsVariableWidthProfile(bb:flatbuffers.ByteBuffer, obj?:VariableWidthProfile):VariableWidthProfile {
  return (obj || new VariableWidthProfile()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsVariableWidthProfile(bb:flatbuffers.ByteBuffer, obj?:VariableWidthProfile):VariableWidthProfile {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new VariableWidthProfile()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

stops(index: number, obj?:VariableWidthStop):VariableWidthStop|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new VariableWidthStop()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

stopsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startVariableWidthProfile(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addStops(builder:flatbuffers.Builder, stopsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, stopsOffset, 0);
}

static createStopsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startStopsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endVariableWidthProfile(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createVariableWidthProfile(builder:flatbuffers.Builder, stopsOffset:flatbuffers.Offset):flatbuffers.Offset {
  VariableWidthProfile.startVariableWidthProfile(builder);
  VariableWidthProfile.addStops(builder, stopsOffset);
  return VariableWidthProfile.endVariableWidthProfile(builder);
}
}
