// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

/**
 * A single stop in a variable-width stroke profile.
 *
 * - `u` is the normalized position along the stroke in [0, 1].
 * - `r` is the half-width ("radius") at this position in pixels.
 */
export class VariableWidthStop {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):VariableWidthStop {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsVariableWidthStop(bb:flatbuffers.ByteBuffer, obj?:VariableWidthStop):VariableWidthStop {
  return (obj || new VariableWidthStop()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsVariableWidthStop(bb:flatbuffers.ByteBuffer, obj?:VariableWidthStop):VariableWidthStop {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new VariableWidthStop()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

u():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

r():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

static startVariableWidthStop(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addU(builder:flatbuffers.Builder, u:number) {
  builder.addFieldFloat32(0, u, 0.0);
}

static addR(builder:flatbuffers.Builder, r:number) {
  builder.addFieldFloat32(1, r, 0.0);
}

static endVariableWidthStop(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createVariableWidthStop(builder:flatbuffers.Builder, u:number, r:number):flatbuffers.Offset {
  VariableWidthStop.startVariableWidthStop(builder);
  VariableWidthStop.addU(builder, u);
  VariableWidthStop.addR(builder, r);
  return VariableWidthStop.endVariableWidthStop(builder);
}
}
