// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { CGPoint } from '../grida/cgpoint';


/**
 * Rust: `(f32, f32)` vertex
 *
 * Stored as CGPoint (same coordinate space as node local geometry).
 * Indexed by position in the `vertices` array.
 */
export class VectorNetworkVertex {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):VectorNetworkVertex {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

vertexPosition(obj?:CGPoint):CGPoint|null {
  return (obj || new CGPoint()).__init(this.bb_pos, this.bb!);
}

static sizeOf():number {
  return 8;
}

static createVectorNetworkVertex(builder:flatbuffers.Builder, vertex_position_x: number, vertex_position_y: number):flatbuffers.Offset {
  builder.prep(4, 8);
  builder.prep(4, 8);
  builder.writeFloat32(vertex_position_y);
  builder.writeFloat32(vertex_position_x);
  return builder.offset();
}

}
