// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { CGPoint } from '../grida/cgpoint';
import { VectorNetworkRegion } from '../grida/vector-network-region';
import { VectorNetworkSegment } from '../grida/vector-network-segment';


/**
 * Rust: `VectorNetwork { vertices, segments, regions }`
 */
export class VectorNetworkData {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):VectorNetworkData {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsVectorNetworkData(bb:flatbuffers.ByteBuffer, obj?:VectorNetworkData):VectorNetworkData {
  return (obj || new VectorNetworkData()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsVectorNetworkData(bb:flatbuffers.ByteBuffer, obj?:VectorNetworkData):VectorNetworkData {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new VectorNetworkData()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

vertices(index: number, obj?:CGPoint):CGPoint|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new CGPoint()).__init(this.bb!.__vector(this.bb_pos + offset) + index * 8, this.bb!) : null;
}

verticesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

segments(index: number, obj?:VectorNetworkSegment):VectorNetworkSegment|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new VectorNetworkSegment()).__init(this.bb!.__vector(this.bb_pos + offset) + index * 24, this.bb!) : null;
}

segmentsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

regions(index: number, obj?:VectorNetworkRegion):VectorNetworkRegion|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new VectorNetworkRegion()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

regionsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startVectorNetworkData(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addVertices(builder:flatbuffers.Builder, verticesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, verticesOffset, 0);
}

static startVerticesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(8, numElems, 4);
}

static addSegments(builder:flatbuffers.Builder, segmentsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, segmentsOffset, 0);
}

static startSegmentsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(24, numElems, 4);
}

static addRegions(builder:flatbuffers.Builder, regionsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, regionsOffset, 0);
}

static createRegionsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startRegionsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endVectorNetworkData(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createVectorNetworkData(builder:flatbuffers.Builder, verticesOffset:flatbuffers.Offset, segmentsOffset:flatbuffers.Offset, regionsOffset:flatbuffers.Offset):flatbuffers.Offset {
  VectorNetworkData.startVectorNetworkData(builder);
  VectorNetworkData.addVertices(builder, verticesOffset);
  VectorNetworkData.addSegments(builder, segmentsOffset);
  VectorNetworkData.addRegions(builder, regionsOffset);
  return VectorNetworkData.endVectorNetworkData(builder);
}
}
