// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

/**
 * Rust: `VectorNetworkLoop(pub Vec<usize>)`
 *
 * A closed contour defined by indices into `segments`.
 */
export class VectorNetworkLoop {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):VectorNetworkLoop {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsVectorNetworkLoop(bb:flatbuffers.ByteBuffer, obj?:VectorNetworkLoop):VectorNetworkLoop {
  return (obj || new VectorNetworkLoop()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsVectorNetworkLoop(bb:flatbuffers.ByteBuffer, obj?:VectorNetworkLoop):VectorNetworkLoop {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new VectorNetworkLoop()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

loopSegmentIndices(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb!.__vector(this.bb_pos + offset) + index * 4) : 0;
}

loopSegmentIndicesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

loopSegmentIndicesArray():Uint32Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? new Uint32Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

static startVectorNetworkLoop(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addLoopSegmentIndices(builder:flatbuffers.Builder, loopSegmentIndicesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, loopSegmentIndicesOffset, 0);
}

static createLoopSegmentIndicesVector(builder:flatbuffers.Builder, data:number[]|Uint32Array):flatbuffers.Offset;
/**
 * @deprecated This Uint8Array overload will be removed in the future.
 */
static createLoopSegmentIndicesVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset;
static createLoopSegmentIndicesVector(builder:flatbuffers.Builder, data:number[]|Uint32Array|Uint8Array):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt32(data[i]!);
  }
  return builder.endVector();
}

static startLoopSegmentIndicesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endVectorNetworkLoop(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createVectorNetworkLoop(builder:flatbuffers.Builder, loopSegmentIndicesOffset:flatbuffers.Offset):flatbuffers.Offset {
  VectorNetworkLoop.startVectorNetworkLoop(builder);
  VectorNetworkLoop.addLoopSegmentIndices(builder, loopSegmentIndicesOffset);
  return VectorNetworkLoop.endVectorNetworkLoop(builder);
}
}
