// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { CGPoint } from '../grida/cgpoint';


/**
 * Rust: `VectorNetworkSegment { a, b, ta, tb }`
 *
 * `tangent_a` / `tangent_b` are relative tangent vectors used for cubic béziers.
 * When both tangents are zero, the segment is a straight line.
 */
export class VectorNetworkSegment {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):VectorNetworkSegment {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

segmentVertexA():number {
  return this.bb!.readUint32(this.bb_pos);
}

segmentVertexB():number {
  return this.bb!.readUint32(this.bb_pos + 4);
}

tangentA(obj?:CGPoint):CGPoint|null {
  return (obj || new CGPoint()).__init(this.bb_pos + 8, this.bb!);
}

tangentB(obj?:CGPoint):CGPoint|null {
  return (obj || new CGPoint()).__init(this.bb_pos + 16, this.bb!);
}

static sizeOf():number {
  return 24;
}

static createVectorNetworkSegment(builder:flatbuffers.Builder, segment_vertex_a: number, segment_vertex_b: number, tangent_a_x: number, tangent_a_y: number, tangent_b_x: number, tangent_b_y: number):flatbuffers.Offset {
  builder.prep(4, 24);
  builder.prep(4, 8);
  builder.writeFloat32(tangent_b_y);
  builder.writeFloat32(tangent_b_x);
  builder.prep(4, 8);
  builder.writeFloat32(tangent_a_y);
  builder.writeFloat32(tangent_a_x);
  builder.writeInt32(segment_vertex_b);
  builder.writeInt32(segment_vertex_a);
  return builder.offset();
}

}
