// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { FillRule } from '../grida/fill-rule';
import { PaintStackItem } from '../grida/paint-stack-item';
import { VectorNetworkLoop } from '../grida/vector-network-loop';


/**
 * Rust: `VectorNetworkRegion { loops, fill_rule, fills }`
 *
 * Archive model uses `region_fill_paints` (empty = no fill) instead of Option wrappers.
 */
export class VectorNetworkRegion {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):VectorNetworkRegion {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsVectorNetworkRegion(bb:flatbuffers.ByteBuffer, obj?:VectorNetworkRegion):VectorNetworkRegion {
  return (obj || new VectorNetworkRegion()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsVectorNetworkRegion(bb:flatbuffers.ByteBuffer, obj?:VectorNetworkRegion):VectorNetworkRegion {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new VectorNetworkRegion()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

regionLoops(index: number, obj?:VectorNetworkLoop):VectorNetworkLoop|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new VectorNetworkLoop()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

regionLoopsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

regionFillRule():FillRule {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : FillRule.NonZero;
}

regionFillPaints(index: number, obj?:PaintStackItem):PaintStackItem|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new PaintStackItem()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

regionFillPaintsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startVectorNetworkRegion(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addRegionLoops(builder:flatbuffers.Builder, regionLoopsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, regionLoopsOffset, 0);
}

static createRegionLoopsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startRegionLoopsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addRegionFillRule(builder:flatbuffers.Builder, regionFillRule:FillRule) {
  builder.addFieldInt8(1, regionFillRule, FillRule.NonZero);
}

static addRegionFillPaints(builder:flatbuffers.Builder, regionFillPaintsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, regionFillPaintsOffset, 0);
}

static createRegionFillPaintsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startRegionFillPaintsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endVectorNetworkRegion(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createVectorNetworkRegion(builder:flatbuffers.Builder, regionLoopsOffset:flatbuffers.Offset, regionFillRule:FillRule, regionFillPaintsOffset:flatbuffers.Offset):flatbuffers.Offset {
  VectorNetworkRegion.startVectorNetworkRegion(builder);
  VectorNetworkRegion.addRegionLoops(builder, regionLoopsOffset);
  VectorNetworkRegion.addRegionFillRule(builder, regionFillRule);
  VectorNetworkRegion.addRegionFillPaints(builder, regionFillPaintsOffset);
  return VectorNetworkRegion.endVectorNetworkRegion(builder);
}
}
