[package]
name = "figma"
version = "0.0.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
reqwest = "0.12.19"

[dev-dependencies]
zip = {version = "4.0.0", features = ["deflate"]}

