// GRIDA-SEC-004 / GRIDA-SEC-006 — host reference/persistence behavior over the public image operation.
// GRIDA-GG: provider — scoped image access stays inside the host transport.
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { GridaGatewaySessionStore, ProviderHttp } from "@grida/ai";
import { WorkspaceRegistry, type SecretsStore } from "@grida/daemon/server";
import { createWorkspaceAgentBindings } from "./workspace-agent-bindings";

const PNG =
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=";
const MODEL = "openai/gpt-image-2";

describe("workspace image operation consumer", () => {
  let root: string;
  let workspace: string;
  let scratch: string;
  let registry: WorkspaceRegistry;
  beforeEach(async () => {
    root = await fs.realpath(
      await fs.mkdtemp(path.join(os.tmpdir(), "grida-image-consumer-"))
    );
    workspace = path.join(root, "workspace");
    scratch = path.join(root, "scratch");
    await fs.mkdir(workspace);
    await fs.mkdir(scratch);
    registry = new WorkspaceRegistry(path.join(root, "registry"));
    await registry.open(workspace);
  });
  afterEach(async () => {
    vi.restoreAllMocks();
    await fs.rm(root, { recursive: true, force: true });
  });
  async function build(
    options: {
      keys?: Record<string, string>;
      get?: (id: string) => Promise<string | null>;
      gg?: GridaGatewaySessionStore;
      request?: typeof globalThis.fetch;
    } = {}
  ) {
    const request = vi.fn<typeof globalThis.fetch>(
      options.request ??
        (async () => Response.json({ data: [{ b64_json: PNG }] }))
    );
    const download = vi.fn<typeof globalThis.fetch>();
    const bindings = await createWorkspaceAgentBindings(
      { workspace_root: workspace },
      {
        workspace_registry: registry,
        scratch_dir: scratch,
        image_gen_enabled: true,
        secrets: {
          _getKey:
            options.get ?? (async (id: string) => options.keys?.[id] ?? null),
        } as unknown as SecretsStore,
        gg: options.gg,
        gg_base_url: options.gg ? "https://grida.test" : undefined,
        provider_http: new ProviderHttp({ request, download }),
      }
    );
    if (!bindings?.image_gen) throw new Error("missing image binding");
    return {
      bindings,
      generate: bindings.image_gen.generate.bind(bindings.image_gen),
      request,
      download,
    };
  }

  it("retains the agent default and writes generated bytes only into its scratch sink", async () => {
    const { generate, request, download } = await build({
      keys: { openrouter: "synthetic-key" },
    });
    const result = await generate({ prompt: "a red apple" });
    expect(result).toMatchObject({
      ok: true,
      mime: "image/png",
      width: 1,
      height: 1,
      data: PNG,
      bytes: Buffer.from(PNG, "base64").length,
    });
    if (!result.ok) throw new Error("expected image");
    expect(path.dirname(result.path)).toBe(scratch);
    expect(await fs.readFile(result.path)).toEqual(Buffer.from(PNG, "base64"));
    expect(await fs.readdir(workspace)).toEqual([]);
    expect(JSON.parse(String(request.mock.calls[0][1]?.body))).toEqual({
      model: MODEL,
      prompt: "a red apple",
      n: 1,
    });
    expect(request).toHaveBeenCalledOnce();
    expect(download).not.toHaveBeenCalled();
  });

  it("resolves reference support before any workspace bytes are read", async () => {
    const { bindings, generate, request } = await build({
      keys: { fal: "synthetic-key" },
    });
    const read = vi.spyOn(bindings.fs, "readBytes");
    expect(
      await generate({ prompt: "edit", references: ["/missing.png"] })
    ).toMatchObject({ ok: false, reason: "unavailable" });
    expect(read).not.toHaveBeenCalled();
    expect(request).not.toHaveBeenCalled();
    expect(await fs.readdir(scratch)).toEqual([]);
  });

  it("caps references before host reads and passes validated image data to the operation", async () => {
    await fs.writeFile(
      path.join(workspace, "reference.png"),
      Buffer.from(PNG, "base64")
    );
    const { bindings, generate, request } = await build({
      keys: { openrouter: "synthetic-key" },
    });
    const read = vi.spyOn(bindings.fs, "readBytes");
    const result = await generate({
      prompt: "edit",
      references: [
        ...Array<string>(16).fill("/reference.png"),
        "/must-not-read.png",
      ],
    });
    expect(result.ok).toBe(true);
    expect(read).toHaveBeenCalledTimes(16);
    expect(read.mock.calls.every(([value]) => value === "/reference.png")).toBe(
      true
    );
    const sent = JSON.parse(String(request.mock.calls[0][1]?.body));
    expect(sent.input_references).toEqual(
      Array(16).fill({
        type: "image_url",
        image_url: { url: `data:image/png;base64,${PNG}` },
      })
    );
    expect(sent).not.toHaveProperty("grida");
    expect(sent).not.toHaveProperty("references");
  });

  it("rejects an invalid reference without submitting or creating an output", async () => {
    const { generate, request } = await build({
      keys: { openrouter: "synthetic-key" },
    });
    expect(
      await generate({ prompt: "edit", references: ["/missing.png"] })
    ).toMatchObject({ ok: false, reason: "invalid_input" });
    expect(request).not.toHaveBeenCalled();
    expect(await fs.readdir(scratch)).toEqual([]);
  });

  it("keeps provider failures safe without logging details, retrying, or writing output", async () => {
    const sentinel = "synthetic-private-upstream-prompt-key";
    const logged = vi.spyOn(console, "error").mockImplementation(() => {});
    const { generate, request } = await build({
      keys: { openrouter: sentinel },
      request: async () => {
        throw Object.assign(new Error(sentinel), { responseBody: sentinel });
      },
    });
    const result = await generate({ prompt: sentinel });
    expect(result).toMatchObject({ ok: false, reason: "generation_failed" });
    expect(JSON.stringify(result)).not.toContain(sentinel);
    expect(JSON.stringify(logged.mock.calls)).not.toContain(sentinel);
    expect(request).toHaveBeenCalledOnce();
    expect(await fs.readdir(scratch)).toEqual([]);
  });

  it("does not fall through to another provider if the selected key disappears", async () => {
    let reads = 0;
    const { generate, request } = await build({
      get: async (id) =>
        id === "openrouter"
          ? ++reads <= 2
            ? "synthetic-key"
            : null
          : "other-key",
    });
    expect(await generate({ prompt: "x" })).toMatchObject({
      ok: false,
      reason: "generation_failed",
    });
    expect(request).not.toHaveBeenCalled();
  });

  it("returns a safe failure when key access breaks after capability advertisement", async () => {
    let reads = 0;
    const logged = vi.spyOn(console, "error").mockImplementation(() => {});
    const { generate, request } = await build({
      get: async () => {
        if (++reads === 1) return "synthetic-key";
        throw new Error("private-key-reader-detail");
      },
    });
    expect(await generate({ prompt: "x" })).toEqual({
      ok: false,
      reason: "generation_failed",
      message: "Image generation could not access its provider.",
    });
    expect(request).not.toHaveBeenCalled();
    expect(logged).not.toHaveBeenCalled();
    expect(await fs.readdir(scratch)).toEqual([]);
  });

  it("allows the same keyless host through scoped GG and persists only image data", async () => {
    const gg = new GridaGatewaySessionStore();
    gg.set({
      access_token: "synthetic-scoped-token",
      expires_at: Date.now() + 900_000,
    });
    const { generate, request } = await build({
      gg,
      request: async () =>
        Response.json({ images: [{ base64: PNG, media_type: "image/png" }] }),
    });
    const result = await generate({ prompt: "x" });
    expect(result.ok).toBe(true);
    expect(String(request.mock.calls[0][0])).toBe(
      "https://grida.test/api/v1/ai/images/generations"
    );
    expect(
      new Headers(request.mock.calls[0][1]?.headers).get("authorization")
    ).toBe("Bearer synthetic-scoped-token");
    expect(JSON.stringify(result)).not.toContain("synthetic-scoped-token");
    gg.clear();
    expect(await generate({ prompt: "x" })).toMatchObject({
      ok: false,
      reason: "unavailable",
    });
    expect(request).toHaveBeenCalledOnce();
  });

  it("reports scratch failure without leaking its path or provider result", async () => {
    const logged = vi.spyOn(console, "error").mockImplementation(() => {});
    const { generate, request } = await build({
      keys: { openrouter: "synthetic-key" },
    });
    await fs.rm(scratch, { recursive: true });
    await fs.writeFile(scratch, "occupied");
    const result = await generate({ prompt: "x" });
    expect(result).toMatchObject({
      ok: false,
      reason: "generation_failed",
      message: "Could not save the generated image to scratch.",
    });
    expect(JSON.stringify(result)).not.toContain(root);
    expect(logged).not.toHaveBeenCalled();
    expect(request).toHaveBeenCalledOnce();
  });
});
