import React from "react";
import styled from "@emotion/styled";
/**
 * `<SectionOneCommand>` ('section-one-command')
 * - [Open in Figma](https://figma.com/file/Gaznaw1QHppxvs9UkqNOb0?node-id=8266:64060)
 * - [Open in Grida](https://code.grida.co/files/Gaznaw1QHppxvs9UkqNOb0?node=8266:64060)
 *
 *
 * ---
 * @example
 * ```tsx
 * import React from "react";
 *
 * export default function () {
 *   return (
 *     <>
 *       👇 instanciate widget like below. 👇
 *       <SectionOneCommand/>
 *     </>
 *   )
 * }
 * ```
 * ---
 * @params {any} props - this widget does not requires props. you can pass custom dynamic props to the widget as you want (on typescript, it will raise type check issues).
 * ---
 * @preview
 * ![](https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/019c7944-1d68-458a-8d71-397a0cefa041)
 * ---
 * @remarks
 * @see {@link https://grida.co/docs} for more information.
 * ---
 * Code generated by grida.co | engine 0.0.1 (Apache-2.0) | Generated code under CC0 (public domain) *This code is free to use, modify, and redistribute. (aknowledgment is not required)*
 *
 *
 * ![Made with Grida](https://bridged-service-static.s3.us-west-1.amazonaws.com/branding/logo/32.png)
 * <!-- Info: Please do not remove this comment unless intended. removing this section will break grida integrations. -->
 * <!-- grida.meta.widget_declaration | engine : 0.0.1 | source : figma://Gaznaw1QHppxvs9UkqNOb0/8266:64060 -->
 */
export function SectionOneCommand() {
  return (
    <RootWrapperSectionOneCommand>
      <Bg>
        <E3 xmlns="http://www.w3.org/2000/svg">
          <path
            fill="rgb(37, 168, 144)"
            d="M209.609 46.6739C209.609 77.6979 120.024 212.304 88.9999 212.304C57.9759 212.304 0 96.9588 0 65.9348C0 34.9108 133.563 0 164.587 0C195.611 0 209.609 15.6499 209.609 46.6739Z"
          />
        </E3>
        <E2 xmlns="http://www.w3.org/2000/svg">
          <path
            fill="rgb(255, 0, 229)"
            d="M188.739 98.3043C188.739 129.328 76.4588 194.13 45.4348 194.13C14.4108 194.13 0 129.328 0 98.3043C0 67.2803 14.4108 0 45.4348 0C76.4588 0 188.739 67.2803 188.739 98.3043Z"
          />
        </E2>
        <E1 />
      </Bg>
      <ArtworkGroup>
        <TopDesign>
          <Rectangle787 />
          <Rectangle789 />
          <Rectangle788 />
          <PlatformIconsFigmaDefault>
            <Image71
              src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/c5ea3975-7eaf-43ad-86ee-ca985649370a"
              alt="image of Image71"
            />
          </PlatformIconsFigmaDefault>
        </TopDesign>
        <BottomCode>
          <ScreenShot20220806At4471
            src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/6c030df7-4192-4b4f-b643-e26d0befc1b4"
            alt="image of ScreenShot20220806At4471"
          />
          <Frame216>
            <Image65
              src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/1a8d9b36-3a06-4e12-9c7f-92265bd1a536"
              alt="image of Image65"
            />
            <Image65
              src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/99e4594d-3641-4371-9553-00e2c2e8ec9a"
              alt="image of Image66"
            />
          </Frame216>
        </BottomCode>
      </ArtworkGroup>
      <Section2HeadingAsH2>
        One command to add designs as a module to your existing projects.
      </Section2HeadingAsH2>
      <DescriptionLayout>
        <Section2DescriptionAsP>Be the Maestro.</Section2DescriptionAsP>
        <Section2DescriptionAsP_0001>
          You can import your design like a well-cded library, with full
          documentations.
          <br />
          We play the details // you play the orchestra.
        </Section2DescriptionAsP_0001>
      </DescriptionLayout>
      <Vector xmlns="http://www.w3.org/2000/svg">
        <path
          fill="white"
          d="M18 9.74017L16.4137 8.02346L10.125 14.8172L10.125 0L7.875 0L7.875 14.8172L1.5975 8.01129L0 9.74017L9 19.4803L18 9.74017Z"
        />
      </Vector>
      <CliLineArtwork
        src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/fc417ae8-65d0-45cd-972b-04fac8cb3a4e"
        alt="image of CliLineArtwork"
      />
    </RootWrapperSectionOneCommand>
  );
}

const RootWrapperSectionOneCommand = styled.div`
  min-height: 100vh;
  background: linear-gradient(-135deg, rgb(9, 4, 26), rgb(31, 5, 27));
  border-top-left-radius: 0px;
  border-top-right-radius: 0px;
  border-bottom-right-radius: 0px;
  border-bottom-left-radius: 0px;
  position: relative;
`;

const Bg = styled.div`
  width: 282px;
  height: 312px;
  border-top-left-radius: 0px;
  border-top-right-radius: 0px;
  border-bottom-right-radius: 0px;
  border-bottom-left-radius: 0px;
  position: absolute;
  left: calc((calc((50% + 3px)) - 141px));
  top: 284px;
  opacity: 0.5;
  filter: blur(82.61px);
`;

const E3 = styled.svg`
  width: 210px;
  height: 212px;
  position: absolute;
  left: calc((calc((50% + 36px)) - 105px));
  top: calc((calc((50% + 13px)) - 106px));
`;

const E2 = styled.svg`
  width: 189px;
  height: 194px;
  position: absolute;
  left: calc((calc((50% + -34px)) - 94px));
  top: calc((calc((50% + 9px)) - 97px));
`;

const E1 = styled.div`
  width: 112px;
  height: 112px;
  background-color: rgb(66, 0, 255);
  border-radius: 112px / 112px;
  position: absolute;
  left: calc((calc((50% + -2px)) - 56px));
  top: calc((calc((50% + 106px)) - 56px));
`;

const ArtworkGroup = styled.div`
  display: flex;
  justify-content: flex-start;
  flex-direction: column;
  align-items: center;
  border-top-left-radius: 0px;
  border-top-right-radius: 0px;
  border-bottom-right-radius: 0px;
  border-bottom-left-radius: 0px;
  box-sizing: border-box;
  position: absolute;
  left: calc((calc((50% + 3px)) - 114px));
  top: 284px;
  width: 228px;
  height: 312px;
`;

const TopDesign = styled.div`
  width: 228px;
  height: 156px;
  overflow: hidden;
  background-color: rgb(243, 243, 243);
  border: solid 1px rgba(0, 0, 0, 0.05);
  border-radius: 4px;
  position: relative;
  box-shadow: 0px 4px 24px rgba(0, 0, 0, 0.04);
`;

const Rectangle787 = styled.div`
  width: 61px;
  height: 107px;
  background-color: white;
  border-radius: 2px;
  position: absolute;
  left: 84px;
  top: 42px;
`;

const Rectangle789 = styled.div`
  width: 61px;
  height: 107px;
  background-color: white;
  border-radius: 2px;
  position: absolute;
  left: -22px;
  top: 42px;
`;

const Rectangle788 = styled.div`
  width: 61px;
  height: 107px;
  background-color: white;
  border-radius: 2px;
  position: absolute;
  left: 183px;
  top: 42px;
`;

const PlatformIconsFigmaDefault = styled.div`
  width: 32px;
  height: 32px;
  overflow: hidden;
  border-top-left-radius: 0px;
  border-top-right-radius: 0px;
  border-bottom-right-radius: 0px;
  border-bottom-left-radius: 0px;
  position: absolute;
  left: 98px;
  top: 62px;
`;

const Image71 = styled.img`
  object-fit: cover;
  position: absolute;
  left: 6px;
  top: 0px;
  right: 5px;
  bottom: 0px;
`;

const BottomCode = styled.div`
  width: 228px;
  height: 156px;
  overflow: hidden;
  background-color: rgb(30, 30, 30);
  border: solid 1px rgba(255, 255, 255, 0.05);
  border-radius: 4px;
  position: relative;
  box-shadow: 0px 4px 24px rgba(0, 0, 0, 0.12);
`;

const ScreenShot20220806At4471 = styled.img`
  width: 228px;
  height: 174px;
  object-fit: cover;
  position: absolute;
  left: 0px;
  top: -18px;
`;

const Frame216 = styled.div`
  display: flex;
  justify-content: center;
  flex-direction: row;
  align-items: flex-end;
  gap: 29px;
  border: solid 1px rgba(255, 255, 255, 0.1);
  border-radius: 9px;
  background-color: rgb(30, 30, 30);
  box-sizing: border-box;
  padding: 12px;
  position: absolute;
  top: 54px;
  right: 64px;
  width: 101px;
  height: 48px;
`;

const Image65 = styled.img`
  width: 24px;
  height: 24px;
  object-fit: cover;
`;

const Section2HeadingAsH2 = styled.h2`
  color: white;
  text-overflow: ellipsis;
  font-size: 40px;
  font-family: "Helvetica Neue", sans-serif;
  font-weight: 700;
  letter-spacing: -1px;
  line-height: 95%;
  text-align: center;
  width: 501px;
  position: absolute;
  left: calc((calc((50% + 1px)) - 251px));
  top: 99px;
  opacity: 0.9;
`;

const DescriptionLayout = styled.div`
  display: flex;
  justify-content: flex-start;
  flex-direction: column;
  align-items: center;
  border-top-left-radius: 0px;
  border-top-right-radius: 0px;
  border-bottom-right-radius: 0px;
  border-bottom-left-radius: 0px;
  box-sizing: border-box;
  position: absolute;
  left: calc((calc((50% + 3px)) - 274px));
  top: 650px;
  width: 548px;
  height: 81px;
`;

const Section2DescriptionAsP = styled.p`
  color: white;
  text-overflow: ellipsis;
  font-size: 16px;
  font-family: "Helvetica Neue", sans-serif;
  font-weight: 700;
  line-height: 167%;
  text-align: center;
  opacity: 0.8;
`;

const Section2DescriptionAsP_0001 = styled.p`
  color: white;
  text-overflow: ellipsis;
  font-size: 16px;
  font-family: "Helvetica Neue", sans-serif;
  font-weight: 400;
  line-height: 167%;
  text-align: center;
  opacity: 0.8;
`;

const Vector = styled.svg`
  width: 18px;
  height: 19px;
  position: absolute;
  left: calc((calc((50% + 0px)) - 9px));
  bottom: 39px;
`;

const CliLineArtwork = styled.img`
  width: 282px;
  height: 49px;
  object-fit: cover;
  position: absolute;
  left: calc((calc((50% + 3px)) - 141px));
  top: 415px;
`;
