import React from "react";
import styled from "@emotion/styled";
/**
 * `<SectionDemo>` ('section-demo')
 * - [Open in Figma](https://figma.com/file/Gaznaw1QHppxvs9UkqNOb0?node-id=8266:64061)
 * - [Open in Grida](https://code.grida.co/files/Gaznaw1QHppxvs9UkqNOb0?node=8266:64061)
 *
 *
 * ---
 * @example
 * ```tsx
 * import React from "react";
 *
 * export default function () {
 *   return (
 *     <>
 *       👇 instanciate widget like below. 👇
 *       <SectionDemo/>
 *     </>
 *   )
 * }
 * ```
 * ---
 * @params {any} props - this widget does not requires props. you can pass custom dynamic props to the widget as you want (on typescript, it will raise type check issues).
 * ---
 * @preview
 * ![](https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/0b0910fd-273f-4e6c-9dd2-31a7f2a7bf07)
 * ---
 * @remarks
 * @see {@link https://grida.co/docs} for more information.
 * ---
 * Code generated by grida.co | engine 0.0.1 (Apache-2.0) | Generated code under CC0 (public domain) *This code is free to use, modify, and redistribute. (aknowledgment is not required)*
 *
 *
 * ![Made with Grida](https://bridged-service-static.s3.us-west-1.amazonaws.com/branding/logo/32.png)
 * <!-- Info: Please do not remove this comment unless intended. removing this section will break grida integrations. -->
 * <!-- grida.meta.widget_declaration | engine : 0.0.1 | source : figma://Gaznaw1QHppxvs9UkqNOb0/8266:64061 -->
 */
export function SectionDemo() {
  return (
    <RootWrapperSectionDemo>
      <ReplayButton>
        <Replay>replay</Replay>
        <IconsMdiReplay src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/8ae07f02-e52b-4682-876b-bb5d539908d6" />
      </ReplayButton>
      <Demo>
        <Frame286>
          <ProjectsMyReactAppZsh>
            ~/projects/my-react-app -- zsh
          </ProjectsMyReactAppZsh>
        </Frame286>
      </Demo>
    </RootWrapperSectionDemo>
  );
}

const RootWrapperSectionDemo = styled.div`
  min-height: 100vh;
  background-color: white;
  border-top-left-radius: 0px;
  border-top-right-radius: 0px;
  border-bottom-right-radius: 0px;
  border-bottom-left-radius: 0px;
  position: relative;
`;

const ReplayButton = styled.div`
  display: flex;
  justify-content: center;
  flex-direction: row;
  align-items: center;
  gap: 8px;
  border-radius: 4px;
  box-sizing: border-box;
  padding: 10px 16px;
  position: absolute;
  left: calc((calc((50% + -4px)) - 62px));
  top: 840px;
  opacity: 0.8;
  width: 124px;
  height: 44px;
`;

const Replay = styled.span`
  color: rgba(0, 0, 0, 0.8);
  text-overflow: ellipsis;
  font-size: 18px;
  font-family: "Roboto Mono", monospace !important;
  font-weight: 400;
  text-align: left;
`;

const IconsMdiReplay = styled.img`
  width: 20px;
  height: 20px;
  object-fit: cover;
`;

const Demo = styled.div`
  display: flex;
  justify-content: flex-start;
  flex-direction: column;
  align-items: flex-start;
  gap: 32px;
  box-shadow: 0px 4px 32px rgba(0, 0, 0, 0.04);
  border: solid 1px rgba(0, 0, 0, 0.04);
  border-radius: 8px;
  background-color: white;
  box-sizing: border-box;
  position: absolute;
  left: 200px;
  top: 147px;
  right: 200px;
  height: 593px;
`;

const Frame286 = styled.div`
  display: flex;
  justify-content: center;
  flex-direction: row;
  align-items: center;
  gap: 10px;
  border-top-left-radius: 0px;
  border-top-right-radius: 0px;
  border-bottom-right-radius: 0px;
  border-bottom-left-radius: 0px;
  align-self: stretch;
  background-color: rgba(0, 0, 0, 0.05);
  box-sizing: border-box;
  padding: 4px 87px;
  flex-shrink: 0;
`;

const ProjectsMyReactAppZsh = styled.span`
  color: rgba(0, 0, 0, 0.3);
  text-overflow: ellipsis;
  font-size: 16px;
  font-family: "Helvetica Neue", sans-serif;
  font-weight: 400;
  line-height: 157%;
  text-align: center;
`;

const Ignore = styled.div`
  display: flex;
  justify-content: flex-start;
  flex-direction: column;
  align-items: flex-start;
  border-top-left-radius: 0px;
  border-top-right-radius: 0px;
  border-bottom-right-radius: 0px;
  border-bottom-left-radius: 0px;
  align-self: stretch;
  box-sizing: border-box;
  padding: 0px 40px;
  flex-shrink: 0;
`;

const GridaAddHttpsWwwFigmaComFileX7Rrk6RwWtZuNakmbMltvhNodeId9063A779 = styled.span`
  color: black;
  text-overflow: ellipsis;
  font-size: 16px;
  font-family: Monaco, sans-serif;
  font-weight: 400;
  text-align: left;
`;

const FetchingDesing = styled.span`
  color: black;
  text-overflow: ellipsis;
  font-size: 16px;
  font-family: Monaco, sans-serif;
  font-weight: 400;
  text-align: left;
`;

const GeneratingCode = styled.span`
  color: black;
  text-overflow: ellipsis;
  font-size: 16px;
  font-family: Monaco, sans-serif;
  font-weight: 400;
  text-align: left;
`;

const FetchingAssets = styled.span`
  color: black;
  text-overflow: ellipsis;
  font-size: 16px;
  font-family: Monaco, sans-serif;
  font-weight: 400;
  text-align: left;
`;

const ModuleAddedToSrcGridaHomeTsx = styled.span`
  color: black;
  text-overflow: ellipsis;
  font-size: 16px;
  font-family: Monaco, sans-serif;
  font-weight: 400;
  text-align: left;
`;

const ToUseThisModuleImportImportReactFromReactImportHomeFromGridaHome = styled.span`
  color: black;
  text-overflow: ellipsis;
  font-size: 16px;
  font-family: Monaco, sans-serif;
  font-weight: 400;
  text-align: left;
`;

const NaN = styled.span`
  color: black;
  text-overflow: ellipsis;
  font-size: 16px;
  font-family: Monaco, sans-serif;
  font-weight: 400;
  text-align: left;
`;
