import React from "react";
import styled from "@emotion/styled";
import { useTranslation } from "next-i18next";

/**
 * `<SectionOneCommand>` ('section-one-command')
 * - [Open in Figma](https://figma.com/file/Gaznaw1QHppxvs9UkqNOb0?node-id=8266:64060)
 * - [Open in Grida](https://code.grida.co/files/Gaznaw1QHppxvs9UkqNOb0?node=8266:64060)
 *
 *
 * ---
 * @example
 * ```tsx
 * import React from "react";
 *
 * export default function () {
 *   return (
 *     <>
 *       👇 instanciate widget like below. 👇
 *       <SectionOneCommand/>
 *     </>
 *   )
 * }
 * ```
 * ---
 * @params {any} props - this widget does not requires props. you can pass custom dynamic props to the widget as you want (on typescript, it will raise type check issues).
 * ---
 * @preview
 * ![](https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/019c7944-1d68-458a-8d71-397a0cefa041)
 * ---
 * @remarks
 * @see {@link https://grida.co/docs} for more information.
 * ---
 * Code generated by grida.co | engine 0.0.1 (Apache-2.0) | Generated code under CC0 (public domain) *This code is free to use, modify, and redistribute. (aknowledgment is not required)*
 *
 *
 * ![Made with Grida](https://bridged-service-static.s3.us-west-1.amazonaws.com/branding/logo/32.png)
 * <!-- Info: Please do not remove this comment unless intended. removing this section will break grida integrations. -->
 * <!-- grida.meta.widget_declaration | engine : 0.0.1 | source : figma://Gaznaw1QHppxvs9UkqNOb0/8266:64060 -->
 */
export function SectionOneCommand() {
  const { t } = useTranslation("page-cli");

  return (
    <RootWrapperSectionOneCommand>
      <Bg>
        <E3 xmlns="http://www.w3.org/2000/svg">
          <path
            fill="rgb(37, 168, 144)"
            d="M209.609 46.6739C209.609 77.6979 120.024 212.304 88.9999 212.304C57.9759 212.304 0 96.9588 0 65.9348C0 34.9108 133.563 0 164.587 0C195.611 0 209.609 15.6499 209.609 46.6739Z"
          />
        </E3>
        <E2 xmlns="http://www.w3.org/2000/svg">
          <path
            fill="rgb(255, 0, 229)"
            d="M188.739 98.3043C188.739 129.328 76.4588 194.13 45.4348 194.13C14.4108 194.13 0 129.328 0 98.3043C0 67.2803 14.4108 0 45.4348 0C76.4588 0 188.739 67.2803 188.739 98.3043Z"
          />
        </E2>
        <E1 />
      </Bg>
      <ArtworkGroup>
        <TopDesign src="/cli/top-design.png" />
        <BottomCode src="/cli/bottom-code.png" />
      </ArtworkGroup>
      <Section2HeadingAsH2>{t("section/command.heading")}</Section2HeadingAsH2>
      <DescriptionLayout>
        <Tagline>{t("section/command.tagline")}</Tagline>
        <Description
          dangerouslySetInnerHTML={{
            __html: t("section/command.description"),
          }}
        />
      </DescriptionLayout>
      <Vector xmlns="http://www.w3.org/2000/svg">
        <path
          fill="white"
          d="M18 9.74017L16.4137 8.02346L10.125 14.8172L10.125 0L7.875 0L7.875 14.8172L1.5975 8.01129L0 9.74017L9 19.4803L18 9.74017Z"
        />
      </Vector>
      <CliLineContainer>
        <CliLine />
      </CliLineContainer>
    </RootWrapperSectionOneCommand>
  );
}

const RootWrapperSectionOneCommand = styled.div`
  min-height: 100vh;
  background: linear-gradient(-135deg, rgb(9, 4, 26), rgb(31, 5, 27));
  border-top-left-radius: 0px;
  border-top-right-radius: 0px;
  border-bottom-right-radius: 0px;
  border-bottom-left-radius: 0px;
  position: relative;
`;

const Bg = styled.div`
  width: 282px;
  height: 312px;
  border-top-left-radius: 0px;
  border-top-right-radius: 0px;
  border-bottom-right-radius: 0px;
  border-bottom-left-radius: 0px;
  position: absolute;
  left: calc((calc((50% + 3px)) - 141px));
  top: 284px;
  opacity: 0.5;
  filter: blur(82.61px);
`;

const E3 = styled.svg`
  width: 210px;
  height: 212px;
  position: absolute;
  left: calc((calc((50% + 36px)) - 105px));
  top: calc((calc((50% + 13px)) - 106px));
`;

const E2 = styled.svg`
  width: 189px;
  height: 194px;
  position: absolute;
  left: calc((calc((50% + -34px)) - 94px));
  top: calc((calc((50% + 9px)) - 97px));
`;

const E1 = styled.div`
  width: 112px;
  height: 112px;
  background-color: rgb(66, 0, 255);
  border-radius: 112px / 112px;
  position: absolute;
  left: calc((calc((50% + -2px)) - 56px));
  top: calc((calc((50% + 106px)) - 56px));
`;

const ArtworkGroup = styled.div`
  display: flex;
  justify-content: flex-start;
  flex-direction: column;
  align-items: center;
  border-top-left-radius: 0px;
  border-top-right-radius: 0px;
  border-bottom-right-radius: 0px;
  border-bottom-left-radius: 0px;
  box-sizing: border-box;
  position: absolute;
  left: calc((calc((50% + 3px)) - 114px));
  top: 284px;
  width: 228px;
  height: 312px;
`;

const TopDesign = styled.img`
  width: 228px;
  height: 156px;
  overflow: hidden;
  background-color: rgb(243, 243, 243);
  border: solid 1px rgba(0, 0, 0, 0.05);
  border-radius: 4px;
  position: relative;
  box-shadow: 0px 4px 24px rgba(0, 0, 0, 0.04);
`;

const BottomCode = styled.img`
  width: 228px;
  height: 156px;
  overflow: hidden;
  background-color: rgb(30, 30, 30);
  border: solid 1px rgba(255, 255, 255, 0.05);
  border-radius: 4px;
  position: relative;
  box-shadow: 0px 4px 24px rgba(0, 0, 0, 0.12);
`;

const Section2HeadingAsH2 = styled.h2`
  color: white;
  text-overflow: ellipsis;
  font-size: 40px;
  font-family: "Helvetica Neue", sans-serif;
  font-weight: 700;
  letter-spacing: -1px;
  line-height: 95%;
  text-align: center;
  width: 501px;
  position: absolute;
  left: calc((calc((50% + 1px)) - 251px));
  top: 99px;
  opacity: 0.9;
`;

const DescriptionLayout = styled.div`
  display: flex;
  justify-content: flex-start;
  flex-direction: column;
  align-items: center;
  border-top-left-radius: 0px;
  border-top-right-radius: 0px;
  border-bottom-right-radius: 0px;
  border-bottom-left-radius: 0px;
  box-sizing: border-box;
  position: absolute;
  left: calc((calc((50% + 3px)) - 274px));
  top: 650px;
  width: 100%;
  max-width: 548px;
  height: 81px;
`;

const Tagline = styled.p`
  color: white;
  text-overflow: ellipsis;
  font-size: 16px;
  font-family: "Helvetica Neue", sans-serif;
  font-weight: 700;
  line-height: 167%;
  text-align: center;
  opacity: 0.8;
`;

const Description = styled.p`
  color: white;
  text-overflow: ellipsis;
  font-size: 16px;
  font-family: "Helvetica Neue", sans-serif;
  font-weight: 400;
  line-height: 167%;
  text-align: center;
  opacity: 0.8;
  max-width: fit-content;
`;

const Vector = styled.svg`
  width: 18px;
  height: 19px;
  position: absolute;
  left: calc((calc((50% + 0px)) - 9px));
  bottom: 39px;
`;

const CliLineContainer = styled.div`
  position: absolute;
  left: calc((calc((50% + 3px)) - 141px));
  top: 415px;
`;

function CliLine() {
  return (
    <RootWrapperCliLine>
      <Icon>➜</Icon>
      <Command>grida add</Command>
      <Arg>
        https://www.figma.com/file/x7RRK6RwWtZuNakmbMLTVH/?node-id=906%3A779
      </Arg>
    </RootWrapperCliLine>
  );
}

const RootWrapperCliLine = styled.div`
  word-break: keep-all;
  display: flex;
  justify-content: flex-start;
  flex-direction: row;
  align-items: center;
  flex: none;
  gap: 12px;
  box-shadow: 0px 4px 32px 0px rgba(0, 0, 0, 0.04);
  border: solid 1px rgba(0, 0, 0, 0.1);
  border-radius: 8px;
  height: 50px;
  width: 282px;
  overflow: scroll;
  background-color: white;
  box-sizing: border-box;
  padding: 0px 21px;
  ::-webkit-scrollbar {
    display: none;
  }
  -ms-overflow-style: none; /* IE and Edge */
  scrollbar-width: none; /* Firefox */
`;

const Icon = styled.span`
  color: rgba(0, 0, 0, 0.5);
  text-overflow: ellipsis;
  font-size: 12px;
  font-family: "Roboto Mono", sans-serif;
  font-weight: 400;
  text-align: left;
`;

const Command = styled.span`
  flex-shrink: 0;
  color: black;
  text-overflow: ellipsis;
  font-size: 12px;
  font-family: "Roboto Mono", sans-serif;
  font-weight: 500;
  text-align: left;
`;

const Arg = styled.span`
  flex-shrink: 0;
  color: rgba(0, 0, 0, 0.5);
  text-overflow: ellipsis;
  font-size: 12px;
  font-family: "Roboto Mono", sans-serif;
  font-weight: 400;
  text-align: left;
`;
