[package]
name = "grida"
version = "0.0.0"
license = "Apache-2.0"
description = "reserved for future use by grida"
edition = "2021"


[dependencies]
cg = { path = "../grida-canvas" }

[features]
default = []
