"use server";

/**
 * AI image *generation* action — text → new pixels via the Vercel AI
 * SDK image-model interface, with the generated bytes uploaded to the
 * Library bucket and a row inserted in `object`.
 */

import {
  generateImage,
  type GeneratedFile,
  type GenerateImageResult,
  type ImageModel,
} from "ai";
import { v4 } from "uuid";
import mime from "mime-types";
import imageSize from "image-size";
import { service_role } from "@/lib/supabase/server";
import ai from "@/lib/ai";
import { methods, withAiAuth, type AiActionResult } from "@/lib/ai/server";

export type GenerateAiImageInput = {
  prompt: string;
  width?: number;
  height?: number;
  aspect_ratio?: ai.image.AspectRatioString;
  model: ai.image.ProviderModel | ai.image.ImageModelId;
  /** Verified org id — falls back to header / inferred via supabase auth. */
  organizationId?: number;
};

export type GenerateAiImageData = {
  object: {
    id: string;
    bytes: number;
    width: number;
    height: number;
    mimetype: string;
  };
  width: number;
  height: number;
  publicUrl: string;
  timestamp: string;
  modelId: string;
};

export type GenerateAiImageResponse = AiActionResult<GenerateAiImageData>;

function computeCostMills(
  card: ai.image.ImageModelCard,
  request: { n: number; width?: number; height?: number }
): number {
  const n = Math.max(1, request.n);
  switch (card.pricing.type) {
    case "per_image_flat":
      return ai.toMills(card.pricing.usd * n);
    case "per_image_tiered": {
      const w = request.width;
      const h = request.height;
      const tierKey = w && h ? `medium/${w}x${h}` : undefined;
      const perImage =
        (tierKey && card.pricing.tiers[tierKey]) || card.avg_cost_usd;
      return ai.toMills(perImage * n);
    }
    case "per_token":
      return ai.toMills(card.avg_cost_usd * n);
  }
}

export async function generateAiImage(
  input: GenerateAiImageInput
): Promise<GenerateAiImageResponse> {
  const model = methods.getSDKImageModel(input.model);
  if (!model) {
    return {
      success: false,
      code: "bad_request",
      message: "invalid model",
      status: 400,
    };
  }

  return withAiAuth(
    "ai/image/generate",
    input.organizationId,
    async (organizationId) => {
      const costMills = computeCostMills(model.card, {
        n: 1,
        width: input.width,
        height: input.height,
      });

      const generation = await generateImageWithSize({
        prompt: input.prompt,
        width: input.width,
        height: input.height,
        aspect_ratio: input.aspect_ratio,
        model: model.model,
        organizationId,
        costMills,
      });

      const meta = generation.responses[0];
      const { width, height } = imageSize(generation.image.uint8Array);
      const { object, publicUrl } = await uploadGeneratedToLibrary({
        request: {
          model: model.card.id,
          prompt: input.prompt,
          width,
          height,
        },
        file: generation.image,
      });

      return {
        object,
        publicUrl,
        width,
        height,
        modelId: meta.modelId,
        timestamp: meta.timestamp.toISOString(),
      } satisfies GenerateAiImageData;
    }
  );
}

async function uploadGeneratedToLibrary({
  file,
  request,
}: {
  file: GeneratedFile;
  request: {
    model: ai.image.ImageModelId;
    prompt: string;
    width: number;
    height: number;
  };
}) {
  // service_role for both storage upload and `object` insert — the
  // `object` table has RLS that an unauthed/RLS-restricted user client
  // can't satisfy for AI-generated rows. The original route did the
  // same; the type annotation lied (declared `createLibraryClient` but
  // passed service_role at runtime).
  const client = service_role.library;
  const { mediaType, uint8Array } = file;

  const ext = mime.extension(mediaType);
  const name = v4();
  const folder = "generated";
  const path = `${folder}/${name}${ext ? `.${ext}` : ""}`;

  const { data: uploaded, error: upload_err } = await client.storage
    .from("library")
    .upload(path, uint8Array, {
      contentType: mediaType,
    });

  if (upload_err) throw new Error(upload_err.message);

  const { data: object, error: object_err } = await client
    .from("object")
    .insert({
      id: uploaded.id,
      bytes: uint8Array.length,
      category: "generated",
      path: uploaded.path,
      mimetype: mediaType,
      generator: request.model,
      prompt: request.prompt,
      width: request.width,
      height: request.height,
      transparency: false,
    })
    .select()
    .single();

  if (object_err) throw new Error(object_err.message);

  const publicUrl = client.storage.from("library").getPublicUrl(object.path)
    .data.publicUrl;

  return { object, publicUrl };
}

async function generateImageWithSize({
  model,
  prompt,
  width,
  height,
  aspect_ratio,
  organizationId,
  costMills,
}: {
  model: ImageModel;
  prompt: string;
  width?: number;
  height?: number;
  aspect_ratio?: ai.image.AspectRatioString;
  organizationId: number;
  costMills: number;
}): Promise<GenerateImageResult> {
  const size: ai.image.SizeString | undefined =
    width && height ? `${width}x${height}` : undefined;

  return await generateImage({
    model,
    prompt,
    size,
    aspectRatio: aspect_ratio,
    n: 1,
    providerOptions: {
      grida: {
        organizationId,
        feature: "ai/image/generate",
        costMills,
      },
    },
  });
}
