import { describe, expect, it, vi } from "vitest";
import type { MediaItem } from "@grida/daemon";
import type { MediaPersistence } from "@grida/daemon/server";
import { GeneratedMediaPersistence } from "./generated-media-persistence";

const generated = {
  base64: "Z2xURg==",
  file_name: "model.glb",
  media_type: "model/gltf-binary",
};

const stored: MediaItem = {
  id: "7ccb8e68-a201-40d9-a793-44de9e6c6fc6",
  file_name: "model.glb",
  media_type: "model/gltf-binary",
  byte_size: 4,
  created_at: 1,
};

describe("GeneratedMediaPersistence", () => {
  it("derives only format-consistent neutral image and video filenames", () => {
    expect(GeneratedMediaPersistence.fileName("image", 0, "image/png")).toBe(
      "image-1.png"
    );
    expect(GeneratedMediaPersistence.fileName("image", 1, "image/jpeg")).toBe(
      "image-2.jpg"
    );
    expect(
      GeneratedMediaPersistence.fileName("video", 0, "video/quicktime")
    ).toBe("video-1.mov");
    expect(
      GeneratedMediaPersistence.fileName("video", 0, "application/json")
    ).toBeUndefined();
    expect(
      GeneratedMediaPersistence.fileName("video", -1, "video/mp4")
    ).toBeUndefined();
  });

  it("saves exact generated bytes and format metadata", async () => {
    const save = vi.fn<MediaPersistence["save"]>().mockResolvedValue(stored);

    await expect(
      GeneratedMediaPersistence.save({ save }, generated)
    ).resolves.toEqual(stored);
    expect(save).toHaveBeenCalledWith({
      file_name: "model.glb",
      media_type: "model/gltf-binary",
      bytes: Buffer.from("glTF"),
    });
  });

  it("omits persistence when the host did not provide a store", async () => {
    await expect(
      GeneratedMediaPersistence.save(null, generated)
    ).resolves.toBeUndefined();
  });

  it("uses a generic warning and preserves generation when save fails", async () => {
    const save = vi
      .fn<MediaPersistence["save"]>()
      .mockRejectedValue(new Error("/private/user/media/model.glb: EACCES"));
    const warning = vi.spyOn(console, "warn").mockImplementation(() => {});

    await expect(
      GeneratedMediaPersistence.save({ save }, generated)
    ).resolves.toBeUndefined();
    expect(warning).toHaveBeenCalledWith(
      "[grida-agent] generated media could not be saved"
    );
    expect(warning.mock.calls.flat().join(" ")).not.toContain("/private/user");

    warning.mockRestore();
  });
});
