/**
 * Best-effort persistence for generated binary media.
 *
 * Generation and persistence have deliberately different failure semantics:
 * provider output is still useful when the optional host media store is
 * unavailable, so a store failure is logged without exposing its path/error
 * and the original generated bytes continue to the caller.
 */

import type { MediaItem } from "@grida/daemon";
import type { MediaPersistence } from "@grida/daemon/server";

type GeneratedMedia = {
  base64: string;
  file_name: string;
  media_type: string;
};

type GeneratedMediaKind = "image" | "video";

const FILE_EXTENSIONS: Readonly<Record<string, string>> = {
  "image/png": "png",
  "image/jpeg": "jpg",
  "image/webp": "webp",
  "image/gif": "gif",
  "image/avif": "avif",
  "image/bmp": "bmp",
  "image/tiff": "tif",
  "image/heic": "heic",
  "image/heif": "heif",
  "image/svg+xml": "svg",
  "video/mp4": "mp4",
  "video/webm": "webm",
  "video/quicktime": "mov",
  "video/x-matroska": "mkv",
  "video/mpeg": "mpg",
  "video/ogg": "ogv",
  "video/x-msvideo": "avi",
};

export namespace GeneratedMediaPersistence {
  /**
   * Derive a format-consistent, single-segment name without prompts, provider
   * filenames, model ids, or other foreign input. Unknown formats stay
   * generated but are not offered to the durable store: inventing an extension
   * would make the stored descriptor dishonest.
   */
  export function fileName(
    kind: GeneratedMediaKind,
    outputIndex: number,
    mediaType: string
  ): string | undefined {
    if (!Number.isSafeInteger(outputIndex) || outputIndex < 0) return undefined;
    const extension = FILE_EXTENSIONS[mediaType.toLowerCase()];
    if (!extension) return undefined;
    return `${kind}-${outputIndex + 1}.${extension}`;
  }

  export async function save(
    media: MediaPersistence | null | undefined,
    generated: GeneratedMedia
  ): Promise<MediaItem | undefined> {
    if (!media) return undefined;

    try {
      return await media.save({
        file_name: generated.file_name,
        media_type: generated.media_type,
        bytes: Buffer.from(generated.base64, "base64"),
      });
    } catch {
      // GRIDA-SEC-004 — do not reflect the native root, filename-bearing Node
      // error, or other host filesystem details into logs available to the
      // renderer. Persistence is optional; generation itself already won.
      console.warn("[grida-agent] generated media could not be saved");
      return undefined;
    }
  }
}
