/**
 * GRIDA-SEC-004 — `/images/generate` route (BYOK image generation, #908).
 *
 * Native host image generation. The route resolves a curated model through
 * the shared image operation and returns generated bytes plus optional host
 * persistence receipts. Provider credentials remain inside the operation.
 *
 * Security contract (reviewed):
 *   - Reads `_getKey` internally (legal — sidecar only). The response carries
 *     base64 image bytes + provider id only: never the key, never the raw
 *     upstream JSON.
 *   - `model_id` is a closed catalog lookup (curated `listed` cards only) and
 *     `provider` is `oneOf` the fixed image providers — there is NO
 *     user-supplied base URL, so this opens no new egress beyond the three
 *     fixed provider hosts (unlike the endpoint routes, issue #806).
 *
 * Billing contract (#908, Phase 4 + GRIDA-SEC-006): the BYOK arms NEVER
 * enter the web Grida-billed image seam (`editor/lib/ai/server.ts`) — the
 * user's own key pays the provider directly, no Grida credit is metered,
 * and this sidecar route never sets the WEB seam's billing trigger. The
 * `gg` hosted arm is not a billing leak: its billing happens
 * server-side at the hosted endpoint (Bearer session token; the seam
 * gates + meters there), never in this process.
 */

import type { Hono } from "hono";
import { ImageClient } from "@grida/ai";
import type { MediaPersistence, SecretsStore } from "@grida/daemon/server";
import type { ModelCatalogStore } from "../../providers/model-catalog";
import {
  ImageModelUnavailableError,
  resolveImageModel,
} from "../../providers/resolve-image";
import { mediaGenerationError } from "./media-generation-errors";
import { body, v } from "@grida/daemon/server";
import type { ProviderHttp } from "../../providers/http";
import type { ImageGeneratedImage } from "../../protocol/images";
import { GeneratedMediaPersistence } from "./generated-media-persistence";

const IMAGE_PROVIDERS = ["vercel", "fal", "openrouter", "gg"] as const;

export type ImagesRoutesDeps = {
  secrets: SecretsStore;
  media?: MediaPersistence | null;
  /** Image catalogue for resolution; absent ⇒ the bundled one. */
  catalog?: ModelCatalogStore;
  // GRIDA-GG: provider — the optional hosted image arm.
  /** GRIDA-SEC-006 — hosted provider deps; absent ⇒ grida never resolves. */
  gg?: import("../../providers/gg-session").GridaGatewaySessionStore;
  gg_base_url?: string;
  provider_http?: ProviderHttp;
};

export function registerImagesRoutes(app: Hono, deps: ImagesRoutesDeps) {
  const { secrets, gg, gg_base_url, provider_http, catalog } = deps;

  app.post("/images/generate", async (c) => {
    const r = await body(c, {
      model_id: v.string,
      prompt: v.string,
      provider: v.optional(v.oneOf(IMAGE_PROVIDERS)),
      width: v.optional(v.number),
      height: v.optional(v.number),
      aspect_ratio: v.optional(v.string),
      n: v.optional(v.number),
      seed: v.optional(v.number),
      quality: v.optional(v.string),
      background: v.optional(
        v.oneOf(["auto", "opaque", "transparent"] as const)
      ),
    });
    if (!r.ok) return r.res;
    const {
      model_id,
      prompt,
      provider,
      width,
      height,
      aspect_ratio,
      n,
      seed,
      quality,
      background,
    } = r.data;

    let resolved;
    try {
      resolved = await resolveImageModel(
        { secrets, gg, gg_base_url, provider_http, catalog },
        model_id,
        { ...(provider ? { explicit: provider } : {}), background }
      );
    } catch (e) {
      if (e instanceof ImageModelUnavailableError) {
        return c.json(
          { error: e.message, code: e.code, model_id: e.model_id },
          400
        );
      }
      return c.json({ error: "image generation failed", model_id }, 502);
    }

    const size =
      width && height
        ? (`${Math.round(width)}x${Math.round(height)}` as `${number}x${number}`)
        : undefined;

    let generation;
    try {
      generation = await resolved.generate({
        prompt,
        n: n ?? 1,
        ...(size ? { size } : {}),
        ...(aspect_ratio
          ? { aspect_ratio: aspect_ratio as `${number}:${number}` }
          : {}),
        ...(seed !== undefined ? { seed } : {}),
        ...(quality ? { quality } : {}),
        signal: c.req.raw.signal,
      });
    } catch (e) {
      if (e instanceof ImageClient.Failure && e.code === "invalid_input") {
        return c.json({ error: "invalid image input", code: e.code }, 400);
      }
      return mediaGenerationError(c, {
        error:
          e instanceof ImageClient.Failure
            ? e
            : new ImageClient.Failure("generation_failed"),
        scope: "agent-host-images",
        label: "image generation failed",
        model_id,
        provider_id: resolved.provider_id,
      });
    }

    const images: ImageGeneratedImage[] = [];
    for (const [index, generated] of generation.images.entries()) {
      const image = {
        base64: Buffer.from(generated.data).toString("base64"),
        media_type: generated.media_type,
      };
      const fileName = GeneratedMediaPersistence.fileName(
        "image",
        index,
        image.media_type
      );
      const storedMedia = fileName
        ? await GeneratedMediaPersistence.save(deps.media, {
            ...image,
            file_name: fileName,
          })
        : undefined;
      images.push({
        ...image,
        ...(storedMedia ? { stored_media: storedMedia } : {}),
      });
    }

    return c.json({
      model_id: resolved.model_id,
      provider_id: resolved.provider_id,
      images,
    });
  });
}
