import { beforeEach, describe, expect, it, vi } from "vitest";
import { Hono } from "hono";
import type { MediaItem } from "@grida/daemon";
import type { MediaPersistence, SecretsStore } from "@grida/daemon/server";
import type {
  ThreeDGenerateRequest,
  ThreeDGeneratedGlb,
} from "../../protocol/three-d";

const generate = vi.hoisted(() =>
  vi.fn<
    (
      request: ThreeDGenerateRequest,
      signal?: AbortSignal
    ) => Promise<ThreeDGeneratedGlb>
  >()
);
vi.mock("../../providers/fal-three-d", () => ({
  FalThreeDProvider: class {
    generate = generate;
  },
}));

import { registerThreeDRoutes } from "./three-d";

function fakeSecrets(keys: Record<string, string>): SecretsStore {
  return {
    _getKey: async (id: string) => keys[id] ?? null,
  } as unknown as SecretsStore;
}

function appWith(keys: Record<string, string>, media?: MediaPersistence) {
  const app = new Hono();
  registerThreeDRoutes(app, { secrets: fakeSecrets(keys), media });
  return app;
}

function post(app: Hono, payload: unknown) {
  return app.request("/three-d/generate", {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify(payload),
  });
}

beforeEach(() => generate.mockReset());

describe("POST /three-d/generate", () => {
  it("accepts a closed text model, returns the GLB, and saves it", async () => {
    const stored: MediaItem = {
      id: "7ccb8e68-a201-40d9-a793-44de9e6c6fc6",
      file_name: "model.glb",
      media_type: "model/gltf-binary",
      byte_size: 4,
      created_at: 1,
    };
    const save = vi.fn<MediaPersistence["save"]>().mockResolvedValue(stored);
    generate.mockResolvedValueOnce({
      base64: "Z2xURg==",
      media_type: "model/gltf-binary",
      file_name: "model.glb",
    });
    const res = await post(appWith({ fal: "fal-key" }, { save }), {
      model_id: "fal-ai/hunyuan-3d/v3.1/pro/text-to-3d",
      prompt: "  a brass robot  ",
    });

    expect(res.status).toBe(200);
    expect(await res.json()).toEqual({
      model_id: "fal-ai/hunyuan-3d/v3.1/pro/text-to-3d",
      provider_id: "fal",
      glb: {
        base64: "Z2xURg==",
        media_type: "model/gltf-binary",
        file_name: "model.glb",
      },
      stored_media: stored,
    });
    expect(save).toHaveBeenCalledWith({
      file_name: "model.glb",
      media_type: "model/gltf-binary",
      bytes: Buffer.from("glTF"),
    });
    expect(generate).toHaveBeenCalledWith(
      {
        model_id: "fal-ai/hunyuan-3d/v3.1/pro/text-to-3d",
        prompt: "a brass robot",
      },
      expect.any(AbortSignal)
    );
  });

  it("still returns generated bytes when persistence fails", async () => {
    generate.mockResolvedValueOnce({
      base64: "Z2xURg==",
      media_type: "model/gltf-binary",
      file_name: "model.glb",
    });
    const save = vi
      .fn<MediaPersistence["save"]>()
      .mockRejectedValue(new Error("private path detail"));
    const warning = vi.spyOn(console, "warn").mockImplementation(() => {});

    const res = await post(appWith({ fal: "fal-key" }, { save }), {
      model_id: "fal-ai/hunyuan-3d/v3.1/pro/text-to-3d",
      prompt: "robot",
    });

    expect(res.status).toBe(200);
    expect(await res.json()).toEqual({
      model_id: "fal-ai/hunyuan-3d/v3.1/pro/text-to-3d",
      provider_id: "fal",
      glb: {
        base64: "Z2xURg==",
        media_type: "model/gltf-binary",
        file_name: "model.glb",
      },
    });
    expect(warning).toHaveBeenCalledWith(
      "[grida-agent] generated media could not be saved"
    );
    expect(warning.mock.calls.flat().join(" ")).not.toContain("private path");
    warning.mockRestore();
  });

  it("admits one memory-heavy 3D generation at a time and releases the slot", async () => {
    const glb: ThreeDGeneratedGlb = {
      base64: "Z2xURg==",
      media_type: "model/gltf-binary",
      file_name: "model.glb",
    };
    let finishFirst!: (value: ThreeDGeneratedGlb) => void;
    generate
      .mockImplementationOnce(
        async () =>
          await new Promise<ThreeDGeneratedGlb>((resolve) => {
            finishFirst = resolve;
          })
      )
      .mockResolvedValueOnce(glb);
    const app = appWith({ fal: "fal-key" });
    const payload = {
      model_id: "fal-ai/hunyuan-3d/v3.1/pro/text-to-3d",
      prompt: "robot",
    };

    const first = post(app, payload);
    await vi.waitFor(() => expect(generate).toHaveBeenCalledOnce());

    const concurrent = await post(app, payload);
    expect(concurrent.status).toBe(429);
    expect(await concurrent.json()).toEqual({
      error: "another 3D generation is already in progress",
      code: "three_d_generation_busy",
    });
    expect(generate).toHaveBeenCalledOnce();

    finishFirst(glb);
    expect((await first).status).toBe(200);
    expect((await post(app, payload)).status).toBe(200);
    expect(generate).toHaveBeenCalledTimes(2);
  });

  it("rejects unknown ids, missing fal keys, and mismatched inputs", async () => {
    expect(
      (
        await post(appWith({ fal: "fal-key" }), {
          model_id: "fal-ai/not-real",
          prompt: "x",
        })
      ).status
    ).toBe(400);
    expect(
      (
        await post(appWith({}), {
          model_id: "fal-ai/hunyuan-3d/v3.1/pro/text-to-3d",
          prompt: "x",
        })
      ).status
    ).toBe(400);
    expect(
      (
        await post(appWith({ fal: "fal-key" }), {
          model_id: "fal-ai/trellis-2",
          prompt: "wrong modality",
        })
      ).status
    ).toBe(400);
    expect(generate).not.toHaveBeenCalled();
  });

  it("bounds image input and accepts only the closed media types", async () => {
    const badMime = await post(appWith({ fal: "fal-key" }), {
      model_id: "fal-ai/trellis-2",
      image: { base64: "AAAA", media_type: "image/svg+xml" },
    });
    const badBase64 = await post(appWith({ fal: "fal-key" }), {
      model_id: "fal-ai/trellis-2",
      image: { base64: "not base64", media_type: "image/png" },
    });
    expect(badMime.status).toBe(400);
    expect(badBase64.status).toBe(400);
  });
});
