export const formcollection_sample_001_the_bundle = {
  brand: {
    name: "The Bundle",
    logo: "/templates/sample-brand-the-bundle/logo.png",
  },
  featured: {
    h1: "The Bundle",
    p: "A collection of events and meetups for developers and designers.",
    media: {
      $id: "media",
      type: "video",
      src: "https://player.vimeo.com/progressive_redirect/playback/860123788/rendition/1080p/file.mp4?loc=external&log_user=0&signature=ac9c2e0d2e367d8a31af6490edad8c1f7bae87d085c4f3909773a7ca5a129cb6",
    },
  },
  listheader: { text: "Upcoming Events" },
  tags: [
    "Apple",
    "Banana",
    "Carrot",
    "Dog",
    "Elephant",
    "Flower",
    "Giraffe",
    "House",
    "Igloo",
    "Jacket",
    "Kite",
    "Lion",
    "Monkey",
    "Nurse",
    "Orange",
    "Piano",
    "Queen",
  ],
  events: [
    {
      date: "24.1.02",
      attendees: 200,
      title: "Tech meetup",
      cta: "register now",
      status: "Opens 1:11",
      image: "/templates/sample-brand-the-bundle/collection/001.png",
      tags: ["Apple", "Banana"],
    },
    {
      date: "15.2.02",
      attendees: 150,
      title: "AI Conference",
      cta: "sign up today",
      status: "Opens 2:00",
      image: "/templates/sample-brand-the-bundle/collection/002.png",
      tags: ["Apple", "Banana"],
    },
    {
      date: "03.3.02",
      attendees: 300,
      title: "Blockchain Expo",
      cta: "join now",
      status: "Opens 3:30",
      image: "/templates/sample-brand-the-bundle/collection/003.png",
      tags: ["Apple", "Banana"],
    },
    {
      date: "10.4.02",
      attendees: 250,
      title: "Cybersecurity Summit",
      cta: "reserve your spot",
      status: "Opens 4:00",
      image: "/templates/sample-brand-the-bundle/collection/004.png",
      tags: ["Apple", "Banana"],
    },
    // {
    //   date: "22.5.02",
    //   attendees: 180,
    //   title: "Cloud Computing Workshop",
    //   cta: "get tickets",
    //   status: "Opens 5:15",
    //   image: "/bundle-abstract/004.png",
    // },
  ],
} as const;

export const formcollection_sample_002_endura_sports = {
  brand: {
    name: "Endura Sports",
    tagline: "Connecting You with the Spirit of Sports",
    logo: "/templates/sample-brand-endura-sports/logo.png",
    description:
      "Endura Sports is a leading sports brand dedicated to creating unforgettable offline events and lucky draws for sports enthusiasts. We bring together athletes, fans, and experts for a unique experience that celebrates the spirit of sportsmanship.",
  },
  featured: {
    h1: "SprintPro Release Event",
    p: "Join us for the exclusive release of the SprintPro running shoes. Experience unparalleled comfort and performance.",
    media: {
      $id: "media",
      type: "video",
      src: "/templates/sample-brand-endura-sports/hero.mp4",
    },
  },
  listheader: {
    text: "Upcoming Events",
  },
  tags: [
    "Football",
    "Basketball",
    "Tennis",
    "Running",
    "Cycling",
    "Swimming",
    "Gymnastics",
    "Volleyball",
    "Cricket",
    "Rugby",
    "Baseball",
    "Golf",
    "Hockey",
    "Martial Arts",
    "Surfing",
    "Skiing",
    "Snowboarding",
  ],
  events: [
    {
      date: "2024-08-01",
      attendees: 200,
      title: "Football Fan Fest",
      cta: "Register Now",
      status: "Opens 2024-07-20",
      image: "/templates/sample-brand-endura-sports/collection/001.png",
      tags: ["Football", "Running"],
    },
    {
      date: "2024-09-15",
      attendees: 150,
      title: "Basketball Bash",
      cta: "Sign Up Today",
      status: "Opens 2024-08-30",
      image: "/templates/sample-brand-endura-sports/collection/002.png",
      tags: ["Basketball", "Gymnastics"],
    },
    {
      date: "2024-10-03",
      attendees: 300,
      title: "Tennis Tournament",
      cta: "Join Now",
      status: "Opens 2024-09-15",
      image: "/templates/sample-brand-endura-sports/collection/003.png",
      tags: ["Tennis", "Cycling"],
    },
    {
      date: "2024-11-10",
      attendees: 250,
      title: "Running Marathon",
      cta: "Reserve Your Spot",
      status: "Opens 2024-10-25",
      image: "/templates/sample-brand-endura-sports/collection/004.png",
      tags: ["Running", "Swimming"],
    },
    {
      date: "2024-12-22",
      attendees: 180,
      title: "Cycling Challenge",
      cta: "Get Tickets",
      status: "Opens 2024-12-05",
      image: "/templates/sample-brand-endura-sports/collection/005.png",
      tags: ["Cycling", "Volleyball"],
    },
  ],
} as const;

export const formcollection_sample_003_prism = {
  brand: {
    name: "Prism",
    tagline: "Shining Bright with Every Beat",
    logo: "/templates/sample-brand-prism/logo.png",
    description:
      "Prism is a sensational K-Pop girl group idol known for their electrifying performances and captivating music. We connect with fans through unforgettable concerts, intimate fan meetings, and exciting community events, creating memories that last a lifetime.",
  },
  featured: {
    h1: "Prism World Tour 2024",
    p: "Join Prism on their global tour as they light up stages around the world with their dazzling performances and hit songs. Don't miss out on the chance to experience the magic live.",
    media: {
      $id: "media",
      type: "video",
      src: "/templates/sample-brand-prism/hero.mp4",
    },
  },
  listheader: {
    text: "Upcoming Events",
  },
  tags: [
    "Concert",
    "Fan Meeting",
    "Autograph Session",
    "Community Event",
    "Luck Draw",
    "K-Pop",
    "Live Performance",
    "Meet & Greet",
    "Exclusive Event",
  ],
  events: [
    {
      date: "2024-07-20",
      attendees: 5000,
      title: "Seoul Concert",
      cta: "Buy Tickets",
      status: "Tickets Available",
      image: "/templates/sample-brand-prism/collection/001.png",
      tags: ["Concert", "Live Performance"],
    },
    {
      date: "2024-08-15",
      attendees: 3000,
      title: "Tokyo Fan Meeting",
      cta: "Sign Up Today",
      status: "Opens 2024-07-30",
      image: "/templates/sample-brand-prism/collection/002.png",
      tags: ["Fan Meeting", "Meet & Greet"],
    },
    {
      date: "2024-09-10",
      attendees: 4500,
      title: "New York Concert",
      cta: "Join Now",
      status: "Tickets Available",
      image: "/templates/sample-brand-prism/collection/003.png",
      tags: ["Concert", "Live Performance"],
    },
    {
      date: "2024-10-05",
      attendees: 3500,
      title: "Bangkok Autograph Session",
      cta: "Reserve Your Spot",
      status: "Opens 2024-09-15",
      image: "/templates/sample-brand-prism/collection/004.png",
      tags: ["Autograph Session", "Meet & Greet"],
    },
    {
      date: "2024-11-22",
      attendees: 2000,
      title: "London Community Event",
      cta: "Get Tickets",
      status: "Opens 2024-11-01",
      image: "/templates/sample-brand-prism/collection/005.png",
      tags: ["Community Event", "Exclusive Event"],
    },
  ],
  luckDraw: {
    title: "Lucky Draw",
    description:
      "Enter our lucky draw for a chance to win exclusive Prism merchandise and VIP tickets to upcoming events.",
    entryDetails:
      "Participants can enter the lucky draw at any of our events. Winners will be announced at the end of each event.",
    prizes: [
      {
        prize: "Exclusive Prism T-shirt",
        image: "https://example.com/images/prism_prizes/tshirt.png",
      },
      {
        prize: "VIP Tickets to Next Concert",
        image: "https://example.com/images/prism_prizes/vip_tickets.png",
      },
      {
        prize: "Signed Album",
        image: "https://example.com/images/prism_prizes/signed_album.png",
      },
      {
        prize: "Meet & Greet Pass",
        image: "https://example.com/images/prism_prizes/meet_greet.png",
      },
    ],
  },
} as const;
