interface Background {
  name: string;
  title: string;
  description: string;
  embed: string;
  url: string;
  preview: [string] | [string, string];
  type: "dynamic" | "static";
}

const data: ReadonlyArray<Background> = [
  {
    name: "aurora",
    title: "Aurora",
    description: "Aurora background",
    embed: "/embed/aurora",
    url: "/embed/aurora",
    preview: ["/preview/aurora.png", "/preview/aurora.mp4"],
    type: "dynamic",
  },
  {
    name: "dots",
    title: "Dots",
    description: "Dots background",
    embed: "/embed/dots",
    url: "/dots",
    preview: ["/preview/dots.png"],
    type: "static",
  },
  {
    name: "globe",
    title: "Globe",
    description: "Globe background",
    embed: "/embed/globe",
    url: "/globe",
    preview: ["/preview/globe.png", "/preview/globe.mp4"],
    type: "dynamic",
  },
  {
    name: "grid",
    title: "Grid",
    description: "Grid background",
    embed: "/embed/grid",
    url: "/grid",
    preview: ["/preview/grid.png"],
    type: "static",
  },
  {
    name: "grid-sm",
    title: "Grid (small)",
    description: "Smaller Grid background",
    embed: "/embed/grid?variant=sm",
    url: "/grid-sm",
    preview: ["/preview/grid-sm.png"],
    type: "static",
  },
  {
    name: "shadergradient-00",
    title: "Halo",
    description: "Shader Gradient 00 Halo",
    embed: "/embed/shadergradient/00",
    url: "/shadergradient-00",
    preview: [
      "/preview/shadergradient-00.png",
      "/preview/shadergradient-00.mp4",
    ],
    type: "dynamic",
  },
  {
    name: "shadergradient-01",
    title: "Pensive",
    description: "Shader Gradient 01 Pensive",
    embed: "/embed/shadergradient/01",
    url: "/shadergradient-01",
    preview: [
      "/preview/shadergradient-01.png",
      "/preview/shadergradient-01.mp4",
    ],
    type: "dynamic",
  },
  {
    name: "shadergradient-02",
    title: "Mint",
    description: "Shader Gradient 02 Mint",
    embed: "/embed/shadergradient/02",
    url: "/shadergradient-02",
    preview: [
      "/preview/shadergradient-02.png",
      "/preview/shadergradient-02.mp4",
    ],
    type: "dynamic",
  },
  {
    name: "shadergradient-03",
    title: "Interstella",
    description: "Shader Gradient 03 Interstella",
    embed: "/embed/shadergradient/03",
    url: "/shadergradient-03",
    preview: [
      "/preview/shadergradient-03.png",
      "/preview/shadergradient-03.mp4",
    ],
    type: "dynamic",
  },
  {
    name: "shadergradient-04",
    title: "Nightly night",
    description: "Shader Gradient 04 Nightly night",
    embed: "/embed/shadergradient/04",
    url: "/shadergradient-04",
    preview: [
      "/preview/shadergradient-04.png",
      "/preview/shadergradient-04.mp4",
    ],
    type: "dynamic",
  },
  {
    name: "shadergradient-05",
    title: "Viola orientalis",
    description: "Shader Gradient 05 Viola orientalis",
    embed: "/embed/shadergradient/05",
    url: "/shadergradient-05",
    preview: [
      "/preview/shadergradient-05.png",
      "/preview/shadergradient-05.mp4",
    ],
    type: "dynamic",
  },
  {
    name: "shadergradient-06",
    title: "Universe",
    description: "Shader Gradient 06 Universe",
    embed: "/embed/shadergradient/06",
    url: "/shadergradient-06",
    preview: [
      "/preview/shadergradient-06.png",
      "/preview/shadergradient-06.mp4",
    ],
    type: "dynamic",
  },
  {
    name: "shadergradient-07",
    title: "Sunset",
    description: "Shader Gradient 07 Sunset",
    embed: "/embed/shadergradient/07",
    url: "/shadergradient-07",
    preview: [
      "/preview/shadergradient-07.png",
      "/preview/shadergradient-07.mp4",
    ],
    type: "dynamic",
  },
  {
    name: "shadergradient-08",
    title: "Madarin",
    description: "Shader Gradient 08 Madarin",
    embed: "/embed/shadergradient/08",
    url: "/shadergradient-08",
    preview: [
      "/preview/shadergradient-08.png",
      "/preview/shadergradient-08.mp4",
    ],
    type: "dynamic",
  },
  {
    name: "shadergradient-09",
    title: "Cotton candy",
    description: "Shader Gradient 09 Cotton candy",
    embed: "/embed/shadergradient/09",
    url: "/shadergradient-09",
    preview: [
      "/preview/shadergradient-09.png",
      "/preview/shadergradient-09.mp4",
    ],
    type: "dynamic",
  },
  {
    name: "shadergradient-85",
    title: "Mint Fresh",
    description: "Shader Gradient 85 Mint Fresh",
    embed: "/embed/shadergradient/85",
    url: "/shadergradient-85",
    preview: [
      "/preview/shadergradient-85.png",
      "/preview/shadergradient-85.mp4",
    ],
    type: "dynamic",
  },
  {
    name: "shadergradient-86",
    title: "Blush Spiral",
    description: "Shader Gradient 86 Blush Spiral",
    embed: "/embed/shadergradient/86",
    url: "/shadergradient-86",
    preview: [
      "/preview/shadergradient-86.png",
      "/preview/shadergradient-86.mp4",
    ],
    type: "dynamic",
  },
  {
    name: "shadergradient-87",
    title: "Crimson Tide",
    description: "Shader Gradient 87 Crimson Tide",
    embed: "/embed/shadergradient/87",
    url: "/shadergradient-87",
    preview: [
      "/preview/shadergradient-87.png",
      "/preview/shadergradient-87.mp4",
    ],
    type: "dynamic",
  },
  {
    name: "shadergradient-88",
    title: "Solar Vortex",
    description: "Shader Gradient 88 Solar Vortex",
    embed: "/embed/shadergradient/88",
    url: "/shadergradient-88",
    preview: [
      "/preview/shadergradient-88.png",
      "/preview/shadergradient-88.mp4",
    ],
    type: "dynamic",
  },
  {
    name: "shadergradient-89",
    title: "Shadow Wave",
    description: "Shader Gradient 89 Shadow Wave",
    embed: "/embed/shadergradient/89",
    url: "/shadergradient-89",
    preview: [
      "/preview/shadergradient-89.png",
      "/preview/shadergradient-89.mp4",
    ],
    type: "dynamic",
  },
  {
    name: "shadergradient-90",
    title: "Emerald Glow",
    description: "Shader Gradient 90 Emerald Glow",
    embed: "/embed/shadergradient/90",
    url: "/shadergradient-90",
    preview: [
      "/preview/shadergradient-90.png",
      "/preview/shadergradient-90.mp4",
    ],
    type: "dynamic",
  },
  {
    name: "shadergradient-91",
    title: "Lunar wave",
    description: "Shader Gradient 91 Lunar wave",
    embed: "/embed/shadergradient/91",
    url: "/shadergradient-91",
    preview: [
      "/preview/shadergradient-91.png",
      "/preview/shadergradient-91.mp4",
    ],
    type: "dynamic",
  },
  {
    name: "shadergradient-92",
    title: "Lemon glow",
    description: "Shader Gradient 92 Lemon glow",
    embed: "/embed/shadergradient/92",
    url: "/shadergradient-92",
    preview: [
      "/preview/shadergradient-92.png",
      "/preview/shadergradient-92.mp4",
    ],
    type: "dynamic",
  },
  {
    name: "shadergradient-93",
    title: "Twilight blue",
    description: "Shader Gradient 93 Twilight blue",
    embed: "/embed/shadergradient/93",
    url: "/shadergradient-93",
    preview: ["/preview/shadergradient-93.png"],
    type: "static",
  },
  {
    name: "shadergradient-94",
    title: "Abyss blue",
    description: "Shader Gradient 94 Abyss blue",
    embed: "/embed/shadergradient/94",
    url: "/shadergradient-94",
    preview: [
      "/preview/shadergradient-94.png",
      "/preview/shadergradient-94.mp4",
    ],
    type: "dynamic",
  },
  {
    name: "shadergradient-95",
    title: "Lavender mist",
    description: "Shader Gradient 95 Lavender mist",
    embed: "/embed/shadergradient/95",
    url: "/shadergradient-95",
    preview: [
      "/preview/shadergradient-95.png",
      "/preview/shadergradient-95.mp4",
    ],
    type: "dynamic",
  },
  {
    name: "shadergradient-96",
    title: "Aqua noir",
    description: "Shader Gradient 96 Aqua noir",
    embed: "/embed/shadergradient/96",
    url: "/shadergradient-96",
    preview: [
      "/preview/shadergradient-96.png",
      "/preview/shadergradient-96.mp4",
    ],
    type: "dynamic",
  },
  {
    name: "shadergradient-97",
    title: "Electric violet",
    description: "Shader Gradient 97 Electric violet",
    embed: "/embed/shadergradient/97",
    url: "/shadergradient-97",
    preview: [
      "/preview/shadergradient-97.png",
      "/preview/shadergradient-97.mp4",
    ],
    type: "dynamic",
  },
  {
    name: "shadergradient-98",
    title: "Pastel dream",
    description: "Shader Gradient 98 Pastel dream",
    embed: "/embed/shadergradient/98",
    url: "/shadergradient-98",
    preview: [
      "/preview/shadergradient-98.png",
      "/preview/shadergradient-98.mp4",
    ],
    type: "dynamic",
  },
  {
    name: "shadergradient-99",
    title: "Skyline gradient",
    description: "Shader Gradient 99 Skyline gradient",
    embed: "/embed/shadergradient/99",
    url: "/shadergradient-99",
    preview: [
      "/preview/shadergradient-99.png",
      "/preview/shadergradient-99.mp4",
    ],
    type: "dynamic",
  },
];

export default data;
