export {
  SYSTEM_GF_KEY_STARTS_WITH,
  SYSTEM_GF_TIMEZONE_UTC_OFFSET_KEY,
  SYSTEM_GF_FINGERPRINT_VISITORID_KEY,
  SYSTEM_GF_CUSTOMER_UUID_KEY,
  SYSTEM_GF_CUSTOMER_EMAIL_KEY,
  SYSTEM_GF_CUSTOMER_PHONE_KEY,
  SYSTEM_GF_CUSTOMER_NAME_KEY,
  SYSTEM_GF_SESSION_KEY,
} from "@grida/forms";
