export const AXES: Record<string, string> = {
  // Standard axes
  wght: "Weight",
  wdth: "Width",
  slnt: "Slant",
  ital: "Italic",
  opsz: "Optical Size",
  // Known custom axes
  GRAD: "Grade",
  CASL: "Casual",
  CRSV: "Cursive",
  MONO: "Monospace",
  ROND: "Roundness",
  SOFT: "Softness",
  WONK: "Wonky",
  BLED: "Bleed",
  BNCE: "Bounce",
  EHLT: "Edge Highlight",
  ELGR: "Element Grid",
  ELSH: "Element Shape",
  EDPT: "Extrusion Depth",
  FILL: "Fill",
  FLAR: "Flare",
  HEXP: "Hyper Expansion",
  MORF: "Morph",
  YTAS: "Parametric Ascender Height",
  XTRA: "Parametric Counter Width",
  YTDE: "Parametric Descender Depth",
  YTFI: "Parametric Figure Height",
  YTLC: "Parametric Lowercase Height",
  YTUC: "Parametric Uppercase Height",
  YELA: "Vertical Element Alignment",
  VOLM: "Volume",
  YEAR: "Year",
  ARRO: "AR Retinal Resolution",
  INFM: "Informality",
  SCAN: "Scanlines",
  SHRP: "Sharpness",
} as const;

export type OpentypeAxisTag = keyof typeof AXES;
